import type { AuthoringDocument } from "../../../src/lib/domain";

const common = {
  publicationStatus: "reviewed" as const,
  obligationStatus: "open" as const,
  statementIds: [],
  reviewedAt: "2026-09-07",
};

export const populismResearchDocuments = [
  {
    documentType: "entity",
    entity: {
      id: "populism-definition-sensitivity",
      kind: "research-obligation",
      label: "Populism classification sensitivity",
      description: "Test how rival definitions change classification of the same material.",
      obligationType: "research-gap",
      question: "Which people, parties, or practices enter or leave the category when ideology, discourse, style, strategy, or anti-pluralism supplies the rule?",
      target: { kind: "concept", id: "populism" },
      targetSectionId: "definitions",
      addressedStatementIds: ["populism-contested-category", "mudde-thin-ideology", "weyland-strategy-definition", "aslanidis-discourse-definition", "moffitt-style-definition", "muller-antipluralism"],
      currentLimitation: "Existing comparisons do not apply every rival definition systematically to the same multilingual evidence corpus.",
      evidenceNeeded: "A preregistered coding comparison with original-language texts, multiple coders, explicit units of analysis, and disagreement reporting.",
      scope: "Selected speeches, organizations, and practices in named periods; not a universal ranking of definitions.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "populism-people-exclusions",
      kind: "research-obligation",
      label: "Exclusions from the people",
      description: "Identify who people-claims include, silence, or exclude.",
      obligationType: "counterargument",
      question: "Which constituencies did each formation include in 'the people,' and which people lacked voice, membership, rights, or practical access?",
      target: { kind: "concept", id: "populism" },
      addressedStatementIds: ["people-is-constructed", "peoples-party-case-limit", "peronism-self-description-boundary"],
      currentLimitation: "National platforms and leadership texts do not establish how marginalized participants understood or contested the represented people.",
      evidenceNeeded: "Constituency-grounded newspapers, organization records, oral histories, voting and membership rules, and scholarship on race, gender, ethnicity, class, and citizenship.",
      scope: "Each selected formation in its own place and period.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "populism-inclusion-antipluralism",
      kind: "research-obligation",
      label: "Democratic inclusion and anti-pluralism",
      description: "Separate agenda inclusion from exclusive representation and institutional restraint.",
      obligationType: "counterevidence",
      question: "When did a people-versus-elite appeal widen effective participation, and when did it undermine opposition, rights, contestation, or independent institutions?",
      target: { kind: "concept", id: "populism" },
      targetSectionId: "democracy",
      addressedStatementIds: ["anti-elitism-antipluralism-distinct", "democratic-ambivalence"],
      currentLimitation: "General theory identifies both possibilities but the selected evidence does not measure them consistently across cases.",
      evidenceNeeded: "Period-specific franchise, participation, opposition, media, judicial, administrative, and rights evidence with plausible rival explanations.",
      scope: "Named institutions before, during, and after selected mobilizations.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "populism-leader-organization-counterfactual",
      kind: "research-obligation",
      label: "Leader and organization counterfactual",
      description: "Test whether personalistic leadership or organization drove mobilization and durability.",
      obligationType: "counterfactual",
      question: "How would mobilization and institutional change likely have differed without the named leader, party organization, unions, associations, or media system?",
      target: { kind: "concept", id: "populism" },
      addressedStatementIds: ["weyland-strategy-definition", "sata-urban-poor-strategy", "thaksin-classification-developed"],
      currentLimitation: "The selected sources describe leader-centered strategies but do not isolate leadership from organization and political opportunity.",
      evidenceNeeded: "Within-case process tracing, succession episodes, organizational records, and comparisons with similar campaigns lacking the named leader.",
      scope: "The Zambia and Thailand periods selected here, with separately bounded follow-up cases.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "populism-translation-category-travel",
      kind: "research-obligation",
      label: "Translation and category travel",
      description: "Test how scholarly categories travel across political languages and regions.",
      obligationType: "research-gap",
      question: "How do pueblo, people, and ประชานิยม differ in the selected sources, and who authorized each translation or external classification?",
      target: { kind: "concept", id: "populism" },
      addressedStatementIds: ["populism-label-provenance", "prachaniyom-translation-boundary"],
      currentLimitation: "English-language scholarship and translated official texts cannot establish that political terms share one field of meaning.",
      evidenceNeeded: "Original-language editions, named translators, locally authored conceptual histories, and reception evidence showing how actors used or rejected each label.",
      scope: "Spanish, Thai, English, and additional languages only as separately researched.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "populism-policy-attribution",
      kind: "research-obligation",
      label: "Policy attribution and outcomes",
      description: "Separate labels, proposals, enactment, use, outputs, and causal effects.",
      obligationType: "counterfactual",
      question: "Which selected policies depended on populist mobilization, and what would likely have happened to their implementation and outcomes without it?",
      target: { kind: "concept", id: "populism" },
      addressedStatementIds: ["redistribution-insufficient", "omaha-institutional-demands", "peron-social-justice-constitution", "thai-policy-program"],
      currentLimitation: "Platforms and enacted texts establish proposals or formal rules but do not isolate populist framing as their cause or measure distributional results.",
      evidenceNeeded: "Implementation records, outcome measures, rival-policy histories, and causal research that separates rhetoric from institutional design.",
      scope: "Named policies within the four bounded cases; no inference from label to effect.",
      ...common,
    },
  },
] satisfies AuthoringDocument[];
