import type { AuthoringDocument } from "../../../src/lib/domain";

const common = {
  publicationStatus: "reviewed" as const,
  obligationStatus: "open" as const,
  statementIds: [],
  reviewedAt: "2026-09-08",
};

const target = {
  kind: "case" as const,
  id: "south-carolina-reconstruction-political-membership",
};

export const southCarolinaReconstructionResearchDocuments = [
  {
    documentType: "entity",
    entity: {
      id: "sc-reconstruction-paramilitary-electoral-effect",
      kind: "research-obligation",
      label: "County-level electoral effects of paramilitary intimidation",
      description: "A counterfactual question about registration, turnout, ballot choice, and counted returns in the 1876 South Carolina election.",
      obligationType: "counterfactual",
      question: "How did Red Shirt and rifle-club intimidation change registration, turnout, ballot choice, or counted returns in specific South Carolina counties during the 1876 election?",
      target,
      targetSectionId: "contest-and-transfer",
      addressedStatementIds: ["sc-rifle-club-intimidation-purpose", "sc-rifle-club-hampton-support-purpose", "sc-disputed-election-rival-governors"],
      currentLimitation: "The selected evidence describes the organizations' attributed purposes and a disputed statewide result but does not identify county-level electoral effects.",
      evidenceNeeded: "County and precinct registration and returns, contemporaneous testimony, campaign records, and scholarship distinguishing intimidation from fraud, party organization, and ordinary turnout change.",
      scope: "The 1876 South Carolina election, with county-specific outcomes; not a general causal estimate for Reconstruction elections.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-reconstruction-federal-withdrawal-control-effect",
      kind: "research-obligation",
      label: "Institutional effect of continued State House protection",
      description: "A counterfactual question about practical and legal control after the April 1877 federal troop decision.",
      obligationType: "counterfactual",
      question: "What institutional control would Chamberlain's government likely have retained after 10 April 1877 if federal troops had continued guarding the State House?",
      target,
      targetSectionId: "contest-and-transfer",
      addressedStatementIds: ["sc-statehouse-troops-withdrawn-april-10", "sc-chamberlain-transfer-correspondence-april-10", "sc-executive-office-transferred-april-11"],
      currentLimitation: "The selected chronology establishes troop withdrawal, transfer correspondence, and office transfer but not the legal or practical control that continued protection would have sustained.",
      evidenceNeeded: "Hayes administration orders and correspondence, both state claimants' records, troop mission orders, and competing historical analyses of legal authority and practical control.",
      scope: "Control of South Carolina's executive institutions after April 10, 1877; not why Reconstruction ended nationally.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-reconstruction-enforcement-deterrence-duration",
      kind: "research-obligation",
      label: "Duration and geography of federal deterrence",
      description: "A counterevidence need testing the attributed short-term effect of the 1871–72 prosecutions.",
      obligationType: "counterevidence",
      question: "Did the 1871–72 arrests and prosecutions reduce organized political violence, and if so, for how long and in which South Carolina counties?",
      target,
      targetSectionId: "federal-enforcement",
      addressedStatementIds: ["sc-federal-mass-arrests-1871", "sc-klan-prosecution-results", "sc-klan-enforcement-short-term-assessment"],
      currentLimitation: "The FJC offers a statewide short-term assessment, while the selected evidence does not measure changes by county or distinguish displacement from deterrence.",
      evidenceNeeded: "County-level incident records before and after enforcement, prosecution dispositions, election conditions, and scholarship testing displacement or organizational change.",
      scope: "South Carolina counties during and after the 1871–72 prosecutions; the later durability claim remains analytically separate from trial results.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-reconstruction-federal-protection-durability",
      kind: "research-obligation",
      label: "Durability of federal political-rights protection",
      description: "A research gap testing the FJC's longer-run assessment and the institutional mechanisms that could explain it.",
      obligationType: "research-gap",
      question: "What evidence supports or qualifies the Federal Judicial Center's conclusion that the South Carolina prosecutions did not secure durable protection for Black political rights, and which institutional mechanisms best explain the observed trajectory?",
      target,
      targetSectionId: "federal-enforcement",
      addressedStatementIds: ["sc-klan-enforcement-durability-limit"],
      currentLimitation: "The FJC states a longer-run conclusion extending beyond the 1871–72 trial Episode, while the selected evidence does not separate the institutional mechanisms behind that result.",
      evidenceNeeded: "Federal appropriations and personnel records, Justice Department and presidential correspondence, state enforcement records, political-rights incidents, and competing scholarship covering 1873–1885.",
      scope: "Durable federal protection of Black political rights in South Carolina after the 1871–72 prosecutions through the FJC account's 1885 horizon; not a nationwide explanation of Reconstruction's end.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-reconstruction-republican-coalition-division-1876",
      kind: "research-obligation",
      label: "Republican coalition divisions in the 1876 contest",
      description: "A research gap about governing capacity and conflict inside South Carolina's Republican coalition.",
      obligationType: "research-gap",
      question: "Which divisions within South Carolina's Republican coalition affected governing capacity or the 1876 contest, independently of paramilitary coercion?",
      target,
      targetSectionId: "comparisons-and-open-questions",
      addressedStatementIds: [],
      currentLimitation: "The selected records establish coercion and rival gubernatorial claims but do not reconstruct conflicts inside the Republican coalition.",
      evidenceNeeded: "Party and convention records, officeholder correspondence, patronage and fiscal disputes, and competing inspected scholarship.",
      scope: "South Carolina Republican coalition divisions relevant to the 1876 contest; no assumption that one internal division determined the result.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-reconstruction-women-political-practice",
      kind: "research-obligation",
      label: "Women's political practice outside the franchise",
      description: "A research gap about organizing and participation despite the constitution's male elector rule.",
      obligationType: "research-gap",
      question: "How did Black and white women participate in South Carolina political organizing from 1868 through 1877 despite exclusion from the state franchise?",
      target,
      targetSectionId: "convention-arguments",
      addressedStatementIds: ["sc-whipper-woman-suffrage-argument", "sc-whipper-motion-rejected"],
      currentLimitation: "The proceedings establish Whipper's argument and the convention vote, not women's varied political activity outside formal voting.",
      evidenceNeeded: "Women's petitions, organizational records, testimony, newspapers, and scholarship disaggregated by race, place, and activity.",
      scope: "South Carolina political organizing from 1868 through April 1877; it does not infer common experience across Black and white women.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-reconstruction-post-1877-formal-practice-divergence",
      kind: "research-obligation",
      label: "Formal and practical political access after 1877",
      description: "A research gap about constitutional continuity and changing access after the Case's executive-office boundary.",
      obligationType: "research-gap",
      question: "Which 1868 electoral and officeholding provisions remained formally in force after 11 April 1877, and how did access or enforcement change before the 1895 constitution?",
      target,
      targetSectionId: "changed-membership",
      addressedStatementIds: ["sc-office-transfer-case-boundary"],
      currentLimitation: "The selected Case ends with transfer of the executive office and does not establish the subsequent life or enforcement of each constitutional rule.",
      evidenceNeeded: "Dated constitutional amendments, election and office records, statutes, court decisions, and scholarship through 1895.",
      scope: "South Carolina from April 11, 1877 through the 1895 constitution; evidence from this later period must not be back-projected into the bounded Case.",
      ...common,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-hamburg-casualty-identity-sequence-reconciliation",
      kind: "research-obligation",
      label: "Hamburg casualty identities and sequence",
      description: "A counterevidence need created by conflicting execution counts and incomplete victim-membership information.",
      obligationType: "counterevidence",
      question: "How many captives were killed or wounded during the Hamburg confrontation and its overnight aftermath, which victims belonged to the militia company, and what dates and sequence do the completed inquest testimony and specialist studies establish?",
      target,
      targetSectionId: "contest-and-transfer",
      addressedStatementIds: ["sc-hamburg-bradley-six-executions-account", "sc-hamburg-stone-five-prisoners-account", "sc-hamburg-victim-membership-boundary", "sc-hamburg-casualty-count-conflict"],
      currentLimitation: "Bradley reports six executions, while Stone reports five prisoners deliberately killed and three wounded and distinguishes company members from nonmembers.",
      evidenceNeeded: "The completed coroner inquest and witness testimony, victim-level identification, contemporaneous court or investigation records, and specialist scholarship that reconciles the accounts.",
      scope: "The July 8 confrontation and overnight aftermath in Hamburg; the shared evidence of killings does not depend on resolving the exact count.",
      ...common,
    },
  },
] satisfies AuthoringDocument[];
