import type { AuthoringDocument } from "../../../src/lib/domain";

const reviewed = { publicationStatus: "reviewed" as const };

export const centralPlanningApproachDocuments = [
  { documentType: "entity", entity: { id: "central-planning-arrangements", kind: "collection", label: "Central planning", description: "A Means family in which authorized bodies coordinate a substantial scope of production, investment, or allocation through plans.", inclusionRule: "Include only concrete Means whose binding or directive plans specify authority, scope, information, targets, revision, enforcement, and ownership context.", editorialPurpose: "Keep central planning searchable without treating it as an ideology, ownership form, or one uniform institution.", ...reviewed } },
  { documentType: "entity", entity: { id: "controlled-materials-allocation", kind: "means", label: "Controlled materials allocation", description: "A mechanism that reconciles program requirements with scarce-material supply and passes authorized allotments through agencies and production chains.", institutionalForm: "A central board estimates available materials, approves quarterly claimant allotments, and conditions producers' orders on authorized schedules while agencies and firms subdivide allotments down supply chains.", ...reviewed } },
  { documentType: "entity", entity: { id: "us-wartime-production-mobilization", kind: "approach", label: "United States wartime production mobilization", description: "The federal mobilization approach that combined military procurement, civilian production controls, private contracting, and scarce-material allocation during the Second World War.", scope: "United States federal production mobilization from 1942 to 1945; not a name for the whole economy, a permanent system, or every wartime control.", ...reviewed } },
  { documentType: "entity", entity: { id: "war-production-board", kind: "organization", label: "War Production Board", description: "The federal civilian agency directing wartime production priorities and materials allocation.", scope: "United States federal production coordination from January 1942 until its termination in November 1945.", ...reviewed } },
  { documentType: "entity", entity: { id: "wpb-requirements-committee", kind: "organization", label: "War Production Board Requirements Committee", description: "The WPB body that estimated controlled-material supplies and made initial allotments among claimant agencies.", scope: "Controlled Materials Plan supply estimates and claimant-agency allotments during the plan's operation.", ...reviewed } },
  { documentType: "entity", entity: { id: "cmp-claimant-agencies", kind: "organization", label: "Controlled Materials Plan claimant agencies", description: "The military and civilian agencies receiving and subdividing controlled-material allotments.", scope: "The officially designated CMP claimant agencies, treated collectively only for their shared allotment role.", ...reviewed } },
] satisfies AuthoringDocument[];
