import type { AuthoringDocument } from "../../../src/lib/domain";

const base = { publicationStatus: "reviewed" as const };

export const vocabularyDocuments = [
  { documentType: "entity", entity: { id: "political-economic-ideas", kind: "concept-scheme", label: "Political-economic ideas", description: "Concepts used to describe political and economic institutions.", scope: "A project vocabulary for contested political-economic ideas.", ...base } },
  { documentType: "entity", entity: { id: "institutional-domains", kind: "concept-scheme", label: "Institutional domains", description: "Domains in which authority, rules, and resources are organized.", scope: "Cross-cutting political, economic, social, legal, and cultural domains.", ...base } },
  { documentType: "entity", entity: { id: "social-democracy", kind: "concept", label: "Social democracy", description: "A contested family of approaches combining democratic politics with economic and social reform.", schemeIds: ["political-economic-ideas"], alternateLabels: ["social-democratic"], scopeNote: "Use for the broader contested concept; do not treat any government or policy as its complete embodiment.", externalRefs: [{ system: "wikipedia", url: "https://en.wikipedia.org/wiki/Social_democracy", purpose: "orientation", language: "en", checkedAt: "2026-09-04" }, { system: "wikidata", id: "Q130471", url: "https://www.wikidata.org/wiki/Q130471", purpose: "identity", match: "exact", checkedAt: "2026-09-04" }], ...base } },
  { documentType: "entity", entity: { id: "economic-democracy", kind: "concept", label: "Economic democracy", description: "A contested family of proposals for extending democratic participation or accountability into economic ownership and decision-making.", schemeIds: ["political-economic-ideas"], scopeNote: "Use as an analytical concept, not a claim that any particular ownership mechanism gives workers or the public effective control.", externalRefs: [{ system: "wikipedia", url: "https://en.wikipedia.org/wiki/Economic_democracy", purpose: "orientation", language: "en", checkedAt: "2026-09-04" }], ...base } },
  { documentType: "entity", entity: { id: "market-socialism", kind: "concept", label: "Market socialism", description: "A diverse family of models combining market coordination with some form of social or collective ownership.", schemeIds: ["political-economic-ideas"], scopeNote: "Do not treat every public investor, regulated market, or mixed economy as market socialism; ownership, control, and the allocation of returns all matter.", externalRefs: [{ system: "wikipedia", url: "https://en.wikipedia.org/wiki/Market_socialism", purpose: "orientation", language: "en", checkedAt: "2026-09-04" }, { system: "wikidata", id: "Q268919", url: "https://www.wikidata.org/wiki/Q268919", purpose: "identity", match: "exact", checkedAt: "2026-09-04" }], ...base } },
  { documentType: "entity", entity: { id: "social-ownership", kind: "concept", label: "Social ownership", description: "A family of arrangements in which claims to productive assets or their returns are held for workers, communities, or society rather than solely for private owners.", schemeIds: ["political-economic-ideas"], scopeNote: "Distinguish legal title, beneficial ownership, allocation of returns, and effective control; public ownership alone does not settle all four.", externalRefs: [{ system: "wikipedia", url: "https://en.wikipedia.org/wiki/Social_ownership", purpose: "orientation", language: "en", checkedAt: "2026-09-04" }, { system: "wikidata", id: "Q1190277", url: "https://www.wikidata.org/wiki/Q1190277", purpose: "identity", match: "close", checkedAt: "2026-09-04" }], ...base } },
  { documentType: "entity", entity: { id: "collective-capital-formation", kind: "concept", label: "Collective capital formation", description: "Institutional arrangements that accumulate capital through collectively governed funds.", schemeIds: ["political-economic-ideas"], scopeNote: "Distinguish collective accumulation from direct worker ownership or state ownership.", ...base } },
  { documentType: "entity", entity: { id: "institutional-abolition", kind: "concept", label: "Institutional abolition", description: "The legal termination of an institution or governing body.", schemeIds: ["political-economic-ideas"], scopeNote: "Use as an Event kind; it does not by itself explain why an institution ended or what replaced it.", ...base } },
  { documentType: "entity", entity: { id: "ownership-and-control", kind: "domain", label: "Ownership and control", description: "How claims over productive assets and decision authority are distributed.", sphere: "cross-cutting", schemeIds: ["institutional-domains"], ...base } },
] satisfies AuthoringDocument[];
