import type { AuthoringDocument, DomainEntity } from "../../../src/lib/domain";

const reviewed = { publicationStatus: "reviewed" as const };

const entities = [
  {
    id: "west-sumatra",
    kind: "place",
    label: "West Sumatra",
    description: "An Indonesian province on the island of Sumatra.",
    placeType: "region",
  },
  {
    id: "nagari-koto-tinggi-agam",
    kind: "place",
    label: "Nagari Koto Tinggi, Agam",
    description:
      "The nagari in Baso subdistrict, Agam Regency, examined during October 2016 fieldwork.",
    placeType: "institutional-jurisdiction",
  },
  {
    id: "nagari-bonjol-dharmasraya",
    kind: "place",
    label: "Nagari Bonjol, Dharmasraya",
    description:
      "The nagari in Koto Besar subdistrict, Dharmasraya Regency, examined during 2016 communal-forest fieldwork.",
    placeType: "institutional-jurisdiction",
  },
  {
    id: "nurdin-nagari-governance-work",
    kind: "work",
    label: "New Value Within Old Structure",
    description:
      "Ismail Nurdin’s public-administration case study of adat revival and local capacity in Koto Tinggi.",
    title:
      "New Value Within Old Structure: The Creation of Organizational Culture of Nagari in Indonesian Decentralization Era",
    workType: "article",
    originalPublicationYear: 2017,
  },
  {
    id: "nurdin-nagari-governance-source",
    kind: "source",
    label: "Koto Tinggi nagari governance study (2017)",
    description:
      "The open-access journal manifestation, whose PDF uses the English running title ‘Adat Revival and Local Capacity in Indonesia: The Case of Nagari.’",
    title:
      "New Value Within Old Structure: The Creation of Organizational Culture of Nagari in Indonesian Decentralization Era",
    sourceType: "article",
    workId: "nurdin-nagari-governance-work",
    contributorDisplay: ["Ismail Nurdin"],
    publicationYear: 2017,
    publisher: "Sosiohumaniora, Universitas Padjadjaran",
    identifiers: { doi: "10.24198/sosiohumaniora.v19i2.11398" },
    resourceLinks: [
      {
        purpose: "authorized-reading",
        url: "https://journals.unpad.ac.id/sosiohumaniora/article/view/11398",
        label: "Read the journal article",
      },
    ],
  },
  {
    id: "mutolib-bonjol-ulayat-work",
    kind: "work",
    label: "Gender Inequality in Nagari Bonjol Ulayat Management",
    description:
      "A field study of communal-forest management within the Melayu clan of Nagari Bonjol.",
    title:
      "Gender Inequality and the Oppression of Women within Minangkabau Matrilineal Society: A Case Study of the Management of Ulayat Forest Land in Nagari Bonjol, Dharmasraya District, West Sumatra Province, Indonesia",
    workType: "article",
    originalPublicationYear: 2016,
  },
  {
    id: "mutolib-bonjol-ulayat-source",
    kind: "source",
    label: "Nagari Bonjol ulayat forest study (2016)",
    description:
      "The open-access peer-reviewed article by researchers at Andalas University and the University of Lampung.",
    title:
      "Gender Inequality and the Oppression of Women within Minangkabau Matrilineal Society: A Case Study of the Management of Ulayat Forest Land in Nagari Bonjol, Dharmasraya District, West Sumatra Province, Indonesia",
    sourceType: "article",
    workId: "mutolib-bonjol-ulayat-work",
    contributorDisplay: ["Abdul Mutolib", "Yonariza", "Mahdi", "Hanung Ismono"],
    publicationYear: 2016,
    publisher: "Asian Women",
    identifiers: { doi: "10.14431/aw.2016.09.32.3.23" },
    resourceLinks: [
      {
        purpose: "authorized-reading",
        url: "https://e-asianwomen.org/search.php?where=aview&id=10.14431/aw.2016.09.32.3.23&code=0274AW&vmode=FULL",
        label: "Read the journal article",
      },
    ],
  },
  {
    id: "blackwood-webs-power-work",
    kind: "work",
    label: "Webs of Power",
    description:
      "Evelyn Blackwood’s ethnography of gender, kinship, and power in one rural Minangkabau village.",
    title: "Webs of Power: Women, Kin, and Community in a Sumatran Village",
    workType: "book",
    originalPublicationYear: 2000,
  },
  {
    id: "blackwood-webs-power-source",
    kind: "source",
    label: "Webs of Power (2000)",
    description:
      "The Rowman & Littlefield edition, checked through the publisher’s authorized preview.",
    title: "Webs of Power: Women, Kin, and Community in a Sumatran Village",
    sourceType: "edition",
    workId: "blackwood-webs-power-work",
    contributorDisplay: ["Evelyn Blackwood"],
    publicationYear: 2000,
    publisher: "Rowman & Littlefield",
    identifiers: { isbn10: "0847699110", isbn13: "9780847699117" },
    resourceLinks: [
      {
        purpose: "publisher",
        url: "https://www.bloomsbury.com/us/webs-of-power-9780847699117/",
        label: "View the publisher record",
      },
      {
        purpose: "authorized-reading",
        url: "https://books.google.com/books?id=Bs1t0QUOeKsC",
        label: "Inspect the 2000 edition preview",
      },
    ],
  },
  {
    id: "sanday-women-center-work",
    kind: "work",
    label: "Women at the Center",
    description:
      "Peggy Reeves Sanday’s ethnography and proposed redefinition of matriarchy in a Minangkabau setting.",
    title: "Women at the Center: Life in a Modern Matriarchy",
    workType: "book",
    originalPublicationYear: 2002,
  },
  {
    id: "sanday-women-center-excerpt-source",
    kind: "source",
    label: "Women at the Center author excerpt",
    description:
      "Sanday’s University of Pennsylvania author page presenting the book’s preface and interpretive framing.",
    title: "Women at the Center: Life in a Modern Matriarchy",
    sourceType: "web-page",
    workId: "sanday-women-center-work",
    contributorDisplay: ["Peggy Reeves Sanday"],
    publicationYear: 2002,
    publisher: "University of Pennsylvania",
    resourceLinks: [
      {
        purpose: "authorized-reading",
        url: "https://web.sas.upenn.edu/psanday/books/women-at-the-center-life-in-a-modern-matriarchy/",
        label: "Read the author’s excerpt",
      },
    ],
  },
  {
    id: "sebastian-matrilineal-muslims-work",
    kind: "work",
    label: "Matrilineal Practices among Muslims",
    description:
      "Aleena Sebastian’s ethnographic study of changing Minangkabau matrilineal practices.",
    title:
      "Matrilineal Practices among Muslims: An Ethnographic Study of the Minangkabau of West Sumatra",
    workType: "article",
    originalPublicationYear: 2022,
  },
  {
    id: "sebastian-matrilineal-muslims-source",
    kind: "source",
    label: "Matrilineal Practices among Muslims (2022)",
    description:
      "The SAGE article record and abstract for Sebastian’s historically situated ethnographic account.",
    title:
      "Matrilineal Practices among Muslims: An Ethnographic Study of the Minangkabau of West Sumatra",
    sourceType: "article",
    workId: "sebastian-matrilineal-muslims-work",
    contributorDisplay: ["Aleena Sebastian"],
    publicationYear: 2022,
    publisher: "Ethnography, SAGE Publications",
    identifiers: { doi: "10.1177/14661381221147137" },
    resourceLinks: [
      {
        purpose: "publisher",
        url: "https://journals.sagepub.com/doi/10.1177/14661381221147137",
        label: "View the journal article",
      },
    ],
  },
  {
    id: "mardoni-matrilineal-data-center-work",
    kind: "work",
    label: "Pusat Data Matrilineal",
    description:
      "An Indonesian-language account of the West Sumatra cultural-preservation office’s matrilineal data center.",
    title:
      "Pusat Data Matrilineal Sebagai Sumber Sejarah dan Budaya Minangkabau",
    workType: "other",
    originalPublicationYear: 2019,
  },
  {
    id: "mardoni-matrilineal-data-center-source",
    kind: "source",
    label: "Pusat Data Matrilineal (2019)",
    description:
      "Mardoni’s Indonesian-language article for the West Sumatra cultural-preservation office.",
    title:
      "Pusat Data Matrilineal Sebagai Sumber Sejarah dan Budaya Minangkabau",
    sourceType: "web-page",
    workId: "mardoni-matrilineal-data-center-work",
    contributorDisplay: ["Mardoni"],
    publicationYear: 2019,
    publisher: "Balai Pelestarian Nilai Budaya Sumatera Barat",
    resourceLinks: [
      {
        purpose: "publisher",
        url: "https://kebudayaan.kemdikbud.go.id/bpnbsumbar/pusat-data-matrilineal-sebagai-sumber-sejarah-dan-budaya-minangkabau/",
        label: "Read the Indonesian-language article",
      },
    ],
  },
  {
    id: "west-sumatra-nagari-law-2018-work",
    kind: "work",
    label: "West Sumatra Nagari Regulation (2018)",
    description:
      "The provincial regulation governing nagari as customary-law community government after the two case periods.",
    title:
      "Peraturan Daerah Provinsi Sumatera Barat Nomor 7 Tahun 2018 tentang Nagari",
    workType: "law",
    originalPublicationYear: 2018,
  },
  {
    id: "west-sumatra-nagari-law-2018-source",
    kind: "source",
    label: "West Sumatra Regulation No. 7 of 2018",
    description:
      "The official Indonesian legal record and text published through the national audit board’s legislation database.",
    title:
      "Peraturan Daerah Provinsi Sumatera Barat Nomor 7 Tahun 2018 tentang Nagari",
    sourceType: "legal-text",
    workId: "west-sumatra-nagari-law-2018-work",
    contributorDisplay: ["Pemerintah Provinsi Sumatera Barat"],
    publicationYear: 2018,
    publisher: "Database Peraturan BPK",
    resourceLinks: [
      {
        purpose: "publisher",
        url: "https://peraturan.bpk.go.id/Details/99639/perda-",
        label: "Read the official legal record",
      },
    ],
  },
  {
    id: "colombijn-padang-landownership-work",
    kind: "work",
    label: "Dynamics and Dynamite",
    description:
      "Freek Colombijn’s study of landownership and property categories in 1990s Padang.",
    title:
      "Dynamics and Dynamite: Minangkabau Urban Landownership in the 1990s",
    workType: "article",
    originalPublicationYear: 1992,
  },
  {
    id: "colombijn-padang-landownership-source",
    kind: "source",
    label: "Minangkabau urban landownership study (1992)",
    description:
      "The Bijdragen tot de Taal-, Land- en Volkenkunde article, checked against an author-uploaded full-text copy, on property categories and changing landownership in Padang.",
    title:
      "Dynamics and Dynamite: Minangkabau Urban Landownership in the 1990s",
    sourceType: "article",
    workId: "colombijn-padang-landownership-work",
    contributorDisplay: ["Freek Colombijn"],
    publicationYear: 1992,
    publisher: "Brill",
    identifiers: { doi: "10.1163/22134379-90003145" },
    resourceLinks: [
      {
        purpose: "publisher",
        url: "https://doi.org/10.1163/22134379-90003145",
        label: "View the journal article",
      },
      {
        purpose: "authorized-reading",
        url: "https://www.researchgate.net/publication/41017572_Dynamics_and_dynamite_Minangkabau_urban_landownership_in_the_1990s",
        label: "Read the author-uploaded article",
      },
    ],
  },
  {
    id: "matriliny-maternal-descent-definition",
    kind: "statement",
    label: "Matriliny traces descent through mothers",
    description: "A locally published definition of maternal-line descent.",
    statementKind: "definition",
    text: "Mardoni defines Minangkabau matriliny as a kinship system in which people trace descent through their mother and earlier women in that maternal line.",
  },
  {
    id: "matrilocality-residence-distinction",
    kind: "statement",
    label: "Matrilocality concerns residence after marriage",
    description:
      "A distinction between postmarital residence and maternal-line descent.",
    statementKind: "observation",
    text: "Sanday describes husbands moving into their wives’ households in the community she studied.",
  },
  {
    id: "matriliny-does-not-fix-residence",
    kind: "statement",
    label: "Sanday distinguishes descent from residence",
    description: "A bounded distinction in Sanday’s Minangkabau account.",
    statementKind: "observation",
    text: "In Sanday’s account, maternal-line kin organization and husbands’ residence with their wives’ domestic groups are separately described features.",
  },
  {
    id: "matriliny-does-not-fix-property-control",
    kind: "statement",
    label: "Property control varied within Blackwood’s village study",
    description:
      "A bounded observation about descent and effective control.",
    statementKind: "observation",
    text: "Blackwood reports senior women controlling land in the Minangkabau village she studied.",
  },
  {
    id: "matriliny-does-not-fix-office",
    kind: "statement",
    label: "Kin authority and land control differed in Blackwood’s study",
    description: "A bounded observation about land control and formal kin authority.",
    statementKind: "observation",
    text: "Blackwood reports men claiming formal kin authority in the village where she observed senior women controlling land.",
  },
  {
    id: "matriliny-does-not-fix-equality",
    kind: "statement",
    label: "Bonjol’s authors reject an equality inference",
    description: "The Bonjol authors’ bounded interpretation of descent and equality.",
    statementKind: "observation",
    text: "The Bonjol authors caution that matrilineal inheritance in their case did not make women equal participants in decisions over communal forest resources.",
  },
  {
    id: "matriarchy-rule-by-women-dispute",
    kind: "statement",
    label: "Matriarchy has disputed meanings",
    description:
      "A distinction between political domination and Sanday’s maternal-centered interpretation.",
    statementKind: "editorial-interpretation",
    text: "Sanday rejects ‘rule by women’ as the only meaning of matriarchy.",
  },
  {
    id: "matriarchy-sanday-maternal-centered-interpretation",
    kind: "statement",
    label: "Sanday offers a maternal-centered interpretation",
    description: "Sanday’s attributed alternative use of matriarchy.",
    statementKind: "editorial-interpretation",
    text: "Sanday interprets Minangkabau matriarchaat through maternal meanings and women’s social centrality.",
  },
  {
    id: "minangkabau-power-varies-by-relation",
    kind: "statement",
    label: "Power varies across relationships",
    description:
      "Blackwood’s argument against reducing gendered power to formal office alone.",
    statementKind: "editorial-interpretation",
    text: "Blackwood argues from one late-twentieth-century village that formal titles alone did not describe the distribution of gendered power.",
  },
  {
    id: "minangkabau-practices-historically-changing",
    kind: "statement",
    label: "Matrilineal practices change historically",
    description:
      "A historical limit on treating Minangkabau institutions as timeless.",
    statementKind: "observation",
    text: "Sebastian treats Minangkabau matrilineal practices as historically changing rather than timeless.",
  },
  {
    id: "adat-translation-boundary",
    kind: "statement",
    label: "Adat is broader than a single rulebook",
    description: "A translation note for a retained local term.",
    statementKind: "definition",
    text: "Adat can encompass customs, beliefs, norms, and laws; translating it only as ‘customary law’ would narrow the practices examined by the sources.",
  },
  {
    id: "nagari-translation-boundary",
    kind: "statement",
    label: "Nagari joins community and government",
    description: "A translation note for a retained local institution name.",
    statementKind: "definition",
    text: "Nagari is retained for a West Sumatran community and territorial jurisdiction whose customary institutions interact with Indonesian village administration; it is not treated as interchangeable with village in every period.",
  },
  {
    id: "minangkabau-legal-orders-interact",
    kind: "statement",
    label: "Adat, Islamic, and state institutions interact",
    description:
      "A boundary against collapsing distinct legal and institutional orders.",
    statementKind: "observation",
    text: "Sebastian describes Minangkabau adat, Islamic authority, and state law as interacting rather than isolated domains.",
  },
  {
    id: "minangkabau-ancestral-acquired-property-distinction",
    kind: "statement",
    label: "Ancestral and acquired property are distinct categories",
    description:
      "A property-category distinction documented in urban Padang, outside the two cases.",
    statementKind: "observation",
    text: "In 1990s Padang, Colombijn distinguishes high ancestral property from harta pencaharian acquired through a person’s own efforts.",
  },
  {
    id: "koto-tinggi-minangkabau-adat-context",
    kind: "statement",
    label: "Koto Tinggi’s institutions were presented in an adat context",
    description:
      "A narrow link between the named case and Minangkabau institutional context.",
    statementKind: "observation",
    text: "Nurdin presents Koto Tinggi as a Minangkabau nagari in which revived adat institutions interacted with post-decentralization public administration.",
  },
  {
    id: "koto-tinggi-descent-unobserved",
    kind: "statement",
    label: "The Koto Tinggi study does not document descent",
    description: "A limit on the case’s relevance to matriliny.",
    statementKind: "observation",
    text: "Nurdin’s Koto Tinggi study does not separately document descent practice.",
  },
  {
    id: "koto-tinggi-residence-unobserved",
    kind: "statement",
    label: "The Koto Tinggi study does not document postmarital residence",
    description: "A limit on the case’s relevance to matrilocality.",
    statementKind: "observation",
    text: "Nurdin’s Koto Tinggi study does not separately document postmarital residence.",
  },
  {
    id: "koto-tinggi-fieldwork-scope",
    kind: "statement",
    label: "The Koto Tinggi study used four field methods",
    description: "The methods and timing reported for the fieldwork.",
    statementKind: "observation",
    text: "Nurdin reports using observation, interviews, a focus group, and document study in Koto Tinggi during October 2016.",
  },
  {
    id: "koto-tinggi-participant-count-unreported",
    kind: "statement",
    label: "The Koto Tinggi study omits participant counts",
    description: "A method-reporting limit.",
    statementKind: "observation",
    text: "The Koto Tinggi article does not report participant counts.",
  },
  {
    id: "koto-tinggi-womens-voice-unidentified",
    kind: "statement",
    label: "The Koto Tinggi study does not identify women’s testimony",
    description: "A voice and provenance limit.",
    statementKind: "observation",
    text: "The Koto Tinggi article does not identify whose testimony represented women’s experience.",
  },
  {
    id: "koto-tinggi-three-institutions",
    kind: "statement",
    label: "Koto Tinggi had an elected executive",
    description:
      "One element of the reported formal institutional arrangement.",
    statementKind: "observation",
    text: "Under Agam Regulation 12 of 2007, Koto Tinggi’s nagari structure included an elected wali nagari and executive staff.",
  },
  {
    id: "koto-tinggi-representative-council",
    kind: "statement",
    label: "Koto Tinggi had a representative Nagari Council",
    description:
      "One element of the reported formal institutional arrangement.",
    statementKind: "observation",
    text: "Under Agam Regulation 12 of 2007, Koto Tinggi’s nagari structure included a representative Nagari Council.",
  },
  {
    id: "koto-tinggi-customary-council",
    kind: "statement",
    label: "Koto Tinggi had a customary council",
    description:
      "One element of the reported formal institutional arrangement.",
    statementKind: "observation",
    text: "Under Agam Regulation 12 of 2007, Koto Tinggi’s nagari structure included a Kerapatan Adat Nagari customary council drawn from kin groups.",
  },
  {
    id: "koto-tinggi-formal-participation-rules",
    kind: "statement",
    label: "Formal planning rules included women’s-group delegates",
    description: "The stated delegate-participation rule.",
    statementKind: "observation",
    text: "Nurdin reports that the Nagari Council convened development meetings whose invited delegates included representatives of women’s groups.",
  },
  {
    id: "koto-tinggi-formal-decision-rule",
    kind: "statement",
    label: "Formal meetings required a two-thirds quorum",
    description: "The stated quorum rule.",
    statementKind: "observation",
    text: "The formal meeting procedure required a two-thirds quorum.",
  },
  {
    id: "koto-tinggi-formal-speaking-rule",
    kind: "statement",
    label: "The procedure allowed participants to speak",
    description: "The stated deliberation rule.",
    statementKind: "observation",
    text: "The formal meeting procedure allowed participants to express their views before a decision.",
  },
  {
    id: "koto-tinggi-formal-consensus-rule",
    kind: "statement",
    label: "The procedure preferred consensus",
    description: "The stated primary decision rule.",
    statementKind: "observation",
    text: "The formal meeting procedure preferred consensus.",
  },
  {
    id: "koto-tinggi-formal-vote-fallback",
    kind: "statement",
    label: "The procedure allowed a vote if consensus failed",
    description: "The stated fallback decision rule.",
    statementKind: "observation",
    text: "The formal meeting procedure permitted majority voting if consensus failed.",
  },
  {
    id: "koto-tinggi-customary-council-contestation",
    kind: "statement",
    label: "Customary leaders contested the dual-council design",
    description: "A locally reported institutional disagreement.",
    statementKind: "observation",
    text: "The Koto Tinggi customary-council head and another adat leader told Nurdin that the representative council displaced the customary council from legislative work.",
  },
  {
    id: "koto-tinggi-budget-rules-in-use",
    kind: "statement",
    label: "The 2016 draft budget arrived too late for review",
    description:
      "The reported late delivery from the executive to the council.",
    statementKind: "observation",
    text: "In 2016 the wali nagari delivered a draft budget too late for council review.",
  },
  {
    id: "koto-tinggi-budget-postponement",
    kind: "statement",
    label: "Council members secured a budget postponement",
    description: "The reported procedural response to late delivery.",
    statementKind: "observation",
    text: "Council members secured a one-week postponement of the 2016 budget meeting.",
  },
  {
    id: "koto-tinggi-budget-consensus",
    kind: "statement",
    label: "The reconvened budget meeting reached consensus",
    description: "The reported decision after the postponement.",
    statementKind: "observation",
    text: "The reconvened 2016 meeting reached consensus on allocations for infrastructure, housing repairs, and scholarships.",
  },
  {
    id: "koto-tinggi-administrative-capacity-limit",
    kind: "statement",
    label: "Koto Tinggi had incomplete planning documents",
    description: "A reported planning-document gap.",
    statementKind: "observation",
    text: "Nurdin reports incomplete planning documents in Koto Tinggi.",
  },
  {
    id: "koto-tinggi-unspent-funds",
    kind: "statement",
    label: "Koto Tinggi had unspent program funds",
    description: "A reported administrative outcome.",
    statementKind: "observation",
    text: "Nurdin reports unspent program funds in Koto Tinggi.",
  },
  {
    id: "koto-tinggi-accounting-difficulty",
    kind: "statement",
    label: "Koto Tinggi had difficulty meeting accounting requirements",
    description: "A reported administrative constraint.",
    statementKind: "observation",
    text: "Nurdin reports difficulty meeting accounting requirements in Koto Tinggi.",
  },
  {
    id: "koto-tinggi-regulatory-preparation-limit",
    kind: "statement",
    label: "Council members reported inadequate regulatory preparation",
    description: "Attributed testimony about administrative preparation.",
    statementKind: "observation",
    text: "Council members told Nurdin that nagari personnel had not been adequately prepared for changing regulations.",
  },
  {
    id: "bonjol-study-method-and-voice",
    kind: "statement",
    label: "The Bonjol study used four months of participant observation",
    description: "The reported participant-observation period.",
    statementKind: "observation",
    text: "The Bonjol study conducted participant observation from January through April 2016.",
  },
  {
    id: "bonjol-thirteen-key-informants",
    kind: "statement",
    label: "The Bonjol study interviewed 13 key informants",
    description: "One component of the reported sample.",
    statementKind: "observation",
    text: "The Bonjol study interviewed 13 key informants.",
  },
  {
    id: "bonjol-agency-records",
    kind: "statement",
    label: "The Bonjol study used agency records",
    description: "One component of the reported evidence base.",
    statementKind: "observation",
    text: "The Bonjol study examined agency records.",
  },
  {
    id: "bonjol-twenty-seven-women-sample",
    kind: "statement",
    label: "The Bonjol survey sampled 27 married women",
    description: "The reported household-survey sample.",
    statementKind: "observation",
    text: "The Bonjol study reports a random household sample of 27 married women.",
  },
  {
    id: "bonjol-new-nagari-forest-transition",
    kind: "statement",
    label: "Bonjol became a separate nagari around 2000",
    description:
      "The reported administrative transition after decentralization.",
    statementKind: "observation",
    text: "The Bonjol study reports that decentralization ended desa administration around 2000 and Bonjol became a separate nagari.",
  },
  {
    id: "bonjol-concession-end-transition",
    kind: "statement",
    label: "A concession ending changed forest access",
    description: "The reported 2002 forest transition.",
    statementKind: "observation",
    text: "When a forest concession ended in 2002, Melayu-clan leaders and state and company actors negotiated access to land claimed both as state forest and ulayat.",
  },
  {
    id: "bonjol-ulayat-formal-distinction",
    kind: "statement",
    label: "Melayu-clan ulayat was collectively held",
    description:
      "The reported collective holding and member-access arrangement.",
    statementKind: "observation",
    text: "The study describes Melayu-clan ulayat as collectively held land to which clan members could seek access.",
  },
  {
    id: "bonjol-ulayat-delegated-management",
    kind: "statement",
    label: "Named officeholders managed ulayat for the clan",
    description:
      "A distinction between delegated management and personal ownership.",
    statementKind: "observation",
    text: "A Datuak, or titled customary leader, and mamak kepala waris, maternal-kin property managers, managed the Melayu clan’s ulayat rather than owning it personally.",
  },
  {
    id: "bonjol-harta-pusaka-transition",
    kind: "statement",
    label: "Cleared land entered a different inheritance category",
    description: "A distinction between forest access and ancestral property.",
    statementKind: "observation",
    text: "The authors report that forest land opened for cultivation became harta pusaka, rendered harato pusako in their article.",
  },
  {
    id: "bonjol-harta-pusaka-female-line",
    kind: "statement",
    label: "The Bonjol study describes female-line transmission",
    description: "The reported inheritance rule for harta pusaka.",
    statementKind: "observation",
    text: "The Bonjol authors describe harta pusaka as ancestral property transmitted through the female line.",
  },
  {
    id: "bonjol-inheritance-did-not-confer-office-authority",
    kind: "statement",
    label: "Inheritance did not confer forest-negotiation authority",
    description: "A distinction between inheritance and customary office.",
    statementKind: "observation",
    text: "In the Bonjol study, women’s inherited claims did not confer the authority held by male officeholders to negotiate forest access.",
  },
  {
    id: "bonjol-bundo-kanduang-role",
    kind: "statement",
    label: "Bundo Kanduang was an advisory maternal role",
    description: "The advisory maternal role described for Bonjol.",
    statementKind: "observation",
    text: "The Bonjol authors describe Bundo Kanduang as a respected senior maternal figure who could advise customary leaders.",
  },
  {
    id: "bonjol-bundo-kanduang-not-universal-authority",
    kind: "statement",
    label: "Bundo Kanduang did not confer authority on every woman",
    description: "A boundary between a named role and universal authority.",
    statementKind: "editorial-interpretation",
    text: "The Bundo Kanduang role described in the Bonjol study does not establish that every woman controlled ulayat decisions.",
  },
  {
    id: "bonjol-ulayat-sales-rules-in-use",
    kind: "statement",
    label: "Officeholders facilitated outsider land transactions",
    description: "The reported transactions involving Melayu-clan ulayat.",
    statementKind: "observation",
    text: "Key informants reported that male customary officeholders facilitated transactions giving officials and other outsiders access to large areas of Melayu-clan ulayat.",
  },
  {
    id: "bonjol-ulayat-sales-contrary-to-custom",
    kind: "statement",
    label: "The reported sales contradicted the stated customary rule",
    description:
      "The authors’ classification of the transactions against stated custom.",
    statementKind: "observation",
    text: "The authors describe the reported outsider transactions as contrary to the customary rule governing Melayu-clan ulayat.",
  },
  {
    id: "bonjol-neshp-formal-promise",
    kind: "statement",
    label: "The oil-palm agreement promised household plots",
    description: "The stated distribution rule for smallholdings.",
    statementKind: "observation",
    text: "An agreement negotiated by male clan representatives called for 1,000 hectares of oil-palm smallholdings to be divided into two-hectare plots for 500 Bonjol households as compensation for transferred land.",
  },
  {
    id: "bonjol-neshp-distribution-practice",
    kind: "statement",
    label: "Male signatories controlled the recipient list",
    description: "The reported control over smallholding recipients.",
    statementKind: "observation",
    text: "The study reports that male signatories controlled the recipient list for the promised smallholdings.",
  },
  {
    id: "bonjol-neshp-exclusion-outcome",
    kind: "statement",
    label: "The recipient list favored signatories’ associates",
    description: "The reported favoritism in the recipient list.",
    statementKind: "observation",
    text: "The authors report that the recipient list favored signatories’ relatives and associates.",
  },
  {
    id: "bonjol-neshp-member-exclusion",
    kind: "statement",
    label: "The recipient list excluded many clan members",
    description: "The reported exclusion outcome.",
    statementKind: "observation",
    text: "The authors report that the recipient list excluded many Melayu-clan members.",
  },
  {
    id: "bonjol-women-testimony-limit",
    kind: "statement",
    label: "Many women declined to discuss the land dispute",
    description:
      "An observation about both testimony and the conditions of speaking.",
    statementKind: "observation",
    text: "Researchers report that many women declined to discuss the contested land practices.",
  },
  {
    id: "bonjol-five-women-testimony",
    kind: "statement",
    label: "Five women described anger about the dispute",
    description:
      "Attributed anger from a small group, not a population estimate.",
    statementKind: "observation",
    text: "A group of five Melayu women described anger about the land dispute.",
  },
  {
    id: "bonjol-five-women-income-loss",
    kind: "statement",
    label: "Five women described lost income",
    description: "Attributed testimony from a small group.",
    statementKind: "observation",
    text: "A group of five Melayu women described lost income from the contested land practices.",
  },
  {
    id: "bonjol-five-women-weak-influence",
    kind: "statement",
    label: "Five women described weak influence over representatives",
    description: "Attributed testimony from a small group.",
    statementKind: "observation",
    text: "A group of five Melayu women described being unable to influence male kin who represented the clan publicly.",
  },
  {
    id: "bonjol-authors-causal-interpretation",
    kind: "statement",
    label: "The authors identify limited education as one possible cause",
    description:
      "An attributed education hypothesis rather than an observed effect.",
    statementKind: "causal-hypothesis",
    text: "Mutolib and colleagues attribute women’s weak influence partly to limited education.",
  },
  {
    id: "bonjol-authors-early-marriage-hypothesis",
    kind: "statement",
    label: "The authors identify early marriage as one possible cause",
    description: "An attributed causal hypothesis.",
    statementKind: "causal-hypothesis",
    text: "Mutolib and colleagues attribute women’s weak influence partly to early marriage.",
  },
  {
    id: "bonjol-authors-gender-norms-hypothesis",
    kind: "statement",
    label: "The authors identify gender norms as one possible cause",
    description: "An attributed causal hypothesis.",
    statementKind: "causal-hypothesis",
    text: "Mutolib and colleagues attribute women’s weak influence partly to gender norms.",
  },
  {
    id: "bonjol-authors-forum-hypothesis",
    kind: "statement",
    label: "The authors identify lack of a forum as one possible cause",
    description: "An attributed causal hypothesis.",
    statementKind: "causal-hypothesis",
    text: "Mutolib and colleagues attribute women’s weak influence partly to the lack of a forum for women.",
  },
  {
    id: "bonjol-authors-representation-dependence-hypothesis",
    kind: "statement",
    label: "The authors identify dependence on male representatives",
    description: "An attributed causal hypothesis.",
    statementKind: "causal-hypothesis",
    text: "Mutolib and colleagues attribute women’s weak influence partly to dependence on male customary representatives.",
  },
  {
    id: "bonjol-causal-identification-limit",
    kind: "statement",
    label: "The Bonjol study cannot isolate the proposed causes",
    description: "A causal-identification limit.",
    statementKind: "editorial-interpretation",
    text: "The Bonjol study’s small cross-sectional design cannot isolate the effects of the causes proposed by its authors.",
  },
  {
    id: "bonjol-no-minangkabau-generalization",
    kind: "statement",
    label: "The Bonjol findings are not society-wide",
    description: "The case study’s explicit transfer limit.",
    statementKind: "observation",
    text: "The authors explicitly caution that findings about Melayu-clan forest management in Bonjol should not be generalized to ulayat practice or women’s position across Minangkabau communities.",
  },
  {
    id: "nagari-law-changed-after-cases",
    kind: "statement",
    label: "The provincial nagari framework changed after both studies",
    description:
      "A temporal boundary against presenting the case rules as current law.",
    statementKind: "observation",
    text: "West Sumatra Regulation 7 of 2018 established a later provincial framework for nagari as customary-law community government.",
  },
].map((entity) => ({
  documentType: "entity" as const,
  entity: { ...entity, ...reviewed } as DomainEntity,
}));

const cases = [
  {
    id: "koto-tinggi-post-decentralization-governance",
    kind: "case",
    label: "Koto Tinggi nagari governance observed in October 2016",
    description:
      "A bounded October 2016 study of formal institutions and development-planning practice in Koto Tinggi.",
    locationIds: ["nagari-koto-tinggi-agam", "west-sumatra"],
    startDate: {
      year: 2016,
      month: 10,
      certainty: "exact",
    },
    endDate: { year: 2016, month: 10, certainty: "exact" },
    scope:
      "Nagari government, representative and customary councils, and development planning observed in Koto Tinggi during October 2016; decentralization from 2001 is background, and the cited formal design dates to Agam Regulation 12 of 2007.",
    conditionStatementIds: ["koto-tinggi-minangkabau-adat-context"],
    selectionRationale:
      "Selected to separate maternal-line social organization from the public offices, representative bodies, customary council, and rules-in-use of one named nagari.",
    episodeIds: ["koto-tinggi-governance-october-2016"],
  },
  {
    id: "koto-tinggi-governance-october-2016",
    kind: "case-episode",
    caseId: "koto-tinggi-post-decentralization-governance",
    label: "Koto Tinggi governance observed in October 2016",
    description:
      "The post-decentralization institutional arrangement observed in October 2016.",
    locationIds: ["nagari-koto-tinggi-agam", "west-sumatra"],
    startDate: {
      year: 2016,
      month: 10,
      certainty: "exact",
    },
    endDate: { year: 2016, month: 10, certainty: "exact" },
    scope:
      "The institutions and development-planning interactions described for Koto Tinggi, not all Agam or Minangkabau nagari.",
    conditionStatementIds: ["koto-tinggi-minangkabau-adat-context"],
    formalRuleStatementIds: [
      "koto-tinggi-three-institutions",
      "koto-tinggi-representative-council",
      "koto-tinggi-customary-council",
      "koto-tinggi-formal-participation-rules",
      "koto-tinggi-formal-decision-rule",
      "koto-tinggi-formal-speaking-rule",
      "koto-tinggi-formal-consensus-rule",
      "koto-tinggi-formal-vote-fallback",
    ],
    ruleInUseStatementIds: [
      "koto-tinggi-budget-rules-in-use",
      "koto-tinggi-budget-postponement",
      "koto-tinggi-budget-consensus",
    ],
    interactionStatementIds: ["koto-tinggi-customary-council-contestation"],
    outcomeStatementIds: [
      "koto-tinggi-administrative-capacity-limit",
      "koto-tinggi-unspent-funds",
      "koto-tinggi-accounting-difficulty",
      "koto-tinggi-regulatory-preparation-limit",
    ],
  },
  {
    id: "bonjol-melayu-ulayat-governance",
    kind: "case",
    label: "Melayu-clan ulayat governance in Nagari Bonjol",
    description:
      "A bounded study of communal-forest access, management, and oil-palm plot distribution in Nagari Bonjol.",
    locationIds: ["nagari-bonjol-dharmasraya", "west-sumatra"],
    startDate: {
      year: 2000,
      certainty: "approximate",
      note: "The authors date the new nagari and management transition to the period beginning around 2000, with the concession ending in 2002.",
    },
    endDate: { year: 2016, month: 4, certainty: "exact" },
    scope:
      "Melayu-clan ulayat forest governance in Nagari Bonjol from the administrative and concession transition around 2000–2002 through fieldwork ending in April 2016.",
    conditionStatementIds: [
      "bonjol-new-nagari-forest-transition",
      "bonjol-concession-end-transition",
    ],
    selectionRationale:
      "Selected because the study distinguishes collective and inherited claims from practical management, negotiation, voice, and receipt of benefits in one named clan and nagari.",
    episodeIds: ["bonjol-ulayat-governance-2000-2016"],
  },
  {
    id: "bonjol-ulayat-governance-2000-2016",
    kind: "case-episode",
    caseId: "bonjol-melayu-ulayat-governance",
    label: "Bonjol ulayat governance, 2000–2016",
    description:
      "The Melayu-clan forest-management period examined by the 2016 field study.",
    locationIds: ["nagari-bonjol-dharmasraya", "west-sumatra"],
    startDate: {
      year: 2000,
      certainty: "approximate",
      note: "The authors date the new nagari and management transition to the period beginning around 2000, with the concession ending in 2002.",
    },
    endDate: { year: 2016, month: 4, certainty: "exact" },
    scope:
      "Observed Melayu-clan rules and practices concerning the claimed ulayat forest and smallholder plots; excludes other Bonjol clans and other Minangkabau communities.",
    conditionStatementIds: [
      "bonjol-new-nagari-forest-transition",
      "bonjol-concession-end-transition",
    ],
    formalRuleStatementIds: [
      "bonjol-ulayat-formal-distinction",
      "bonjol-harta-pusaka-female-line",
      "bonjol-neshp-formal-promise",
    ],
    ruleInUseStatementIds: [
      "bonjol-ulayat-delegated-management",
      "bonjol-harta-pusaka-transition",
      "bonjol-inheritance-did-not-confer-office-authority",
      "bonjol-ulayat-sales-rules-in-use",
      "bonjol-ulayat-sales-contrary-to-custom",
    ],
    interactionStatementIds: ["bonjol-neshp-distribution-practice"],
    outcomeStatementIds: [
      "bonjol-neshp-exclusion-outcome",
      "bonjol-neshp-member-exclusion",
    ],
  },
].map((entity) => ({
  documentType: "entity" as const,
  entity: { ...entity, ...reviewed } as DomainEntity,
}));

export const minangkabauEvidenceDocuments = [
  ...entities,
  ...cases,
] satisfies AuthoringDocument[];
