import type { AuthoringDocument } from "../../../src/lib/domain";

const reviewed = { publicationStatus: "reviewed" as const };

const statement = (
  id: string,
  label: string,
  text: string,
  statementKind: "observation" | "classification" | "definition" | "editorial-interpretation" = "observation",
): AuthoringDocument => ({
  documentType: "entity",
  entity: { id, kind: "statement", label, description: text, statementKind, text, ...reviewed },
});

export const nomadicConfederatedOrganizationEvidenceDocuments = [
  {
    documentType: "entity",
    entity: {
      id: "southwestern-syrian-desert-wadi-sirhan",
      kind: "place",
      label: "Southwestern Syrian Desert and Wadi Sirhan",
      description: "The steppe and desert corridor connecting southern Syria and Transjordan with Wadi Sirhan and al-Jawf in northern Arabia.",
      placeType: "region",
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "jinst-sum",
      kind: "place",
      label: "Jinst sum",
      description: "A desert-steppe district in Bayankhongor Province, Mongolia.",
      placeType: "institutional-jurisdiction",
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "cicek-tribal-agency-work",
      kind: "work",
      label: "Tribal agency and the translocalization of the Middle East",
      description: "M. Talha Çiçek’s archival study of mobile Arab Bedouin agency in the post-Ottoman border order.",
      title: "Tribal agency and the translocalization of the Middle East: the European mandates, the Arab Bedouins and the making of the post-Ottoman order",
      workType: "article",
      originalPublicationYear: 2025,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "cicek-tribal-agency-source",
      kind: "source",
      label: "Tribal agency and the post-Ottoman order (2025)",
      description: "The publisher-hosted Historical Research article based on French and British archives, Arabic newspapers, and other primary records.",
      title: "Tribal agency and the translocalization of the Middle East: the European mandates, the Arab Bedouins and the making of the post-Ottoman order",
      sourceType: "article",
      workId: "cicek-tribal-agency-work",
      contributorDisplay: ["M. Talha Çiçek"],
      publicationYear: 2025,
      publisher: "Historical Research, Oxford University Press",
      identifiers: { doi: "10.1093/hisres/htaf012" },
      resourceLinks: [{ purpose: "publisher", url: "https://academic.oup.com/histres/article/98/282/599/8155496", label: "Read the journal article" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "stocker-borders-in-motion-work",
      kind: "work",
      label: "Borders in Motion",
      description: "Laura Stocker’s Ruwalla and Shammar Jarba study of Bedouin territoriality after Ottoman rule.",
      title: "Borders in Motion: Bedouin Tribes and Territoriality in the Post-Ottoman Middle East, 1918–1936",
      workType: "report",
      originalPublicationYear: 2026,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "stocker-borders-in-motion-source",
      kind: "source",
      label: "Borders in Motion (2026)",
      description: "The University of Neuchâtel repository record for Stocker’s multilingual archival doctoral thesis.",
      title: "Borders in Motion: Bedouin Tribes and Territoriality in the Post-Ottoman Middle East, 1918–1936",
      sourceType: "report",
      workId: "stocker-borders-in-motion-work",
      contributorDisplay: ["Laura Stocker"],
      publicationYear: 2026,
      publisher: "Université de Neuchâtel",
      identifiers: { doi: "10.35662/unine-thesis-3254" },
      resourceLinks: [{ purpose: "archive", url: "https://libra.unine.ch/entities/publication/890b2aac-f81c-4627-ba6a-bc437fcfa2a9", label: "View the university repository record" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "fernandez-gimenez-pastoral-tenure-work",
      kind: "work",
      label: "Spatial and Social Boundaries and the Paradox of Pastoral Land Tenure",
      description: "María E. Fernández-Giménez’s field-based study of pastoral land use in Jinst and Bayan-Ovoo after Mongolia’s collectives ended.",
      title: "Spatial and Social Boundaries and the Paradox of Pastoral Land Tenure: A Case Study From Postsocialist Mongolia",
      workType: "article",
      originalPublicationYear: 2002,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "fernandez-gimenez-pastoral-tenure-source",
      kind: "source",
      label: "Pastoral land tenure in postsocialist Mongolia (2002)",
      description: "The Human Ecology article, consulted in an author-hosted full-text manifestation.",
      title: "Spatial and Social Boundaries and the Paradox of Pastoral Land Tenure: A Case Study From Postsocialist Mongolia",
      sourceType: "article",
      workId: "fernandez-gimenez-pastoral-tenure-work",
      contributorDisplay: ["María E. Fernández-Giménez"],
      publicationYear: 2002,
      publisher: "Human Ecology",
      identifiers: { doi: "10.1023/A:1014562911434" },
      resourceLinks: [{ purpose: "authorized-reading", url: "https://cdn.greensoft.mn/uploads/users/1277/files/Greenmongolia/%D0%93%D0%B0%D0%B4%D0%B0%D0%B0%D0%B4/Mongolian_steppe_studies/Article_Gadaad_PDF/FernandezGimenez_spatialsocialboundarieslandtenureMongolia_HE_2002.pdf", label: "Read the full article" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "allington-context-matters-work",
      kind: "work",
      label: "Context matters in Mongolian pastoral governance",
      description: "A multi-ecozone household study of rules, social ties, tenure, mobility, and forage reservation in Mongolia.",
      title: "Context matters: Rethinking resource governance theories for Mongolian pastoral systems",
      workType: "article",
      originalPublicationYear: 2024,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "allington-context-matters-source",
      kind: "source",
      label: "Context matters in Mongolian pastoral systems (2024)",
      description: "The open-access Land Use Policy article based on a survey of 760 households across four Mongolian ecozones.",
      title: "Context matters: Rethinking resource governance theories for Mongolian pastoral systems",
      sourceType: "article",
      workId: "allington-context-matters-work",
      contributorDisplay: ["Ginger R. H. Allington", "María E. Fernández-Giménez", "Batkhishig Baival", "Batbuyan Batjav et al."],
      publicationYear: 2024,
      publisher: "Land Use Policy",
      identifiers: { doi: "10.1016/j.landusepol.2024.107170" },
      resourceLinks: [{ purpose: "publisher", url: "https://www.sciencedirect.com/science/article/pii/S0264837724001236", label: "Read the open-access article" }],
      ...reviewed,
    },
  },
  statement("ruwalla-name-boundary", "Ruwalla and external labels remain distinct", "Stocker names the historical collective Ruwalla and describes it as a camel-breeding Bedouin tribe; those English scholarly classifications do not by themselves establish how every member self-identified or define a universal political type.", "classification"),
  statement("ruwalla-anaza-affiliation", "Ruwalla belonged to wider ʿAnaza networks", "Çiçek places the Ruwalla among mobile groups linked through the ʿAnaza genealogy, which actors could mobilize for political alliance; the affiliation did not erase differences among Ruwalla sections or create a single centralized ʿAnaza state."),
  statement("ruwalla-mobility-corridor", "Ruwalla mobility crossed emerging borders", "During the post-Ottoman settlement, Ruwalla seasonal movement connected the southwestern Syrian Desert with pasture and water around Wadi Sirhan and al-Jawf across territories claimed by Syria, Transjordan, Iraq, and Ibn Saud."),
  statement("ruwalla-mashyakha", "The mashyakha institutionalized representation", "Stocker identifies the Al Shaʿlan family as political representatives of Ruwalla collectives and describes the mashyakha as the institutionalized position of paramount shaykh.", "definition"),
  statement("ruwalla-shaykh-consent-limit", "A shaykh could not simply command collective assent", "Çiçek argues that a Bedouin shaykh risked internal crisis if he disregarded fellow tribespeople’s interests and therefore had to persuade them when government demands conflicted with those interests."),
  statement("ruwalla-dira-not-sovereignty", "Dīra did not mean exclusive state territory", "Stocker interprets Ruwalla political action as seeking influence, mobility, and access across the collective’s historical resource area, or dīra, rather than exclusive territorial sovereignty.", "classification"),
  statement("ruwalla-border-bargaining", "Ruwalla leaders bargained over border incorporation", "In the 1920s Nuri al-Shaʿlan used control of and access to al-Jawf to negotiate with British and French authorities, Amir Abdullah, King Faisal, and Ibn Saud over winter pasture, mobility, and regional influence."),
  statement("ruwalla-border-concessions", "States conceded cross-border mobility", "Çiçek finds that mandate and regional governments could not reduce mobile tribal affiliation to ordinary individual nationality and instead developed exemptions and interstate mechanisms that preserved cross-border migration."),
  statement("ruwalla-archive-mediation", "Ruwalla evidence is archivally mediated", "The principal historical studies reconstruct Ruwalla action by cross-reading French and British colonial archives with Arabic newspapers and multilingual private, travel, and reference sources; these records unevenly preserve non-elite and women’s voices."),
  statement("ruwalla-case-transfer-limit", "The Ruwalla case is not a tribal template", "Ruwalla organization between 1918 and 1936 joined mobile pastoral production, layered kin affiliation, shaykhly representation, and bargaining with rival states under conditions specific to the post-Ottoman border settlement; it is not a stage or template for Arabian, Bedouin, tribal, or confederated government.", "editorial-interpretation"),
  statement("jinst-fieldwork-provenance", "Jinst evidence includes herder interviews", "Fernández-Giménez lived with herding camps in Jinst and Bayan-Ovoo during ten months in 1994–1995, conducted interviews with herders and officials, and surveyed 102 households across both districts in 1995."),
  statement("jinst-administrative-boundary", "Sum and bag were state administrative boundaries", "In the 1990s pasture remained state-owned for common use by herders of a defined sum and bag, while actual resource claims and seasonal movement crossed or nested within those administrative units.", "classification"),
  statement("jinst-postcollective-change", "Collective dissolution shifted risks to households", "After the collectives were dismantled and livestock privatized in 1992, herder households became responsible for movement, labor, transport, veterinary inputs, marketing, and production risk while pasture remained state-owned."),
  statement("jinst-seasonal-norms", "Herders described reserve and emergency-access norms", "Herders described setting aside winter and spring pasture and discouraging out-of-season grazing, while allowing outsiders access during drought or severe winter with an expectation of reciprocal access if conditions reversed."),
  statement("jinst-khot-ail", "Khot ail coordinated household herding labor", "The study describes khot ail as small, seasonally changeable camps in which households, often but not always kin, pooled animals into species herds and shared work such as hay cutting and moves.", "definition"),
  statement("jinst-campsite-rights", "Campsite rights combined custom, occupancy, and structures", "Jinst campsite claims could rest on inheritance, customary use, collective-period use, current occupancy, and ownership of a shelter; the senior herder commonly held the camp’s recognized claim."),
  statement("jinst-neg-nutgiinkhan-boundary", "Neg nutgiinkhan was locally used but disputed as a category", "Fernández-Giménez reports that some herders identified as neg nutgiinkhan, people of one place, while noting that scholars disputed whether the grouping was a local institution or an analytical construction.", "classification"),
  statement("jinst-pasture-overlap", "Pasture claims were overlapping and distance-sensitive", "Winter and spring pasture use commonly attached to a khot ail or a loose neighborhood of camps, with influence strongest near a campsite, diminishing with distance, and overlapping neighboring use areas."),
  statement("jinst-resource-rights-differed", "Different resources carried different rights", "In the study sites, privately held shelters, inherited or occupied campsites, group-managed wells, leased pump wells, open summer pasture, and overlapping winter pasture did not form one uniform property regime."),
  statement("jinst-inequality", "Secondary access was less secure", "Poorer and newer herders often obtained temporary pasture access through kin or acquaintances and labor exchange, while wealthier or established households were better able to assert inherited or birthright claims."),
  statement("jinst-mobility-coordination", "Loss of coordination weakened seasonal mobility", "After collective regulation and transport support ended, material constraints and uncertainty about whether others would move contributed to reduced mobility, prolonged use near settlements, and out-of-season grazing."),
  statement("jinst-tenure-proposal-limit", "Rigid tenure was an argued proposal, not an observed solution", "Fernández-Giménez recommends testing participatory coordination of seasonal movement and cautions against rigid pasture tenure because fixed boundaries could restrict emergency access and consolidate unequal claims.", "editorial-interpretation"),
  statement("mongolia-later-study-transfer", "Later national evidence does not extend the Jinst episode", "A 2024 survey of 760 households across four Mongolian ecozones found that rules, social ties, and environmental conditions related differently to forage reservation and mobility; this later cross-sectional result cannot establish what happened in Jinst after 1999."),
  statement("jinst-case-transfer-limit", "Jinst is not a nomadic-government template", "Jinst’s 1990s pasture practices combined fluid household camps, reciprocal access, unequal claims, state land ownership, and the loss of collective coordination; they do not define a universal Mongolian, pastoral, nomadic, customary, or stateless government.", "editorial-interpretation"),
  statement("ruwalla-jinst-non-equivalence", "The two cases support bounded contrast, not a common type", "Ruwalla cross-border shaykhly representation during a post-imperial border settlement and Jinst household pasture coordination after collective dissolution involved different actors, scales, institutions, evidence traditions, and state relationships; shared mobility vocabulary does not make them instances of one evolutionary or political type.", "editorial-interpretation"),
  {
    documentType: "entity",
    entity: {
      id: "ruwalla-borderland-organization",
      kind: "case",
      label: "Ruwalla organization across post-Ottoman borders",
      description: "Ruwalla mobile pastoral organization and political bargaining across the southwestern Syrian Desert and northern Arabian corridor, 1918–1936.",
      locationIds: ["southwestern-syrian-desert-wadi-sirhan"],
      startDate: { year: 1918, certainty: "exact" },
      endDate: { year: 1936, certainty: "approximate", note: "The endpoint follows Stocker’s boundary for consolidation of the post-Ottoman national order." },
      scope: "Ruwalla mobility, resource access, Al Shaʿlan representation, and relations with mandate and emerging national authorities from the Ottoman collapse through the mid-1930s; excludes a timeless account of Ruwalla life or a general model of Bedouin organization.",
      selectionRationale: "The episode shows how mobile access, layered affiliation, representative leadership, and state border-making interacted without treating tribe or confederacy as a universal system.",
      conditionStatementIds: ["ruwalla-name-boundary", "ruwalla-anaza-affiliation", "ruwalla-mobility-corridor", "ruwalla-archive-mediation", "ruwalla-case-transfer-limit"],
      episodeIds: ["ruwalla-borderland-1918-1936"],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "ruwalla-borderland-1918-1936",
      kind: "case-episode",
      label: "Ruwalla borderland bargaining, 1918–1936",
      description: "The bounded period in which Ruwalla leaders and mobile groups negotiated access and affiliation across new borders.",
      caseId: "ruwalla-borderland-organization",
      locationIds: ["southwestern-syrian-desert-wadi-sirhan"],
      startDate: { year: 1918, certainty: "exact" },
      endDate: { year: 1936, certainty: "approximate", note: "Approximate consolidation boundary used by Stocker." },
      scope: "The post-Ottoman remaking of Ruwalla mobility, dīra access, shaykhly representation, and state relations; later ethnography is not evidence for unchanged continuity.",
      conditionStatementIds: ["ruwalla-mobility-corridor", "ruwalla-archive-mediation"],
      formalRuleStatementIds: ["ruwalla-mashyakha"],
      ruleInUseStatementIds: ["ruwalla-shaykh-consent-limit", "ruwalla-dira-not-sovereignty"],
      interactionStatementIds: ["ruwalla-border-bargaining", "ruwalla-border-concessions"],
      outcomeStatementIds: [],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "jinst-postcollective-pastoral-governance",
      kind: "case",
      label: "Jinst post-collective pastoral governance",
      description: "Herder households’ seasonal mobility and overlapping pasture institutions in Jinst sum after collective dissolution, 1990–1997.",
      locationIds: ["jinst-sum"],
      startDate: { year: 1990, certainty: "exact" },
      endDate: { year: 1997, certainty: "exact", note: "The endpoint follows the original dissertation research boundary, not the end of Jinst pastoral life." },
      scope: "Pasture, water, campsite, camp-group, and administrative relations documented in Jinst and explicitly separated from pooled findings for Bayan-Ovoo and from later pasture-user organizations.",
      selectionRationale: "The case exposes resource-specific and overlapping authority after a state collective ended, providing a materially different comparison with Ruwalla cross-border organization.",
      conditionStatementIds: ["jinst-fieldwork-provenance", "jinst-administrative-boundary", "jinst-postcollective-change", "jinst-case-transfer-limit"],
      episodeIds: ["jinst-transition-1990-1997"],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "jinst-transition-1990-1997",
      kind: "case-episode",
      label: "Jinst transition after collective dissolution, 1990–1997",
      description: "The evidence period spanning democratic transition, livestock privatization, and 1994–1995 fieldwork through the original dissertation boundary.",
      caseId: "jinst-postcollective-pastoral-governance",
      locationIds: ["jinst-sum"],
      startDate: { year: 1990, certainty: "exact" },
      endDate: { year: 1997, certainty: "exact" },
      scope: "Jinst evidence where the study identifies it, with pooled two-district findings labeled and no projection into later pasture-user-group institutions.",
      conditionStatementIds: ["jinst-fieldwork-provenance", "jinst-postcollective-change"],
      formalRuleStatementIds: ["jinst-administrative-boundary"],
      ruleInUseStatementIds: ["jinst-seasonal-norms", "jinst-khot-ail", "jinst-campsite-rights", "jinst-neg-nutgiinkhan-boundary", "jinst-pasture-overlap", "jinst-resource-rights-differed"],
      interactionStatementIds: ["jinst-inequality", "jinst-mobility-coordination"],
      outcomeStatementIds: [],
      ...reviewed,
    },
  },
] satisfies AuthoringDocument[];
