import type { AuthoringDocument } from "../../../src/lib/domain";

const reviewed = { publicationStatus: "reviewed" as const };

type SourceType = "web-page" | "article" | "edition";
type WorkType = "book" | "article" | "other";

const source = (
  id: string,
  title: string,
  contributors: string[],
  workYear: number | undefined,
  publicationYear: number | undefined,
  publisher: string,
  url: string,
  workType: WorkType,
  sourceType: SourceType,
  doi?: string,
  isbn13?: string,
  linkPurpose?: "publisher" | "authorized-reading",
  workTitle?: string,
): AuthoringDocument[] => [
  {
    documentType: "entity",
    entity: {
      id: `${id}-work`,
      kind: "work",
      label: workTitle ?? title,
      description: `The non-fiction work consulted for the Oligarchy guide: ${workTitle ?? title}.`,
      title: workTitle ?? title,
      workType,
      ...(workYear === undefined ? {} : { originalPublicationYear: workYear }),
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: `${id}-source`,
      kind: "source",
      label: title,
      description: `The consulted ${publisher} manifestation of ${title}.`,
      title,
      sourceType,
      workId: `${id}-work`,
      contributorDisplay: contributors,
      ...(publicationYear === undefined ? {} : { publicationYear }),
      publisher,
      ...(doi
        ? { identifiers: { doi } }
        : isbn13
          ? { identifiers: { isbn13 } }
          : {}),
      resourceLinks: [
        {
          purpose:
            linkPurpose ??
            (sourceType === "edition" ? "authorized-reading" : "publisher"),
          url,
          label: "Open the consulted source",
        },
      ],
      ...reviewed,
    },
  },
];

const statement = (
  id: string,
  label: string,
  text: string,
  statementKind:
    | "definition"
    | "observation"
    | "causal-hypothesis"
    | "classification"
    | "editorial-interpretation" = "observation",
): AuthoringDocument => ({
  documentType: "entity",
  entity: {
    id,
    kind: "statement",
    label,
    description: label,
    statementKind,
    text,
    ...reviewed,
  },
});

export const oligarchyEvidenceDocuments = [
  ...source(
    "aristotle-politics-rackham",
    "Aristotle in 23 Volumes, Volume 21: Politics",
    ["Aristotle", "H. Rackham (translator)"],
    undefined,
    1944,
    "Harvard University Press and William Heinemann",
    "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0058%3Abook%3D3",
    "book",
    "edition",
    undefined,
    undefined,
    "authorized-reading",
    "Politics",
  ),
  ...source(
    "aristotle-athenian-constitution-rackham",
    "Aristotle in 23 Volumes, Volume 20: Athenian Constitution",
    ["Aristotle", "H. Rackham (translator)"],
    undefined,
    1952,
    "Harvard University Press and William Heinemann",
    "https://www.perseus.tufts.edu/hopper/text?doc=Aristot.%20Ath.%20Pol.%2029",
    "book",
    "edition",
    undefined,
    undefined,
    "authorized-reading",
    "Athenian Constitution",
  ),
  ...source(
    "thucydides-peloponnesian-war-crawley",
    "The History of the Peloponnesian War, translated by Richard Crawley",
    ["Thucydides", "Richard Crawley (translator)"],
    undefined,
    1910,
    "J. M. Dent and E. P. Dutton",
    "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0200%3Abook%3D8",
    "book",
    "edition",
    undefined,
    undefined,
    "authorized-reading",
    "History of the Peloponnesian War",
  ),
  ...source(
    "simonton-classical-greek-oligarchy",
    "Classical Greek Oligarchy: A Political History",
    ["Matthew Simonton"],
    2017,
    2017,
    "Princeton University Press",
    "https://academic.oup.com/princeton-scholarship-online/book/21054",
    "book",
    "web-page",
    "10.23943/princeton/9780691174976.001.0001",
    "9780691174976",
  ),
  ...source(
    "winters-oligarchy-encyclopedia",
    "Oligarchy",
    ["Jeffrey A. Winters"],
    2014,
    2014,
    "John Wiley & Sons",
    "https://onlinelibrary.wiley.com/doi/abs/10.1002/9781118474396.wbept0726",
    "article",
    "article",
    "10.1002/9781118474396.wbept0726",
  ),
  ...source(
    "page-winters-us-oligarchy",
    "Oligarchy in the United States?",
    ["Jeffrey A. Winters", "Benjamin I. Page"],
    2009,
    2009,
    "Cambridge University Press",
    "https://labor.history.ucsb.edu/sites/secure.lsit.ucsb.edu.hist.d7_labor/files/sitefiles/Page-Winters_Oligarchy%20in%20US_PoP_2009.pdf",
    "article",
    "article",
    "10.1017/S1537592709991770",
    undefined,
    "authorized-reading",
  ),
  ...source(
    "winters-indonesia-oligarchy-democracy",
    "Oligarchy and Democracy in Indonesia",
    ["Jeffrey A. Winters"],
    2013,
    2013,
    "Cornell University Press",
    "https://www.jstor.org/stable/10.5728/indonesia.96.0099",
    "article",
    "article",
    "10.5728/indonesia.96.0099",
  ),
  ...source(
    "hadiz-robison-reorganization-power",
    "The Political Economy of Oligarchy and the Reorganization of Power in Indonesia",
    ["Vedi R. Hadiz", "Richard Robison"],
    2013,
    2013,
    "Cornell University Press",
    "https://www.jstor.org/stable/10.5728/indonesia.96.0033",
    "article",
    "article",
    "10.5728/indonesia.96.0033",
  ),
  ...source(
    "ford-pepinsky-beyond-oligarchy-introduction",
    "Beyond Oligarchy? Critical Exchanges on Political Power and Material Inequality in Indonesia",
    ["Michele Ford", "Thomas B. Pepinsky"],
    2013,
    2013,
    "Cornell University Press",
    "https://www.jstor.org/stable/10.5728/indonesia.96.0001",
    "article",
    "article",
    "10.5728/indonesia.96.0001",
  ),
  ...source(
    "gilens-page-testing-theories",
    "Testing Theories of American Politics: Elites, Interest Groups, and Average Citizens",
    ["Martin Gilens", "Benjamin I. Page"],
    2014,
    2014,
    "Cambridge University Press",
    "https://doi.org/10.1017/S1537592714001595",
    "article",
    "article",
    "10.1017/S1537592714001595",
  ),
  ...source(
    "gilens-inequality-responsiveness",
    "Inequality and Democratic Responsiveness",
    ["Martin Gilens"],
    2005,
    2005,
    "Oxford University Press",
    "https://academic.oup.com/poq/article/69/5/778/1920084",
    "article",
    "article",
    "10.1093/poq/nfi058",
  ),
  ...source(
    "bashir-testing-inferences",
    "Testing Inferences about American Politics: A Review of the ‘Oligarchy’ Result",
    ["Omar S. Bashir"],
    2015,
    2015,
    "SAGE Publications",
    "https://journals.sagepub.com/doi/10.1177/2053168015608896",
    "article",
    "article",
    "10.1177/2053168015608896",
  ),
  ...source(
    "gilens-simulating-representation",
    "Simulating Representation: The Devil’s in the Detail",
    ["Martin Gilens"],
    2016,
    2016,
    "SAGE Publications",
    "https://journals.sagepub.com/doi/10.1177/2053168016654720",
    "article",
    "article",
    "10.1177/2053168016654720",
  ),

  {
    documentType: "entity",
    entity: {
      id: "oligarchy",
      kind: "concept",
      label: "Oligarchy",
      description:
        "A contested concept used for rule by a few, rule by the wealthy, durable minority power, and allegations that a small group dominates political decisions.",
      schemeIds: ["political-economic-ideas"],
      scopeNote:
        "Neither inequality, wealth, elite office, a small legislature, nondemocracy, nor an unpopular governing group alone establishes oligarchy; each use needs a definition, mechanism, scope, and evidence.",
      externalRefs: [
        {
          system: "wikipedia",
          url: "https://en.wikipedia.org/wiki/Oligarchy",
          purpose: "orientation",
          language: "en",
          checkedAt: "2026-09-06",
        },
        {
          system: "wikidata",
          id: "Q79751",
          url: "https://www.wikidata.org/wiki/Q79751",
          purpose: "identity",
          match: "exact",
          checkedAt: "2026-09-06",
        },
      ],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "athens",
      kind: "place",
      label: "Athens",
      description:
        "The city and polity used to bound the 411 BCE constitutional episode.",
      placeType: "city",
      externalRefs: [
        {
          system: "wikipedia",
          url: "https://en.wikipedia.org/wiki/Athens",
          purpose: "orientation",
          language: "en",
          checkedAt: "2026-09-06",
        },
        {
          system: "wikidata",
          id: "Q1524",
          url: "https://www.wikidata.org/wiki/Q1524",
          purpose: "identity",
          match: "exact",
          checkedAt: "2026-09-06",
        },
      ],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "indonesia",
      kind: "place",
      label: "Indonesia",
      description:
        "The national jurisdiction used to bound the 1998–2013 scholarly debate.",
      placeType: "country",
      externalRefs: [
        {
          system: "wikipedia",
          url: "https://en.wikipedia.org/wiki/Indonesia",
          purpose: "orientation",
          language: "en",
          checkedAt: "2026-09-06",
        },
        {
          system: "wikidata",
          id: "Q252",
          url: "https://www.wikidata.org/wiki/Q252",
          purpose: "identity",
          match: "exact",
          checkedAt: "2026-09-06",
        },
      ],
      ...reviewed,
    },
  },

  statement(
    "oligarchy-aristotle-few-common-interest",
    "Aristotle contrasts number and common interest",
    "In Rackham's translation of Aristotle's constitutional scheme, government by a few for the common interest is aristocracy, while its deviation for the rulers' advantage is oligarchy.",
    "definition",
  ),
  statement(
    "oligarchy-aristotle-wealth-distinction",
    "Aristotle makes wealth more decisive than number",
    "Aristotle argues that poverty and wealth distinguish democracy from oligarchy more exactly than the bare fact that many or few govern.",
    "definition",
  ),
  statement(
    "oligarchy-simonton-historical-form",
    "Simonton treats classical oligarchy as a political form",
    "Simonton describes classical Greek oligarchy as minority rule by wealthy citizens maintained through institutions that coordinated rulers and divided opponents.",
    "definition",
  ),
  statement(
    "oligarchy-winters-wealth-defense",
    "Winters defines oligarchs through material power",
    "Winters defines oligarchs as actors who command concentrated material resources and directs oligarchy theory toward their wealth-defense objectives.",
    "definition",
  ),
  statement(
    "oligarchy-page-winters-democracy-coexistence",
    "Page and Winters allow democracy and oligarchy to coexist",
    "Page and Winters argue that democratic institutions can coexist with oligarchic power because wealthy actors need not hold office or control every political question.",
    "definition",
  ),
  statement(
    "oligarchy-elite-theory-distinction",
    "Elite theory asks a broader organizational question",
    "Page and Winters distinguish their material account of oligarchy from elite theories concerned more broadly with leadership, organization, expertise, or control by minorities.",
    "definition",
  ),
  statement(
    "oligarchy-polemic-boundary",
    "An accusation is not a demonstrated classification",
    "Calling opponents an oligarchy identifies a political allegation, not evidence that a named definition, mechanism, and bounded outcome have been established.",
    "editorial-interpretation",
  ),
  statement(
    "oligarchy-inequality-boundary",
    "Wealth inequality does not by itself demonstrate political conversion",
    "A distribution of wealth can identify unequal resources without establishing who used them, through which mechanism, to affect which political outcome.",
    "editorial-interpretation",
  ),
  statement(
    "oligarchy-officeholding-boundary",
    "Officeholding is one possible mechanism",
    "Formal office, agenda control, ownership, coercion, organization, and informal access are different mechanisms and should not be inferred from one another.",
    "editorial-interpretation",
  ),
  statement(
    "oligarchy-regime-boundary",
    "A bounded finding is not a country verdict",
    "Evidence about one institution, policy domain, period, or model cannot by itself classify an entire political order as oligarchic.",
    "editorial-interpretation",
  ),

  statement(
    "athens-411-war-crisis",
    "War and the Sicilian disaster conditioned the 411 change",
    "The Athenian Constitution places the constitutional change after the Sicilian disaster and amid expectations of Persian assistance in the war.",
    "observation",
  ),
  statement(
    "athens-411-five-thousand-proposal",
    "The proposal reserved government to at least five thousand",
    "The proposed constitution entrusted government to at least five thousand Athenians judged most able to serve with person and property.",
    "observation",
  ),
  statement(
    "athens-411-four-hundred-actual-rule",
    "The Four Hundred actually occupied the council house",
    "The Athenian Constitution reports that the Five Thousand were initially only nominally selected while the Four Hundred occupied the council house and administered government.",
    "observation",
  ),
  statement(
    "athens-411-coercion",
    "Thucydides reports intimidation and selective violence",
    "Thucydides reports that conspirators used assassinations and fear while the identities and numbers behind the movement remained uncertain to other citizens.",
    "observation",
  ),
  statement(
    "athens-411-four-hundred-duration",
    "The Four Hundred lasted about four months",
    "The Athenian Constitution dates the rule of the Four Hundred to approximately four months in 411 BCE.",
    "observation",
  ),
  statement(
    "athens-411-five-thousand-successor",
    "The Five Thousand followed the Four Hundred",
    "Thucydides reports that the Athenians deposed the Four Hundred and transferred affairs to the Five Thousand, defined as those able to furnish their own arms.",
    "observation",
  ),
  statement(
    "athens-411-source-boundary",
    "The ancient accounts require source criticism",
    "The surviving narrative accounts describe institutions and actions in 411 BCE but do not supply a neutral census of participation or make later oligarchy theories interchangeable with ancient oligarchia.",
    "editorial-interpretation",
  ),

  statement(
    "indonesia-winters-material-power",
    "Winters centers concentrated material power in Indonesia",
    "Winters argues that highly concentrated material resources gave wealthy actors unusually durable and versatile political power in post-1998 Indonesia.",
    "causal-hypothesis",
  ),
  statement(
    "indonesia-winters-wealth-defense",
    "Winters centers wealth defense",
    "Winters interprets wealth defense as a central shared objective of Indonesian oligarchs across the transition from the New Order to electoral democracy.",
    "causal-hypothesis",
  ),
  statement(
    "indonesia-democracy-coexistence",
    "The 1998 transition did not end the oligarchy debate",
    "The Indonesia debate examines how electoral democracy after 1998 could coexist with continuing concentrations of material and organizational power.",
    "observation",
  ),
  statement(
    "indonesia-hadiz-robison-rival",
    "Hadiz and Robison emphasize reorganized power relations",
    "Hadiz and Robison explain post-New Order politics through the reorganization of entrenched interests and networks rather than a simple persistence of unchanged individual oligarchs.",
    "causal-hypothesis",
  ),
  statement(
    "indonesia-beyond-oligarchy-critique",
    "Ford and Pepinsky identify explanatory limits",
    "Ford and Pepinsky argue that an oligarchy framework can understate institutions, non-material resources, actors outside wealthy elites, and variation across Indonesian political contests.",
    "causal-hypothesis",
  ),
  statement(
    "indonesia-debate-reply",
    "The exchange does not reduce to inequality",
    "Contributors to the Indonesia exchange dispute which resources, organizations, and institutions explain outcomes rather than treating wealth concentration alone as a complete result.",
    "editorial-interpretation",
  ),
  statement(
    "indonesia-case-boundary",
    "Indonesia remains a bounded scholarly dispute",
    "The 1998–2013 case records competing explanations of post-New Order power and does not assign Indonesia a timeless or regime-wide identity.",
    "editorial-interpretation",
  ),

  statement(
    "us-gilens-page-dataset",
    "Gilens and Page analyzed 1,779 proposed policy changes",
    "Gilens and Page analyzed 1,779 United States policy proposals from 1981 through 2002 for which preference and outcome data were available.",
    "observation",
  ),
  statement(
    "us-gilens-page-elite-effect",
    "Their model found an independent association for affluent preferences",
    "In their 2014 publication, Gilens and Page reported that affluent Americans' preferences were strongly associated with outcomes in multivariate models of the 1981–2002 proposal sample after accounting for average-citizen preferences and interest-group alignments.",
    "observation",
  ),
  statement(
    "us-gilens-page-average-effect",
    "Their model found little independent association for average preferences",
    "In the same 2014 models of the 1981–2002 proposal sample, average citizens' preferences had little or no independent association with policy outcomes when correlated preferences and organized groups were included.",
    "observation",
  ),
  statement(
    "us-gilens-page-not-oligarchy-test",
    "The study compared theoretical predictions",
    "Gilens and Page's 2014 article tested predictions associated with several theories of political influence using proposals dated 1981–2002; the dataset did not measure every political decision or establish a regime-wide classification.",
    "editorial-interpretation",
  ),
  statement(
    "us-gilens-earlier-income-gradient",
    "Gilens found an income gradient in responsiveness",
    "Gilens's earlier analysis found that policy responsiveness increased with income, with the largest differences under conditions where preference gaps between income groups were wide.",
    "observation",
  ),
  statement(
    "us-bashir-model-critique",
    "Bashir challenged the regression inference",
    "In 2015, Bashir argued that correlated predictors, a dichotomous outcome, and model specification could generate an extreme contrast between affluent and average-citizen coefficients even under simulated equal influence.",
    "causal-hypothesis",
  ),
  statement(
    "us-gilens-simulation-reply",
    "Gilens challenged Bashir's simulation",
    "In 2016, Gilens replied that Bashir's simulation imposed preference distributions and relationships unlike the observed data, so it did not reproduce the inferential problem it claimed to demonstrate.",
    "causal-hypothesis",
  ),
  statement(
    "us-study-bounded-conclusion",
    "The exchange leaves a bounded unequal-influence finding",
    "The study and its methodological exchange support scrutiny of unequal policy responsiveness within the sampled federal proposals, not a score or verdict for the United States as a whole.",
    "editorial-interpretation",
  ),

  {
    documentType: "entity",
    entity: {
      id: "athens-four-hundred-five-thousand-411-bce",
      kind: "case",
      label: "Athens’ Four Hundred and Five Thousand, 411 BCE",
      description:
        "A bounded constitutional episode during the Peloponnesian War.",
      locationIds: ["athens"],
      startDate: { year: -411, certainty: "exact", note: "411 BCE" },
      endDate: { year: -411, certainty: "exact", note: "411 BCE" },
      scope:
        "The overthrow, approximately four-month rule of the Four Hundred, and transfer to the Five Thousand during 411 BCE; not classical Athens as a whole.",
      selectionRationale:
        "The episode separates proposed participation, actual control, coercive practice, and constitutional succession within one named ancient setting.",
      conditionStatementIds: ["athens-411-war-crisis"],
      episodeIds: ["athens-411-constitutional-change"],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "athens-411-constitutional-change",
      kind: "case-episode",
      label: "Athenian constitutional change, 411 BCE",
      description:
        "The Four Hundred's rule and its replacement by the Five Thousand.",
      caseId: "athens-four-hundred-five-thousand-411-bce",
      locationIds: ["athens"],
      startDate: { year: -411, certainty: "exact", note: "411 BCE" },
      endDate: { year: -411, certainty: "exact", note: "411 BCE" },
      scope:
        "Institutions and reported coercive practices during the 411 BCE episode.",
      conditionStatementIds: ["athens-411-war-crisis"],
      formalRuleStatementIds: ["athens-411-five-thousand-proposal"],
      ruleInUseStatementIds: [
        "athens-411-four-hundred-actual-rule",
        "athens-411-coercion",
      ],
      interactionStatementIds: [],
      outcomeStatementIds: [
        "athens-411-four-hundred-duration",
        "athens-411-five-thousand-successor",
      ],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "indonesia-oligarchy-debate-1998-2013",
      kind: "case",
      label: "Indonesia oligarchy debate, 1998–2013",
      description:
        "A bounded scholarly debate about wealth, organization, institutions, and power after the New Order.",
      locationIds: ["indonesia"],
      startDate: { year: 1998, certainty: "exact" },
      endDate: { year: 2013, certainty: "exact" },
      scope:
        "Competing scholarly explanations of Indonesian political power from the 1998 transition through the 2013 Indonesia exchange; not a regime label.",
      selectionRationale:
        "The exchange makes rival mechanisms and the limits of transferring wealth-defense theory directly visible.",
      conditionStatementIds: ["indonesia-democracy-coexistence"],
      episodeIds: ["indonesia-post-new-order-power-debate"],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "indonesia-post-new-order-power-debate",
      kind: "case-episode",
      label: "Post-New Order power debate, 1998–2013",
      description:
        "The rival material, organizational, and institutional explanations in the selected exchange.",
      caseId: "indonesia-oligarchy-debate-1998-2013",
      locationIds: ["indonesia"],
      startDate: { year: 1998, certainty: "exact" },
      endDate: { year: 2013, certainty: "exact" },
      scope:
        "Claims made in the selected scholarly exchange rather than every Indonesian political contest.",
      conditionStatementIds: ["indonesia-democracy-coexistence"],
      formalRuleStatementIds: [],
      ruleInUseStatementIds: [],
      interactionStatementIds: [
        "indonesia-winters-material-power",
        "indonesia-winters-wealth-defense",
        "indonesia-hadiz-robison-rival",
        "indonesia-beyond-oligarchy-critique",
      ],
      outcomeStatementIds: [],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "us-federal-policy-preferences-1981-2002",
      kind: "case",
      label: "U.S. federal policy-preference study, 1981–2002",
      description:
        "The 1981–2002 federal proposal sample later analyzed by Gilens and Page.",
      locationIds: ["united-states"],
      startDate: { year: 1981, certainty: "exact" },
      endDate: { year: 2002, certainty: "exact" },
      scope:
        "The federal policy proposals dated 1981–2002 and the preferences and outcomes recorded for them; the 2014 analysis and 2015–2016 methodological exchange are later publications, not events inside this period.",
      selectionRationale:
        "The case distinguishes a dataset and model result from the broader labels attached to it in public discussion.",
      conditionStatementIds: ["us-gilens-page-dataset"],
      episodeIds: ["us-policy-responsiveness-analysis-1981-2002"],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "us-policy-responsiveness-analysis-1981-2002",
      kind: "case-episode",
      label: "Federal policy-responsiveness analysis, 1981–2002",
      description:
        "The dates covered by the sampled federal proposals, distinct from the later publication chronology.",
      caseId: "us-federal-policy-preferences-1981-2002",
      locationIds: ["united-states"],
      startDate: { year: 1981, certainty: "exact" },
      endDate: { year: 2002, certainty: "exact" },
      scope:
        "Proposal dates and recorded outcomes from 1981–2002; not the dates of the 2014 model, 2015 critique, or 2016 reply.",
      conditionStatementIds: ["us-gilens-page-dataset"],
      formalRuleStatementIds: [],
      ruleInUseStatementIds: [],
      interactionStatementIds: [],
      outcomeStatementIds: [],
      ...reviewed,
    },
  },
] satisfies AuthoringDocument[];
