import type { AuthoringDocument } from "../../../src/lib/domain";

const reviewed = { publicationStatus: "reviewed" as const };

export const rehnMeidnerEvidenceDocuments = [
  { documentType: "entity", entity: { id: "erixon-rehn-meidner-model-work", kind: "work", label: "The Rehn–Meidner Model in Sweden", description: "Lennart Erixon's historical and institutional analysis of the policy model and its uneven Swedish application.", title: "The Rehn–Meidner Model in Sweden: Its Rise, Challenges and Survival", workType: "article", originalPublicationYear: 2010, ...reviewed } },
  { documentType: "entity", entity: { id: "erixon-rehn-meidner-model-source", kind: "source", label: "The Rehn–Meidner Model in Sweden (2010)", description: "The peer-reviewed Journal of Economic Issues article consulted for the model's objectives, mechanisms, institutional context, and application boundaries.", title: "The Rehn–Meidner Model in Sweden: Its Rise, Challenges and Survival", sourceType: "article", workId: "erixon-rehn-meidner-model-work", contributorDisplay: ["Lennart Erixon"], publicationYear: 2010, publisher: "Taylor & Francis", identifiers: { doi: "10.2753/JEI0021-3624440306" }, resourceLinks: [{ purpose: "publisher", url: "https://doi.org/10.2753/JEI0021-3624440306", label: "Publisher record" }], ...reviewed } },
  { documentType: "entity", entity: { id: "molinder-solidaristic-wage-policy-work", kind: "work", label: "Wage differentials, economic restructuring and the solidaristic wage policy in Sweden", description: "Jakob Molinder's empirical study of Swedish wage dispersion and restructuring under solidaristic bargaining.", title: "Wage differentials, economic restructuring and the solidaristic wage policy in Sweden", workType: "article", originalPublicationYear: 2019, ...reviewed } },
  { documentType: "entity", entity: { id: "molinder-solidaristic-wage-policy-source", kind: "source", label: "Wage differentials and solidaristic wage policy (2019)", description: "The peer-reviewed European Review of Economic History article consulted for the timing and interpretation of Swedish wage compression.", title: "Wage differentials, economic restructuring and the solidaristic wage policy in Sweden", sourceType: "article", workId: "molinder-solidaristic-wage-policy-work", contributorDisplay: ["Jakob Molinder"], publicationYear: 2019, publisher: "Oxford University Press", identifiers: { doi: "10.1093/ereh/hey005" }, resourceLinks: [{ purpose: "publisher", url: "https://doi.org/10.1093/ereh/hey005", label: "Publisher record" }, { purpose: "library", url: "https://uu.diva-portal.org/smash/record.jsf?pid=diva2%3A1270722", label: "Uppsala University record" }], ...reviewed } },
  { documentType: "entity", entity: { id: "hibbs-locking-wage-dispersion-work", kind: "work", label: "Wage Dispersion and Productive Efficiency", description: "Douglas Hibbs and Håkan Locking's empirical analysis of wage dispersion and productive efficiency in Sweden.", title: "Wage Dispersion and Productive Efficiency: Evidence for Sweden", workType: "article", originalPublicationYear: 2000, ...reviewed } },
  { documentType: "entity", entity: { id: "hibbs-locking-wage-dispersion-source", kind: "source", label: "Wage Dispersion and Productive Efficiency (2000)", description: "The peer-reviewed Journal of Labor Economics article consulted for differentiated findings about interindustry and within-industry wage compression.", title: "Wage Dispersion and Productive Efficiency: Evidence for Sweden", sourceType: "article", workId: "hibbs-locking-wage-dispersion-work", contributorDisplay: ["Douglas A. Hibbs Jr.", "Håkan Locking"], publicationYear: 2000, publisher: "University of Chicago Press", identifiers: { doi: "10.1086/209976" }, resourceLinks: [{ purpose: "publisher", url: "https://doi.org/10.1086/209976", label: "Publisher record" }], ...reviewed } },

  { documentType: "entity", entity: { id: "rehn-meidner-declared-objectives", kind: "statement", label: "Rehn–Meidner program objectives", description: "A secondary-source attribution of the program's stated objectives.", statementKind: "attributed-value", text: "Rehn and Meidner advocated combining full employment and fair wages with price stability and high economic growth.", ...reviewed } },
  { documentType: "entity", entity: { id: "rehn-meidner-policy-combination", kind: "statement", label: "Rehn–Meidner policy combination", description: "A sourced description of the program's component mechanisms.", statementKind: "definition", text: "The Rehn–Meidner model combined solidaristic wage policy and active labor-market policy with restrictive macroeconomic policy over the business cycle.", ...reviewed } },
  { documentType: "entity", entity: { id: "centralized-solidaristic-bargaining-form", kind: "statement", label: "Centralized solidaristic bargaining form", description: "A sourced observation about the bargaining institutions associated with Swedish wage compression.", statementKind: "observation", text: "From 1956 to 1983, Swedish solidaristic wage policy operated through coordinated peak bargaining with industry and workplace implementation rather than through one uniform wage fixed centrally.", ...reviewed } },
  { documentType: "entity", entity: { id: "active-labor-market-adjustment-design", kind: "statement", label: "Active labor-market adjustment design", description: "A sourced account of active labor-market policy in the Rehn–Meidner model.", statementKind: "definition", text: "The model paired selective employment support with mobility-enhancing adjustment measures intended to sustain employment and move labor toward expanding activities.", ...reviewed } },
  { documentType: "entity", entity: { id: "restrictive-macroeconomic-policy-design", kind: "statement", label: "Restrictive macroeconomic policy design", description: "A sourced account of the model's restrictive general economic policy.", statementKind: "definition", text: "The model called for restrictive general fiscal policy over the business cycle to restrain inflationary excess demand while selective policies pursued employment and adjustment.", ...reviewed } },
  { documentType: "entity", entity: { id: "swedish-active-labor-market-policy-expansion", kind: "statement", label: "Swedish active labor-market policy expansion", description: "A bounded observation about actual Swedish expansion of active labor-market policy during the model's strongest period of influence.", statementKind: "observation", text: "Sweden expanded active labor-market policy from the late 1950s into the early 1970s, during the period Erixon identifies as the Rehn–Meidner model's strongest practical influence.", ...reviewed } },
  { documentType: "entity", entity: { id: "rehn-meidner-partial-swedish-application", kind: "statement", label: "Partial Swedish application", description: "A qualified classification separating the model from Swedish policy practice.", statementKind: "classification", text: "Sweden never consistently applied the full Rehn–Meidner package, although the late 1950s to early 1970s combined an expansion of active labor-market policy and solidaristic wage policy during the model's strongest period of influence.", ...reviewed } },
  { documentType: "entity", entity: { id: "rehn-meidner-social-democratic-context", kind: "statement", label: "Social-democratic context of the Rehn–Meidner model", description: "A qualified classification of the named policy model within Swedish social-democratic politics.", statementKind: "classification", text: "The Rehn–Meidner model became influential in a Swedish setting shaped by Social Democratic government and organized labor, but it remained a distinct program whose components were adopted unevenly.", ...reviewed } },
  { documentType: "entity", entity: { id: "solidaristic-wage-compression-timing", kind: "statement", label: "Timing of Swedish wage compression", description: "An empirical finding about when wage dispersion changed during centralized bargaining.", statementKind: "observation", text: "Swedish wage inequality remained stable from the introduction of centralized bargaining until the late 1960s and then declined rapidly; Molinder attributes a substantial part of the 1970s decline to deliberate union policy.", ...reviewed } },
  { documentType: "entity", entity: { id: "wage-compression-restructuring-qualification", kind: "statement", label: "Qualification of the restructuring account", description: "A rival empirical interpretation of the timing of wage compression and structural change.", statementKind: "observation", text: "Molinder finds that declining wage dispersion coincided with falling growth and structural change, challenging a simple claim that solidaristic wage compression generated the earlier restructuring peak.", ...reviewed } },
  { documentType: "entity", entity: { id: "interindustry-compression-productivity-result", kind: "statement", label: "Interindustry compression and productivity", description: "An empirical result separating interindustry from within-industry wage compression.", statementKind: "observation", text: "Hibbs and Locking find that reduced interindustry wage differentials contributed positively to aggregate output and productivity growth, while finding no support for productivity gains from wage leveling within workplaces and industries.", ...reviewed } },
  { documentType: "entity", entity: { id: "rehn-meidner-distribution-assessment", kind: "statement", label: "Distribution assessment of the bargaining episode", description: "A criterion-specific interpretation limited to the distributional evidence available in this tranche.", statementKind: "editorial-interpretation", text: "The centralized-bargaining episode compressed wage differentials, especially during the 1970s, but this evidence does not establish the broader distribution of income, wealth, control, or adjustment costs.", ...reviewed } },

  { documentType: "entity", entity: { id: "swedish-solidaristic-bargaining", kind: "case", label: "Swedish solidaristic wage bargaining", description: "The bounded Swedish period of coordinated solidaristic bargaining used to examine wage compression and adjustment mechanisms without treating Sweden as an embodiment of the Rehn–Meidner model.", locationIds: ["sweden"], startDate: { year: 1956, certainty: "exact" }, endDate: { year: 1983, certainty: "exact" }, scope: "Centralized solidaristic bargaining between the 1956 introduction of peak bargaining and its 1983 breakdown; excludes treating every Swedish macroeconomic or labor-market policy in the period as part of one coherent package.", selectionRationale: "This episode separates a proposed policy model from partial institutional implementation and exposes rival findings about wage distribution, productivity, and restructuring.", conditionStatementIds: ["rehn-meidner-social-democratic-context"], episodeIds: ["centralized-solidaristic-bargaining-1956-1983"], ...reviewed } },
  { documentType: "entity", entity: { id: "centralized-solidaristic-bargaining-1956-1983", kind: "case-episode", label: "Centralized solidaristic bargaining, 1956–1983", description: "The period in which peak-level solidaristic agreements structured Swedish wage bargaining before central bargaining broke down.", caseId: "swedish-solidaristic-bargaining", locationIds: ["sweden"], startDate: { year: 1956, certainty: "exact" }, endDate: { year: 1983, certainty: "exact" }, scope: "The coordinated wage-bargaining institution and its distributional record; other components of Swedish economic policy enter only where the cited evidence supports their relationship.", conditionStatementIds: ["rehn-meidner-social-democratic-context"], formalRuleStatementIds: ["centralized-solidaristic-bargaining-form"], ruleInUseStatementIds: ["rehn-meidner-partial-swedish-application"], interactionStatementIds: ["swedish-active-labor-market-policy-expansion"], outcomeStatementIds: ["solidaristic-wage-compression-timing", "wage-compression-restructuring-qualification", "interindustry-compression-productivity-result"], ...reviewed } },
] satisfies AuthoringDocument[];
