import type { AuthoringDocument } from "../../../src/lib/domain";

const reviewed = { publicationStatus: "reviewed" as const };

const statement = (
  id: string,
  label: string,
  text: string,
  statementKind:
    | "observation"
    | "attributed-value"
    | "attributed-proposal"
    | "causal-hypothesis"
    | "editorial-interpretation" = "observation",
): AuthoringDocument => ({
  documentType: "entity",
  entity: {
    id,
    kind: "statement",
    label,
    description: label,
    statementKind,
    text,
    ...reviewed,
  },
});

const constitutionalRuleIds = [
  "sc-constitution-elector-membership-1868",
  "sc-constitution-elector-residence-1868",
  "sc-constitution-federal-disability-exclusion",
  "sc-constitution-institutional-confinement-exclusion",
  "sc-constitution-prison-confinement-exclusion",
  "sc-constitution-enslavement-conviction-boundary",
  "sc-constitution-county-office-elector-rule",
  "sc-constitution-general-office-elector-rule",
  "sc-constitution-first-election-residence-exception",
  "sc-constitution-religious-office-test",
  "sc-constitution-free-open-election-rule",
  "sc-constitution-equal-elect-and-be-elected-rule",
  "sc-constitution-no-property-office-qualification",
  "sc-constitution-election-protection-directive",
  "sc-house-population-apportionment-rule",
  "sc-house-county-minimum-representation-rule",
];

export const southCarolinaReconstructionEvidenceDocuments = [
  {
    documentType: "entity",
    entity: {
      id: "south-carolina",
      kind: "place",
      label: "South Carolina",
      description: "A state of the United States and the jurisdiction of the 1868 constitution examined in this Case.",
      placeType: "institutional-jurisdiction",
      externalRefs: [
        { system: "wikipedia", url: "https://en.wikipedia.org/wiki/South_Carolina", purpose: "orientation", language: "en", checkedAt: "2026-09-08" },
        { system: "wikidata", id: "Q1456", url: "https://www.wikidata.org/wiki/Q1456", purpose: "identity", match: "exact", checkedAt: "2026-09-08" },
      ],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "south-carolina-upcountry",
      kind: "place",
      label: "South Carolina upcountry",
      description: "The inland South Carolina counties discussed in the federal enforcement record.",
      placeType: "region",
      externalRefs: [
        { system: "wikipedia", url: "https://en.wikipedia.org/wiki/Upstate_South_Carolina", purpose: "orientation", language: "en", checkedAt: "2026-09-08" },
        { system: "wikidata", id: "Q7899317", url: "https://www.wikidata.org/wiki/Q7899317", purpose: "identity", match: "close", checkedAt: "2026-09-08" },
      ],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "hamburg-south-carolina",
      kind: "place",
      label: "Hamburg, South Carolina",
      description: "The Reconstruction-era settlement in Edgefield County where the July 1876 confrontation occurred.",
      placeType: "settlement",
      externalRefs: [
        { system: "wikipedia", url: "https://en.wikipedia.org/wiki/Hamburg,_South_Carolina", purpose: "orientation", language: "en", checkedAt: "2026-09-08" },
        { system: "wikidata", id: "Q5644268", url: "https://www.wikidata.org/wiki/Q5644268", purpose: "identity", match: "exact", checkedAt: "2026-09-08" },
      ],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "columbia-south-carolina",
      kind: "place",
      label: "Columbia, South Carolina",
      description: "South Carolina's capital; the April 1877 executive-office transfer occurred at its State House.",
      placeType: "city",
      externalRefs: [
        { system: "wikipedia", url: "https://en.wikipedia.org/wiki/Columbia,_South_Carolina", purpose: "orientation", language: "en", checkedAt: "2026-09-08" },
        { system: "wikidata", id: "Q38453", url: "https://www.wikidata.org/wiki/Q38453", purpose: "identity", match: "exact", checkedAt: "2026-09-08" },
      ],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "political-coercion",
      kind: "concept",
      label: "Political coercion",
      description: "A dated use or threat of force directed at political participation, organization, or control.",
      schemeIds: ["political-economic-ideas"],
      scopeNote: "Use as an Event kind; it records a sourced episode of coercion without determining its prevalence or causal effect.",
      ...reviewed,
    },
  },

  {
    documentType: "entity",
    entity: {
      id: "sc-1868-constitution-work",
      kind: "work",
      label: "Constitution of the State of South Carolina",
      description: "South Carolina's 1868 constitution establishing electoral, officeholding, representation, and election rules.",
      title: "Constitution of the State of South Carolina",
      workType: "constitution",
      originalPublicationYear: 1868,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1868-constitution-later-compilation-source",
      kind: "source",
      label: "South Carolina Constitution of 1868 (later compilation scan)",
      description: "A Justice for All South Carolina-hosted 110-page scan that reproduces the 1868 constitution together with amendments through at least December 1884; the manifestation is later than the constitutional Work.",
      title: "Constitution of the State of South Carolina",
      sourceType: "legal-text",
      workId: "sc-1868-constitution-work",
      contributorDisplay: ["South Carolina Constitutional Convention"],
      publisher: "Justice for All South Carolina",
      resourceLinks: [{ purpose: "authorized-reading", url: "https://www.justiceforallsc.org/wp-content/uploads/2022/09/01-LOC_SC_1868_Constitution.pdf", label: "Inspect the later compilation scan" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1868-convention-proceedings-work",
      kind: "work",
      label: "Proceedings of the Constitutional Convention of South Carolina",
      description: "The printed debates and proceedings of South Carolina's January–March 1868 constitutional convention.",
      title: "Proceedings of the Constitutional Convention of South Carolina, Held at Charleston, S.C., Beginning January 14th and Ending March 17th, 1868",
      workType: "archival-work",
      originalPublicationYear: 1868,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1868-convention-proceedings-scan-source",
      kind: "source",
      label: "South Carolina constitutional convention proceedings (public-domain scan)",
      description: "The Wikimedia Commons and Internet Archive scan of the 1868 Denny & Perry volume digitized from the University of Michigan copy.",
      title: "Proceedings of the Constitutional Convention of South Carolina",
      sourceType: "edition",
      workId: "sc-1868-convention-proceedings-work",
      contributorDisplay: ["South Carolina Constitutional Convention"],
      publicationYear: 1868,
      publisher: "Denny & Perry",
      resourceLinks: [{ purpose: "archive", url: "https://commons.wikimedia.org/wiki/File:Proceedings_of_the_Constitutional_convention_of_South_Carolina,_held_at_Charleston,_S._C.,_beginning_January_14th_and_ending_March_17th,_1868.pdf", label: "Inspect the convention proceedings scan" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1868-ratification-certification-work",
      kind: "work",
      label: "Certification of South Carolina's 1868 constitution vote",
      description: "A. G. Mackey's May 1868 certification of convention adoption and the April 14–16 elector vote.",
      title: "Letter from the President of the Constitutional Convention of South Carolina",
      workType: "archival-work",
      originalPublicationYear: 1868,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1868-ratification-govinfo-source",
      kind: "source",
      label: "South Carolina ratification certification (GovInfo scan)",
      description: "The GovInfo scan of House Executive Document 274 in Serial Set 1343, containing Mackey's May 5, 1868 certification.",
      title: "Letter from the President of the Constitutional Convention of South Carolina",
      sourceType: "archival-record",
      workId: "sc-1868-ratification-certification-work",
      contributorDisplay: ["A. G. Mackey (author)"],
      publicationYear: 1868,
      publisher: "United States Government Printing Office",
      resourceLinks: [{ purpose: "archive", url: "https://www.govinfo.gov/content/pkg/SERIALSET-01343_00_00-023-0274-0000/pdf/SERIALSET-01343_00_00-023-0274-0000.pdf", label: "Inspect the certification scan" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1868-admission-history-work",
      kind: "work",
      label: "The veto of the Omnibus Southern States Admission Bill",
      description: "The U.S. House historian's account of Congress's June 25, 1868 admission legislation and veto override.",
      title: "The veto of the Omnibus Southern States Admission Bill",
      workType: "other",
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1868-admission-house-history-source",
      kind: "source",
      label: "Omnibus Southern States Admission Bill (House History page)",
      description: "The current U.S. House History page used for the separate June 25, 1868 congressional admission event.",
      title: "The veto of the Omnibus Southern States Admission Bill",
      sourceType: "web-page",
      workId: "sc-1868-admission-history-work",
      contributorDisplay: ["Office of the Historian, U.S. House of Representatives"],
      publisher: "U.S. House of Representatives",
      resourceLinks: [{ purpose: "publisher", url: "https://history.house.gov/Historical-Highlights/1851-1900/The-veto-of-the-Omnibus-Southern-States-Admission-Bill/", label: "Read the House historical account" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1865-colored-convention-address-work",
      kind: "work",
      label: "Address of the Colored State Convention",
      description: "The November 1865 address in which South Carolina convention delegates demanded political membership and representation for Black men.",
      title: "Address of the Colored State Convention to the People of the State of South Carolina",
      workType: "archival-work",
      originalPublicationYear: 1865,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1865-colored-convention-house-divided-source",
      kind: "source",
      label: "Colored State Convention address (House Divided transcription)",
      description: "A House Divided transcription identifying the address's November 24, 1865 date and original proceedings provenance.",
      title: "Address of the Colored State Convention to the People of the State of South Carolina",
      sourceType: "web-page",
      workId: "sc-1865-colored-convention-address-work",
      contributorDisplay: ["Colored People's Convention of South Carolina"],
      publisher: "House Divided Project, Dickinson College",
      resourceLinks: [{ purpose: "authorized-reading", url: "https://hd.housedivided.dickinson.edu/node/44782", label: "Read the transcribed address" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1867-black-organizer-letter-work",
      kind: "work",
      label: "Letter from a Black South Carolina organizer",
      description: "An unnamed organizer's August 1867 report of meetings and Union League organization across South Carolina districts.",
      title: "Letter from a Black organizer in South Carolina",
      workType: "archival-work",
      originalPublicationYear: 1867,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-1867-black-organizer-ldhi-source",
      kind: "source",
      label: "Black organizer's 1867 letter (LDHI transcription)",
      description: "The Lowcountry Digital History Initiative transcription of an August 2, 1867 letter in the Robert C. Schenck Papers at Miami University Archives.",
      title: "Letter from a Black organizer in South Carolina",
      sourceType: "web-page",
      workId: "sc-1867-black-organizer-letter-work",
      contributorDisplay: ["Unnamed Black organizer (author)"],
      publisher: "Lowcountry Digital History Initiative",
      resourceLinks: [{ purpose: "authorized-reading", url: "https://ldhi.library.cofc.edu/exhibits/show/after_slavery_educator/unit_two_documents/document_three", label: "Read the transcribed letter" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-black-political-activism-house-history-work",
      kind: "work",
      label: "Reconstruction and Black Political Activism",
      description: "The U.S. House historian's account of Black political participation and officeholding during Reconstruction.",
      title: "Reconstruction and Black Political Activism",
      workType: "report",
      originalPublicationYear: 2008,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-black-political-activism-house-history-source",
      kind: "source",
      label: "Reconstruction and Black Political Activism (House History page)",
      description: "The U.S. House History web presentation used for its separately dated South Carolina House and Senate composition claims.",
      title: "Reconstruction and Black Political Activism",
      sourceType: "web-page",
      workId: "sc-black-political-activism-house-history-work",
      contributorDisplay: ["Office of the Historian, U.S. House of Representatives"],
      publisher: "U.S. House of Representatives",
      resourceLinks: [{ purpose: "publisher", url: "https://history.house.gov/Exhibitions-and-Publications/BAIC/Historical-Essays/Fifteenth-Amendment/Reconstruction/", label: "Read the House historical account" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-joint-select-committee-testimony-work",
      kind: "work",
      label: "South Carolina testimony on conditions in the late insurrectionary states",
      description: "The 1872 congressional volume preserving testimony about Ku Klux Klan violence in South Carolina.",
      title: "Report of the Joint Select Committee to Inquire into the Condition of Affairs in the Late Insurrectionary States: South Carolina Testimony",
      workType: "report",
      originalPublicationYear: 1872,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-elias-hill-testimony-reproduction-source",
      kind: "source",
      label: "Elias Hill testimony (Roots and Recall reproduction)",
      description: "A ten-page reproduction containing Elias Hill's July 25, 1871 Yorkville testimony, beginning at original printed page 1406.",
      title: "Testimony of Elias Hill",
      sourceType: "archival-record",
      workId: "sc-joint-select-committee-testimony-work",
      contributorDisplay: ["Elias Hill (witness)", "Joint Select Committee (compiler)"],
      publisher: "Roots and Recall",
      resourceLinks: [{ purpose: "authorized-reading", url: "https://www.rootsandrecall.com/york-county-sc/files/2015/07/1477579757Elias_Hill_1871_Testimony.pdf", label: "Inspect Hill's reproduced testimony" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-freedpeople-testimony-ldhi-selection-source",
      kind: "source",
      label: "Freedpeople's Klan testimony (LDHI selection)",
      description: "An LDHI selection that preserves named witnesses and original page locators from the 1872 congressional South Carolina testimony volume.",
      title: "Freedpeople's Testimony on the Effects of Klan Violence",
      sourceType: "web-page",
      workId: "sc-joint-select-committee-testimony-work",
      contributorDisplay: ["Alberry Bonner and other named witnesses", "Joint Select Committee (compiler)"],
      publisher: "Lowcountry Digital History Initiative",
      resourceLinks: [{ purpose: "authorized-reading", url: "https://ldhi.library.cofc.edu/exhibits/show/after_slavery_educator/unit_nine_documents/document_9", label: "Read the selected testimony" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-klan-trials-fjc-work",
      kind: "work",
      label: "The South Carolina Ku Klux Klan Trials of 1871–1872",
      description: "Jake Kobrick's institutional history of the federal South Carolina Klan prosecutions and their limits.",
      title: "The South Carolina Ku Klux Klan Trials of 1871–1872",
      workType: "other",
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-klan-trials-fjc-source",
      kind: "source",
      label: "South Carolina Ku Klux Klan trials (FJC page)",
      description: "The Federal Judicial Center institutional-history page used for federal rules, actions, procedural results, and its attributed assessment.",
      title: "The South Carolina Ku Klux Klan Trials of 1871–1872",
      sourceType: "web-page",
      workId: "sc-klan-trials-fjc-work",
      contributorDisplay: ["Jake Kobrick (author)"],
      publisher: "Federal Judicial Center",
      resourceLinks: [{ purpose: "publisher", url: "https://www.fjc.gov/node/9778536", label: "Read the FJC institutional history" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "army-reconstruction-bradley-work",
      kind: "work",
      label: "The Army and Reconstruction, 1865–1877",
      description: "Mark L. Bradley's U.S. Army history of military roles during Reconstruction.",
      title: "The Army and Reconstruction, 1865–1877",
      workType: "report",
      originalPublicationYear: 2015,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "army-reconstruction-govinfo-source",
      kind: "source",
      label: "The Army and Reconstruction (GovInfo PDF)",
      description: "The GovInfo copy of U.S. Army Center of Military History publication CMH Pub 75–18.",
      title: "The Army and Reconstruction, 1865–1877",
      sourceType: "report",
      workId: "army-reconstruction-bradley-work",
      contributorDisplay: ["Mark L. Bradley (author)"],
      publicationYear: 2015,
      publisher: "U.S. Army Center of Military History",
      resourceLinks: [{ purpose: "publisher", url: "https://www.govinfo.gov/content/pkg/GOVPUB-D114-PURL-gpo60344/pdf/GOVPUB-D114-PURL-gpo60344.pdf", label: "Inspect the Army history" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "stone-hamburg-report-work",
      kind: "work",
      label: "Report on the Hamburg confrontation",
      description: "South Carolina Attorney General William Stone's July 12, 1876 report to Governor Daniel H. Chamberlain.",
      title: "Report on the Hamburg disturbance",
      workType: "report",
      originalPublicationYear: 1876,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "stone-hamburg-report-congressional-record-source",
      kind: "source",
      label: "Stone's Hamburg report (Congressional Record reproduction)",
      description: "Stone's report as reproduced in the August 8, 1876 Congressional Record—Senate at printed page 5316; Stone was not an eyewitness and said the inquest remained unfinished.",
      title: "Report on the Hamburg disturbance",
      sourceType: "archival-record",
      workId: "stone-hamburg-report-work",
      contributorDisplay: ["William Stone (author)"],
      publicationYear: 1876,
      publisher: "United States Government Printing Office",
      resourceLinks: [{ purpose: "archive", url: "https://www.govinfo.gov/content/pkg/GPO-CRECB-1876-pt6-v4/pdf/GPO-CRECB-1876-pt6-v4-9-1.pdf", label: "Inspect the Congressional Record reproduction" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "anderson-intelligencer-transfer-work",
      kind: "work",
      label: "The Troops Removed",
      description: "The Anderson Intelligencer's April 12, 1877 report and reproduced correspondence about troop withdrawal and executive-office transfer.",
      title: "The Troops Removed",
      workType: "archival-work",
      originalPublicationYear: 1877,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "anderson-intelligencer-usc-ocr-source",
      kind: "source",
      label: "The Troops Removed (USC newspaper scan and OCR)",
      description: "The University of South Carolina Historical Newspapers scan and OCR of the partisan Anderson Intelligencer page; the reproduced correspondence and dated event report are used, not the paper's political verdicts.",
      title: "The Troops Removed",
      sourceType: "archival-record",
      workId: "anderson-intelligencer-transfer-work",
      contributorDisplay: ["Anderson Intelligencer"],
      publicationYear: 1877,
      publisher: "University of South Carolina Historical Newspapers",
      resourceLinks: [{ purpose: "archive", url: "https://historicnewspapers.sc.edu/lccn/sn84026965/1877-04-12/ed-2/seq-2/ocr/", label: "Inspect the newspaper page and OCR" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "usc-hampton-transfer-history-work",
      kind: "work",
      label: "Wade Hampton historical commission account",
      description: "A University of South Carolina historical commission account of Hampton's April 1877 assumption of office.",
      title: "Wade Hampton College",
      workType: "report",
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "usc-hampton-transfer-history-source",
      kind: "source",
      label: "Wade Hampton historical commission account (USC page)",
      description: "The University of South Carolina commission page used only to corroborate the April 11 office assumption and its relation to troop withdrawal.",
      title: "Wade Hampton College",
      sourceType: "web-page",
      workId: "usc-hampton-transfer-history-work",
      contributorDisplay: ["University of South Carolina Presidential Commission"],
      publisher: "University of South Carolina",
      resourceLinks: [{ purpose: "publisher", url: "https://sc.edu/about/our_history/university_history/presidential_commission/commission_reports/final_report/appendices/appendix-11/recommended-for-removal/wade_hampton_college.php", label: "Read the commission account" }],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "klan-evidence-history-work",
      kind: "work",
      label: "Ku Klux Klan Violence and the Problem of Evidence",
      description: "Stephanie McCurry's analysis of the political construction and interpretive limits of the congressional Klan archive.",
      title: "Ku Klux Klan Violence and the Problem of Evidence",
      workType: "article",
      originalPublicationYear: 2025,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "klan-evidence-history-source",
      kind: "source",
      label: "Ku Klux Klan Violence and the Problem of Evidence (Cambridge article)",
      description: "The open-access Law and History Review article, volume 43, pages 239–257, used to qualify the congressional archive's scope and mediation.",
      title: "Ku Klux Klan Violence and the Problem of Evidence",
      sourceType: "article",
      workId: "klan-evidence-history-work",
      contributorDisplay: ["Stephanie McCurry (author)"],
      publicationYear: 2025,
      publisher: "Cambridge University Press",
      identifiers: { doi: "10.1017/S0738248025101065" },
      resourceLinks: [{ purpose: "publisher", url: "https://www.cambridge.org/core/services/aop-cambridge-core/content/view/3F4521B6CE72AD2ED0BB39AD2EE35C22/S0738248025101065a.pdf/ku-klux-klan-violence-and-the-problem-of-evidence.pdf", label: "Read the open-access article" }],
      ...reviewed,
    },
  },

  statement("sc-colored-convention-equal-suffrage-demand", "The 1865 convention demanded equal suffrage for Black men", "Delegates to South Carolina's 1865 Colored People's Convention demanded equal suffrage for Black men on the same terms as white men.", "attributed-proposal"),
  statement("sc-colored-convention-representation-argument", "The delegates connected taxation and representation", "The delegates protested taxation without representation and denial of a voice in choosing the state's rulers.", "attributed-value"),
  statement("sc-organizer-meeting-reach-report", "An organizer reported meetings in eighteen or twenty districts", "An unnamed Black organizer reported on 2 August 1867 that he had addressed large meetings in eighteen or twenty South Carolina districts."),
  statement("sc-organizer-league-reach-report", "The organizer reported establishing Leagues in ten districts", "The same organizer reported establishing a League in ten districts."),
  statement("sc-organizer-report-scope-boundary", "One organizer's report does not establish statewide participation", "One organizer's report establishes his claimed activity, not statewide participation rates or the views of all freedpeople.", "editorial-interpretation"),

  statement("sc-constitution-elector-membership-1868", "The 1868 constitution widened elector eligibility", "Article VIII §2 made male United States citizens aged twenty-one or older eligible as electors without race, color, or former condition of servitude as a bar."),
  statement("sc-constitution-elector-residence-1868", "The elector rule distinguished adoption-time and later residents", "Article VIII §2 treated people residing in South Carolina when the constitution was adopted differently from later residents, who had to satisfy one year of state residence and sixty days in the county before voting."),
  statement("sc-constitution-federal-disability-exclusion", "Federal constitutional disability excluded electors and officeholders", "Article VIII §2 withheld voting and officeholding while a person was disqualified under the United States Constitution, unless Congress removed the disability."),
  statement("sc-constitution-institutional-confinement-exclusion", "Institutional confinement and period-specific incapacity language excluded people", "Article VIII §2 withheld voting and officeholding from people kept in an almshouse or asylum and from people the text classified with its period-specific mental-incapacity language."),
  statement("sc-constitution-prison-confinement-exclusion", "Public-prison confinement excluded electors and officeholders", "Article VIII §2 withheld voting and officeholding while a person was confined in a public prison."),
  statement("sc-constitution-enslavement-conviction-boundary", "Offenses committed during enslavement could not disfranchise", "Article VIII §12 barred disfranchisement for an offense committed while a person was enslaved."),
  statement("sc-constitution-county-office-elector-rule", "Electors could hold elective county office", "Article VIII §7 made electors eligible for elective county offices subject to the constitution's stated limits."),
  statement("sc-constitution-general-office-elector-rule", "State office generally required elector qualifications", "Article XIV §1 generally required state officeholders to possess elector qualifications, except where the constitution provided otherwise."),
  statement("sc-constitution-first-election-residence-exception", "The first election had an office-residence exception", "Article VIII §11 created a residence exception for offices filled at the first election and first legislative session under the constitution."),
  statement("sc-constitution-religious-office-test", "The constitution imposed a religious office test", "Article XIV §6 excluded a person who denied the existence of a Supreme Being from office."),
  statement("sc-constitution-free-open-election-rule", "Elections had to be free and open", "Article I §31 required elections to be free and open."),
  statement("sc-constitution-equal-elect-and-be-elected-rule", "Qualified inhabitants had equal electoral and office rights", "Article I §31 gave inhabitants who met the constitution's qualifications an equal right to elect officers and be elected to public office."),
  statement("sc-constitution-no-property-office-qualification", "Property qualifications for office were prohibited", "Article I §32 prohibited a property qualification for election to or holding office."),
  statement("sc-constitution-election-protection-directive", "Election laws had to address specified undue influence", "Article I §33 directed election laws to prohibit undue influence by power, bribery, tumult, and improper conduct under adequate penalties."),
  statement("sc-house-population-apportionment-rule", "The House was apportioned by inhabitants", "Article II §4 set a 124-member House and apportioned its members among counties according to inhabitants."),
  statement("sc-house-county-minimum-representation-rule", "Each county received at least one House member", "Article II §6 assigned at least one House member to a county even when its population share would not otherwise produce one."),
  statement("sc-constitution-later-amendment-boundary", "The constitution source contains later amendments", "The consulted compilation includes post-1877 amendments, so those later provisions cannot be treated as rules of the 1868–1877 Case without an independently dated original text.", "editorial-interpretation"),

  statement("sc-ransier-opposed-education-voting-test", "Ransier opposed an education test for voting", "Alonzo J. Ransier argued against an educational qualification for voting.", "attributed-proposal"),
  statement("sc-ransier-opposed-property-voting-test", "Ransier opposed a property test for voting", "Ransier also argued against a property qualification for voting.", "attributed-proposal"),
  statement("sc-ransier-suffrage-self-defense-argument", "Ransier described suffrage as self-defense", "Ransier described the vote as a principal means by which Black citizens could defend themselves.", "attributed-value"),
  statement("sc-whipper-male-word-removal-motion", "Whipper moved to remove male from the elector rule", "William J. Whipper moved to remove “male” from the proposed elector rule.", "attributed-proposal"),
  statement("sc-whipper-woman-suffrage-argument", "Whipper argued for women's equal claim to vote", "Whipper argued that women possessed the same claim to the ballot as men.", "attributed-value"),
  statement("sc-whipper-motion-rejected", "The convention rejected Whipper's motion", "The convention rejected Whipper's motion to remove “male.”"),
  statement("sc-convention-adopted-constitution", "The convention adopted the constitution", "The convention adopted the constitution on 17 March 1868."),
  statement("sc-electors-ratified-constitution", "Electors ratified the constitution over three days", "Mackey certified that qualified electors voted to ratify the constitution on 14, 15, and 16 April 1868."),
  statement("sc-congress-admitted-representation", "Congress admitted South Carolina to representation", "On 25 June 1868 Congress overrode President Johnson's veto of legislation admitting South Carolina and five other states to representation subject to the act's conditions."),
  statement("sc-house-black-majority-1868-1876", "The state House had reported Black majorities from 1868 through 1876", "The U.S. House historian reports Black majorities in South Carolina's state House from 1868 through 1876."),
  statement("sc-senate-black-majority-1872-1876", "The state Senate had reported Black majorities from 1872 through 1876", "The same account reports Black majorities in the state Senate from 1872 through 1876."),

  statement("sc-enforcement-act-vote-intimidation-rule", "The 1870 Enforcement Act penalized vote intimidation", "The Federal Judicial Center reports that §5 of the Enforcement Act of 1870 imposed criminal penalties for violence or intimidation used to prevent Black citizens from voting."),
  statement("sc-klan-act-voter-intimidation-rule", "The 1871 Klan Act penalized intimidation of federal-election voters", "The Federal Judicial Center reports that §2 of the Ku Klux Klan Act of 1871 criminalized violence or intimidation against a qualified voter for supporting a lawful candidate in a federal election."),
  statement("sc-hill-may-1871-assault-testimony", "Hill testified to a May 1871 assault and threat", "Elias Hill testified that masked assailants attacked and threatened him on 5 May 1871."),
  statement("sc-hill-political-renunciation-demands", "Hill testified to demands that he renounce political activity", "Hill testified that his assailants ordered him to stop a Republican newspaper, stop preaching, renounce Republicanism publicly, and leave the Union League."),
  statement("sc-hill-league-role-context", "Hill described his Union League role", "Hill testified that he had served as a local Union League president and held political meetings at his house."),
  statement("sc-bonner-league-meeting-cessation", "Bonner attributed stopped League meetings to Klan riding", "Alberry Bonner testified that his Union League stopped meeting because Klan riding made gatherings unsafe."),
  statement("sc-grant-habeas-suspension-october-1871", "Grant suspended habeas corpus in upcountry counties", "President Grant declared upcountry counties in rebellion and suspended habeas corpus there in October 1871."),
  statement("sc-federal-mass-arrests-1871", "Federal forces made more than six hundred arrests", "Federal troops detained more than 600 suspected participants by the end of 1871, according to the Federal Judicial Center account."),
  statement("sc-klan-prosecution-results", "The South Carolina prosecutions usually ended in conviction or guilty plea", "The Federal Judicial Center reports that prosecutors obtained convictions or guilty pleas in nearly all cases they pursued during the South Carolina trials."),
  statement("sc-klan-enforcement-short-term-assessment", "The FJC attributes a brief reduction in Klan violence to the prosecutions", "The Federal Judicial Center assesses the prosecutions as briefly halting Klan violence.", "causal-hypothesis"),
  statement("sc-klan-enforcement-durability-limit", "The FJC finds no durable federal protection", "The Federal Judicial Center concludes that the prosecutions did not establish durable federal protection for Black political rights.", "causal-hypothesis"),
  statement("sc-congressional-testimony-mediation-boundary", "Congressional testimony preserves voices through a partisan investigation", "Congressional testimony preserves named witnesses' accounts but was collected and published through a partisan congressional investigation, so individual testimony does not by itself establish statewide prevalence.", "editorial-interpretation"),

  statement("sc-hamburg-red-shirt-militia-confrontation", "Red Shirts confronted the Hamburg militia company", "On 8 July 1876 several hundred Red Shirts confronted a Black militia company in Hamburg and demanded its weapons."),
  statement("sc-hamburg-bradley-six-executions-account", "Bradley reports six executions after surrender", "Bradley reports six executions after most of the Hamburg company had surrendered."),
  statement("sc-hamburg-stone-five-prisoners-account", "Stone reports five prisoners killed and three wounded", "Stone's July 1876 report states that five prisoners were deliberately killed and three wounded."),
  statement("sc-hamburg-victim-membership-boundary", "The accounts do not identify every victim as a militia member", "The consulted accounts do not support describing every Black victim as a militia-company member: Stone identifies James Cook as killed while leaving the armory and says he was not a company member, and he distinguishes nonmembers among those captured.", "editorial-interpretation"),
  statement("sc-hamburg-casualty-count-conflict", "The Hamburg execution counts conflict", "Bradley's six-execution account conflicts with Stone's report of five prisoners deliberately killed; the exact count and identities require reconciliation rather than an uncontested project total.", "editorial-interpretation"),
  statement("sc-hamburg-indictments-no-trials", "Hamburg indictments produced no trials", "A subsequent investigation produced indictments, but no one stood trial for the Hamburg killings."),
  statement("sc-rifle-club-organization-october-1876", "Democrats organized sixty-eight rifle clubs", "Bradley reports that by October 1876 South Carolina Democrats had organized 13,000 men in sixty-eight rifle clubs."),
  statement("sc-rifle-club-intimidation-purpose", "Bradley attributes an intimidation purpose to rifle clubs", "Bradley describes the clubs as intended to intimidate Black militia."),
  statement("sc-rifle-club-hampton-support-purpose", "Bradley links rifle clubs to Hampton's campaign", "Bradley describes the clubs as supporting Wade Hampton's gubernatorial campaign."),
  statement("sc-grant-rifle-club-disband-order", "Grant ordered rifle clubs to disband", "On 17 October 1876 Grant ordered the rifle clubs to disband within three days."),
  statement("sc-federal-reinforcement-1876", "Grant sent federal troop reinforcements", "Grant sent reinforcements to the federal troops already in South Carolina."),
  statement("sc-disputed-election-rival-governors", "The disputed election produced rival gubernatorial claimants", "Disputed 1876 returns left rival claimants to the South Carolina governorship, and both parties inaugurated their candidates."),
  statement("sc-statehouse-troops-withdrawn-april-10", "Federal troops left the State House", "Federal troops left the South Carolina State House at noon on 10 April 1877."),
  statement("sc-chamberlain-transfer-correspondence-april-10", "Hampton and Chamberlain arranged an office transfer", "On 10 April Hampton and Chamberlain arranged through correspondence for their officers to transfer the executive chamber, records, and papers."),
  statement("sc-executive-office-transferred-april-11", "The executive office transferred on April 11", "Their private secretaries formally transferred the executive office at noon on 11 April 1877."),
  statement("sc-office-transfer-case-boundary", "The office transfer does not date the end of constitutional rules", "The 11 April boundary dates transfer of the executive office; it does not establish when constitutional rules ceased to exist or when Black political activity ended.", "editorial-interpretation"),
  statement("sc-reversal-causal-weight-boundary", "The sequence does not establish each mechanism's causal weight", "The documented killings, intimidation, disputed returns, federal decisions, and office transfer establish a sequence of mechanisms but do not establish each mechanism's relative causal weight.", "editorial-interpretation"),

  {
    documentType: "entity",
    entity: {
      id: "south-carolina-reconstruction-political-membership",
      kind: "case",
      label: "South Carolina political membership under Reconstruction, 1868–1877",
      description: "Constitutional membership, Black political organization and officeholding, coercion, federal enforcement, and the disputed transfer of state executive authority.",
      locationIds: ["south-carolina", "south-carolina-upcountry", "hamburg-south-carolina", "columbia-south-carolina", "united-states"],
      startDate: { year: 1868, month: 1, day: 14, certainty: "exact" },
      endDate: { year: 1877, month: 4, day: 11, certainty: "exact" },
      scope: "South Carolina's 1868 convention and constitutional rules, reported chamber composition, the 1871–72 federal response to political coercion, and the July 1876–April 1877 election and office-transfer sequence; not Reconstruction nationwide or the later life of the 1868 constitution.",
      selectionRationale: "The selected records distinguish demands, formal eligibility and exclusion, governing composition, named testimony, federal enforcement, conflicting Hamburg accounts, and transfer of the executive office without treating chronology as a single-cause explanation.",
      conditionStatementIds: ["sc-colored-convention-equal-suffrage-demand", "sc-colored-convention-representation-argument", "sc-organizer-meeting-reach-report", "sc-organizer-league-reach-report"],
      episodeIds: ["sc-constitution-formation-1868", "sc-black-legislative-participation-1868-1876", "sc-political-coercion-federal-enforcement-1871-1872", "sc-election-contest-office-transfer-1876-1877"],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-constitution-formation-1868",
      kind: "case-episode",
      label: "South Carolina constitution formation, January–June 1868",
      description: "Political demands, convention argument, constitutional adoption, elector ratification, and congressional admission as separately dated acts.",
      caseId: "south-carolina-reconstruction-political-membership",
      locationIds: ["south-carolina", "united-states"],
      startDate: { year: 1868, month: 1, day: 14, certainty: "exact" },
      endDate: { year: 1868, month: 6, day: 25, certainty: "exact" },
      scope: "The 1868 convention through congressional admission on June 25; it separates convention adoption, the April 14–16 elector vote, and congressional action.",
      conditionStatementIds: ["sc-colored-convention-equal-suffrage-demand", "sc-colored-convention-representation-argument", "sc-organizer-meeting-reach-report", "sc-organizer-league-reach-report"],
      formalRuleStatementIds: constitutionalRuleIds,
      ruleInUseStatementIds: [],
      interactionStatementIds: ["sc-ransier-opposed-education-voting-test", "sc-ransier-opposed-property-voting-test", "sc-ransier-suffrage-self-defense-argument", "sc-whipper-male-word-removal-motion", "sc-whipper-woman-suffrage-argument"],
      outcomeStatementIds: ["sc-whipper-motion-rejected", "sc-convention-adopted-constitution", "sc-electors-ratified-constitution", "sc-congress-admitted-representation"],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-black-legislative-participation-1868-1876",
      kind: "case-episode",
      label: "Black legislative participation, 1868–1876",
      description: "The separately reported periods of Black majority membership in South Carolina's state House and Senate.",
      caseId: "south-carolina-reconstruction-political-membership",
      locationIds: ["south-carolina"],
      startDate: { year: 1868, certainty: "exact" },
      endDate: { year: 1876, certainty: "exact" },
      scope: "Reported House and Senate majority periods under selected office-eligibility rules; not one uninterrupted legislative sitting or an exact convention composition ratio.",
      conditionStatementIds: [],
      formalRuleStatementIds: ["sc-constitution-elector-membership-1868", "sc-constitution-county-office-elector-rule", "sc-constitution-general-office-elector-rule", "sc-constitution-religious-office-test"],
      ruleInUseStatementIds: [],
      interactionStatementIds: [],
      outcomeStatementIds: ["sc-house-black-majority-1868-1876", "sc-senate-black-majority-1872-1876"],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-political-coercion-federal-enforcement-1871-1872",
      kind: "case-episode",
      label: "Political coercion and federal enforcement, 1871–1872",
      description: "Hill's dated testimony, federal criminal rules and actions, prosecution results, and a bounded short-term assessment.",
      caseId: "south-carolina-reconstruction-political-membership",
      locationIds: ["south-carolina", "south-carolina-upcountry", "united-states"],
      startDate: { year: 1871, month: 5, day: 5, certainty: "exact" },
      endDate: { year: 1872, month: 11, certainty: "approximate", note: "The FJC account reports trial activity from November 1871 through November 1872 without a single closing day." },
      scope: "The May 5 attack described by Hill through the South Carolina trials ending in November 1872; Bonner's undated underlying events and the FJC's later durability assessment remain outside Episode roles.",
      conditionStatementIds: ["sc-hill-league-role-context"],
      formalRuleStatementIds: ["sc-enforcement-act-vote-intimidation-rule", "sc-klan-act-voter-intimidation-rule"],
      ruleInUseStatementIds: [],
      interactionStatementIds: ["sc-hill-may-1871-assault-testimony", "sc-hill-political-renunciation-demands", "sc-grant-habeas-suspension-october-1871", "sc-federal-mass-arrests-1871"],
      outcomeStatementIds: ["sc-klan-prosecution-results", "sc-klan-enforcement-short-term-assessment"],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "sc-election-contest-office-transfer-1876-1877",
      kind: "case-episode",
      label: "Election contest and executive-office transfer, 1876–1877",
      description: "The Hamburg confrontation, organized rifle clubs, disputed governorship, federal actions, and transfer of the executive office.",
      caseId: "south-carolina-reconstruction-political-membership",
      locationIds: ["south-carolina", "hamburg-south-carolina", "columbia-south-carolina", "united-states"],
      startDate: { year: 1876, month: 7, day: 8, certainty: "exact" },
      endDate: { year: 1877, month: 4, day: 11, certainty: "exact" },
      scope: "The July 8 Hamburg confrontation through the April 11 executive-office transfer; exact casualty sequence and each mechanism's causal weight remain unresolved.",
      conditionStatementIds: ["sc-house-black-majority-1868-1876", "sc-senate-black-majority-1872-1876"],
      formalRuleStatementIds: [],
      ruleInUseStatementIds: [],
      interactionStatementIds: ["sc-hamburg-red-shirt-militia-confrontation", "sc-rifle-club-organization-october-1876", "sc-rifle-club-intimidation-purpose", "sc-rifle-club-hampton-support-purpose", "sc-grant-rifle-club-disband-order", "sc-federal-reinforcement-1876", "sc-statehouse-troops-withdrawn-april-10", "sc-chamberlain-transfer-correspondence-april-10"],
      outcomeStatementIds: ["sc-hamburg-bradley-six-executions-account", "sc-hamburg-stone-five-prisoners-account", "sc-hamburg-indictments-no-trials", "sc-disputed-election-rival-governors", "sc-executive-office-transferred-april-11"],
      ...reviewed,
    },
  },

  { documentType: "entity", entity: { id: "sc-convention-adopted-constitution-event", kind: "event", label: "South Carolina convention adopted the constitution", description: "The convention adopted the proposed state constitution on March 17, 1868.", eventKindIds: ["institutional-formation"], placeIds: ["south-carolina"], startDate: { year: 1868, month: 3, day: 17, certainty: "exact" }, descriptionStatementIds: ["sc-convention-adopted-constitution"], ...reviewed } },
  { documentType: "entity", entity: { id: "sc-elector-ratification-event", kind: "event", label: "South Carolina electors ratified the constitution", description: "The three-day elector vote certified as ratifying the constitution.", eventKindIds: ["institutional-formation"], placeIds: ["south-carolina"], startDate: { year: 1868, month: 4, day: 14, certainty: "exact" }, endDate: { year: 1868, month: 4, day: 16, certainty: "exact" }, descriptionStatementIds: ["sc-electors-ratified-constitution"], ...reviewed } },
  { documentType: "entity", entity: { id: "sc-congressional-admission-event", kind: "event", label: "Congress admitted South Carolina to representation", description: "Congress overrode the veto of conditional admission legislation on June 25, 1868.", eventKindIds: ["institutional-formation"], placeIds: ["south-carolina", "united-states"], startDate: { year: 1868, month: 6, day: 25, certainty: "exact" }, descriptionStatementIds: ["sc-congress-admitted-representation"], ...reviewed } },
  { documentType: "entity", entity: { id: "sc-habeas-suspension-event", kind: "event", label: "Grant suspended habeas corpus in South Carolina counties", description: "The October 1871 federal suspension in upcountry counties described by the FJC.", eventKindIds: ["institutional-reorganization"], placeIds: ["south-carolina-upcountry", "south-carolina", "united-states"], startDate: { year: 1871, month: 10, certainty: "exact" }, descriptionStatementIds: ["sc-grant-habeas-suspension-october-1871"], ...reviewed } },
  { documentType: "entity", entity: { id: "sc-hamburg-confrontation-event", kind: "event", label: "Hamburg confrontation", description: "The July 8 confrontation and demand for the Black militia company's weapons; later overnight casualty accounts remain in the broader Episode.", eventKindIds: ["political-coercion"], placeIds: ["hamburg-south-carolina", "south-carolina"], startDate: { year: 1876, month: 7, day: 8, certainty: "exact" }, descriptionStatementIds: ["sc-hamburg-red-shirt-militia-confrontation"], ...reviewed } },
  { documentType: "entity", entity: { id: "sc-rifle-club-disband-order-event", kind: "event", label: "Grant ordered South Carolina rifle clubs to disband", description: "The October 17, 1876 federal order directing the rifle clubs to disband within three days.", eventKindIds: ["institutional-reorganization"], placeIds: ["south-carolina", "united-states"], startDate: { year: 1876, month: 10, day: 17, certainty: "exact" }, descriptionStatementIds: ["sc-grant-rifle-club-disband-order"], ...reviewed } },
  { documentType: "entity", entity: { id: "sc-statehouse-troop-withdrawal-event", kind: "event", label: "Federal troops left the South Carolina State House", description: "Federal troops withdrew from the State House at noon on April 10, 1877.", eventKindIds: ["institutional-reorganization"], placeIds: ["columbia-south-carolina", "south-carolina", "united-states"], startDate: { year: 1877, month: 4, day: 10, certainty: "exact" }, descriptionStatementIds: ["sc-statehouse-troops-withdrawn-april-10"], ...reviewed } },
  { documentType: "entity", entity: { id: "sc-executive-office-transfer-event", kind: "event", label: "South Carolina executive office transferred", description: "The formal transfer of the executive chamber, records, and papers at noon on April 11, 1877.", eventKindIds: ["institutional-reorganization"], placeIds: ["columbia-south-carolina", "south-carolina"], startDate: { year: 1877, month: 4, day: 11, certainty: "exact" }, descriptionStatementIds: ["sc-executive-office-transferred-april-11"], ...reviewed } },
] satisfies AuthoringDocument[];
