import type { AuthoringDocument } from "../../../src/lib/domain";

const reviewed = { publicationStatus: "reviewed" as const };

export const evidenceDocuments = [
  { documentType: "entity", entity: { id: "sweden", kind: "place", label: "Sweden", description: "The geographic and political setting for this bounded case.", placeType: "country", externalRefs: [{ system: "wikipedia", url: "https://en.wikipedia.org/wiki/Sweden", purpose: "orientation", language: "en", checkedAt: "2026-09-04" }, { system: "wikidata", id: "Q34", url: "https://www.wikidata.org/wiki/Q34", purpose: "identity", match: "exact", checkedAt: "2026-09-04" }], ...reviewed } },

  { documentType: "entity", entity: { id: "swedish-wage-earner-funds-work", kind: "work", label: "Proposition 1983/84:50 on wage-earner funds", description: "The Swedish government's legislative proposition establishing the enacted fund design.", title: "Proposition 1983/84:50 om löntagarfonder", workType: "law", originalPublicationYear: 1983, ...reviewed } },
  { documentType: "entity", entity: { id: "swedish-wage-earner-funds-proposition", kind: "source", label: "Proposition 1983/84:50", description: "The official online manifestation consulted for the enacted fund design.", title: "Proposition 1983/84:50 om löntagarfonder", sourceType: "legal-text", workId: "swedish-wage-earner-funds-work", contributorDisplay: ["Swedish Government"], publicationYear: 1983, resourceLinks: [{ purpose: "authorized-reading", url: "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/proposition/om-lontagarfonder_g70350/html/", label: "Read at the Swedish Parliament" }], ...reviewed } },
  { documentType: "entity", entity: { id: "westerberg-marxist-venture-work", kind: "work", label: "From Marxist Venture to Venture Capitalists", description: "A historical study of Sweden's wage-earner funds and their later institutional legacy.", title: "From Marxist Venture to Venture Capitalists", workType: "article", originalPublicationYear: 2023, ...reviewed } },
  { documentType: "entity", entity: { id: "westerberg-marxist-venture-source", kind: "source", label: "From Marxist Venture to Venture Capitalists (2023)", description: "The journal article manifestation used for evidence about fund practice and holdings.", title: "From Marxist Venture to Venture Capitalists", sourceType: "article", workId: "westerberg-marxist-venture-work", contributorDisplay: ["Rikard Westerberg"], publicationYear: 2023, identifiers: { doi: "10.1017/eso.2022.23" }, resourceLinks: [{ purpose: "publisher", url: "https://doi.org/10.1017/eso.2022.23", label: "Publisher record" }], ...reviewed } },
  { documentType: "entity", entity: { id: "pontusson-kuruvilla-economic-democracy-work", kind: "work", label: "Swedish Wage-Earner Funds: An Experiment in Economic Democracy", description: "A peer-reviewed assessment of the enacted funds' financial performance and limited effects on wage solidarity and worker influence.", title: "Swedish Wage-Earner Funds: An Experiment in Economic Democracy", workType: "article", originalPublicationYear: 1992, ...reviewed } },
  { documentType: "entity", entity: { id: "pontusson-kuruvilla-economic-democracy-source", kind: "source", label: "Swedish Wage-Earner Funds: An Experiment in Economic Democracy (1992)", description: "The journal article manifestation used to qualify the funds' relationship to economic democracy.", title: "Swedish Wage-Earner Funds: An Experiment in Economic Democracy", sourceType: "article", workId: "pontusson-kuruvilla-economic-democracy-work", contributorDisplay: ["Jonas Pontusson", "Sarosh Kuruvilla"], publicationYear: 1992, identifiers: { doi: "10.1177/001979399204500412" }, resourceLinks: [{ purpose: "publisher", url: "https://doi.org/10.1177/001979399204500412", label: "Publisher record" }], ...reviewed } },
  { documentType: "entity", entity: { id: "abolition-wage-earner-funds-work", kind: "work", label: "Proposition 1991/92:36 on abolishing wage-earner funds", description: "The Swedish government's legislative proposition abolishing the fund boards.", title: "Proposition 1991/92:36 om avveckling av löntagarfonderna", workType: "law", originalPublicationYear: 1991, ...reviewed } },
  { documentType: "entity", entity: { id: "abolition-wage-earner-funds-proposition", kind: "source", label: "Proposition 1991/92:36", description: "The official online manifestation consulted for the abolition decision.", title: "Proposition 1991/92:36 om avveckling av löntagarfonderna", sourceType: "legal-text", workId: "abolition-wage-earner-funds-work", contributorDisplay: ["Swedish Government"], publicationYear: 1991, resourceLinks: [{ purpose: "authorized-reading", url: "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/proposition/om-avveckling-av-lontagarfonderna_gf0336/html/", label: "Read at the Swedish Parliament" }], ...reviewed } },

  { documentType: "entity", entity: { id: "funds-declared-ends", kind: "statement", label: "Declared ends of the enacted funds", description: "A sourced attribution of the enacted proposal's stated purposes.", statementKind: "attributed-value", text: "The enacted proposal sought more even wealth distribution and greater wage-earner influence through co-ownership while also supporting pensions and capital formation.", ...reviewed } },
  { documentType: "entity", entity: { id: "funds-statutory-design", kind: "statement", label: "Statutory fund-board design", description: "A sourced observation about the enacted institutional form.", statementKind: "observation", text: "Five government-appointed AP-system boards invested payroll- and profit-tax receipts under statutory funding, ownership, and listed-company voting caps.", ...reviewed } },
  { documentType: "entity", entity: { id: "funds-practice", kind: "statement", label: "Fund-board practice", description: "A sourced observation about rules-in-use.", statementKind: "observation", text: "The funds generally acted as diversified long-term investors and did not pool holdings or seek company-board control.", ...reviewed } },
  { documentType: "entity", entity: { id: "funds-limited-control", kind: "statement", label: "Limited ownership and control", description: "A sourced observation about holdings and control by the end of the case period.", statementKind: "observation", text: "By 1991 the funds held about 2.6 percent of exchange value and never became controlling owners.", ...reviewed } },
  { documentType: "entity", entity: { id: "funds-abolished", kind: "statement", label: "Fund-board abolition", description: "A sourced observation about the end of the enacted arrangement.", statementKind: "observation", text: "The incoming center-right government abolished the boards at the turn of 1991–1992.", ...reviewed } },
  { documentType: "entity", entity: { id: "funds-partial-instantiation", kind: "statement", label: "Partial social-democratic instantiation", description: "A qualified classification of the case and approach.", statementKind: "classification", text: "The enacted compromise pursued several social-democratic aims but materially constrained the ownership-transfer mechanism, so it is a partial and contested instantiation rather than an embodiment of social democracy.", ...reviewed } },
  { documentType: "entity", entity: { id: "swedish-funds-socialism-transfer-limit", kind: "statement", label: "Swedish fund evidence does not generalize to socialism", description: "A transfer boundary from one enacted Swedish program to a broad and internally diverse concept.", statementKind: "editorial-interpretation", text: "Evidence about five Swedish fund boards operating from 1984 through 1991 cannot establish how socialist institutions would work in other places or show that this contested social-democratic program represents socialism broadly.", ...reviewed } },
  { documentType: "entity", entity: { id: "funds-related-ideas-classification", kind: "statement", label: "Qualified relationship to neighboring ideas", description: "A qualified classification separating useful analytical connections from claims of full realization.", statementKind: "classification", text: "The enacted funds pursued collective ownership and wage-earner influence through investments in a continuing market economy, connecting them to economic democracy, social ownership, and market-socialist thought without fully realizing any one of those broad concepts.", ...reviewed } },
  { documentType: "entity", entity: { id: "funds-distribution-assessment", kind: "statement", label: "Distribution assessment", description: "A criterion-specific interpretation of the available evidence.", statementKind: "editorial-interpretation", text: "The arrangement created collective capital holdings, but the evidence shown here does not establish a comparable transfer of controlling ownership or a broad reduction in private wealth concentration.", ...reviewed } },
  { documentType: "entity", entity: { id: "funds-accountability-assessment", kind: "statement", label: "Accountability assessment", description: "A criterion-specific interpretation of delegated authority.", statementKind: "editorial-interpretation", text: "Appointed and statutorily capped boards created investment capacity while leaving distinct questions about wage-earner representation, contestability, and electoral durability.", ...reviewed } },

  { documentType: "entity", entity: { id: "swedish-wage-earner-funds", kind: "case", label: "Swedish wage-earner funds", description: "Sweden's short-lived experiment with collectively financed investment funds intended to spread ownership and give wage earners greater influence over capital.", externalRefs: [{ system: "wikipedia", url: "https://en.wikipedia.org/wiki/Employee_funds", purpose: "orientation", language: "en", checkedAt: "2026-09-04" }], locationIds: ["sweden"], startDate: { year: 1983, certainty: "exact" }, endDate: { year: 1992, certainty: "approximate", note: "The abolition legislation and transfer process span the turn of 1991–1992." }, scope: "The five enacted AP-system wage-earner fund boards from legislative adoption through abolition; excludes treating the earlier Meidner proposals or later successor foundations as the same institutional arrangement.", selectionRationale: "A compact case that exposes the differences among attributed Ends, formal Means, rules-in-use, outcomes, and rival evaluations.", conditionStatementIds: [], episodeIds: ["enacted-wage-earner-funds-1984-1991", "liquidation-board-period-1992"], ...reviewed } },
  { documentType: "entity", entity: { id: "enacted-wage-earner-funds-1984-1991", kind: "case-episode", label: "Enacted fund-board period, 1984–1991", description: "The operating period of the five enacted regional wage-earner fund boards.", caseId: "swedish-wage-earner-funds", locationIds: ["sweden"], startDate: { year: 1984, certainty: "exact" }, endDate: { year: 1991, certainty: "exact" }, scope: "Revenue collection and investment by the five statutory boards through the abolition decision.", conditionStatementIds: [], formalRuleStatementIds: ["funds-statutory-design"], ruleInUseStatementIds: ["funds-practice"], interactionStatementIds: [], outcomeStatementIds: ["funds-limited-control", "funds-abolished"], ...reviewed } },
  { documentType: "entity", entity: { id: "liquidation-board-period-1992", kind: "case-episode", label: "Liquidation-board period, 1992", description: "The successor interval after the five wage-earner fund boards ceased and their assets moved into liquidation administration.", caseId: "swedish-wage-earner-funds", locationIds: ["sweden"], startDate: { year: 1992, certainty: "exact" }, endDate: { year: 1992, certainty: "exact" }, scope: "The immediate institutional configuration after the five boards ended; excludes the later distribution and institutional histories of all successor assets.", conditionStatementIds: [], formalRuleStatementIds: ["funds-abolished"], ruleInUseStatementIds: [], interactionStatementIds: [], outcomeStatementIds: [], ...reviewed } },
  { documentType: "entity", entity: { id: "wage-earner-fund-board-abolition", kind: "event", label: "Wage-earner fund boards abolished", description: "The statutory end of the five wage-earner fund boards at the 1991–1992 year boundary.", eventKindIds: ["institutional-abolition"], placeIds: ["sweden"], startDate: { year: 1992, month: 1, day: 1, certainty: "approximate", note: "The legislation proposed a January 1 boundary, while residual reporting, accounting, and audit duties continued during 1992." }, descriptionStatementIds: ["funds-abolished"], ...reviewed } },
  { documentType: "entity", entity: { id: "wage-earner-funds-to-liquidation", kind: "transition", label: "From wage-earner fund boards to liquidation administration", description: "A sourced institutional boundary; its political causes and longer-run significance remain contestable interpretations.", caseId: "swedish-wage-earner-funds", fromEpisodeIds: ["enacted-wage-earner-funds-1984-1991"], toEpisodeIds: ["liquidation-board-period-1992"], eventIds: ["wage-earner-fund-board-abolition"], changedRelationshipIds: ["enacted-funds-used-fund-boards"], boundaryStatus: "approximate", explanationStatementIds: ["funds-abolished"], rivalInterpretationStatementIds: ["funds-partial-instantiation"], ...reviewed } },
] satisfies AuthoringDocument[];
