import type { AuthoringDocument } from "../../../src/lib/domain";

const reviewed = { publicationStatus: "reviewed" as const };

const source = (
  id: string,
  title: string,
  contributors: string[],
  publisher: string,
  url: string,
  workType: "article" | "book" | "constitution" | "law" | "other",
  sourceType: "article" | "edition" | "web-page",
  year?: number,
  manifestationTitle?: string,
  consultedDescription?: string,
): AuthoringDocument[] => [
  {
    documentType: "entity",
    entity: {
      id: `${id}-work`,
      kind: "work",
      label: title,
      description: `The non-fiction work underlying the cited source: ${title}.`,
      title,
      workType,
      ...(year ? { originalPublicationYear: year } : {}),
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: `${id}-source`,
      kind: "source",
      label: manifestationTitle ?? title,
      description:
        consultedDescription ??
        `The consulted ${publisher} manifestation of ${title}.`,
      title: manifestationTitle ?? title,
      sourceType,
      workId: `${id}-work`,
      contributorDisplay: contributors,
      publisher,
      ...(year ? { publicationYear: year } : {}),
      resourceLinks: [
        {
          purpose:
            sourceType === "edition" ? "authorized-reading" : "publisher",
          url,
          label: "Open the consulted source",
        },
      ],
      ...reviewed,
    },
  },
];

const statement = (
  id: string,
  label: string,
  text: string,
  statementKind:
    | "definition"
    | "observation"
    | "classification"
    | "editorial-interpretation" = "observation",
): AuthoringDocument => ({
  documentType: "entity",
  entity: {
    id,
    kind: "statement",
    label,
    description: label,
    text,
    statementKind,
    ...reviewed,
  },
});

export const theocracyEvidenceDocuments = [
  ...source(
    "huzakai-theocracy",
    "Theocracy",
    ["Avihu Zakai"],
    "Macmillan Reference USA",
    "https://avihuzakai.huji.ac.il/sites/default/files/avihuzakai/files/theocracy.pdf",
    "article",
    "edition",
    2008,
    "International Encyclopedia of the Social Sciences, 2nd edition, volume 8",
  ),
  ...source(
    "hirschl-constitutional-theocracy",
    "Constitutional Theocracy",
    ["Ran Hirschl"],
    "Harvard University Press",
    "https://www.jstor.org/stable/j.ctvjghxd5",
    "book",
    "edition",
    2010,
  ),
  ...source(
    "iran-constitution-1989",
    "Constitution of the Islamic Republic of Iran, 1989 amended text",
    ["Islamic Republic of Iran"],
    "FAOLEX",
    "https://faolex.fao.org/docs/pdf/ira127540.pdf",
    "constitution",
    "edition",
    1989,
  ),
  ...source(
    "iranica-iran-constitution",
    "Constitution of the Islamic Republic",
    ["Saïd Amir Arjomand"],
    "Encyclopaedia Iranica",
    "https://www.iranicaonline.org/articles/constitution-of-the-islamic-republic/",
    "article",
    "web-page",
    1992,
    undefined,
    "The consulted Encyclopaedia Iranica article by Saïd Amir Arjomand, published 15 December 1992 and last updated 30 June 2016.",
  ),
  ...source(
    "vatican-fundamental-law-2023",
    "Legge fondamentale dello Stato della Città del Vaticano",
    ["Francis"],
    "The Holy See",
    "https://www.vatican.va/content/francesco/it/motu_proprio/documents/20230513-legge-fond-scv.html",
    "law",
    "web-page",
    2023,
  ),
  ...source(
    "vatican-commission-amendment-2025",
    "On the Composition and Presidency of the Pontifical Commission for Vatican City State",
    ["Leo XIV"],
    "The Holy See",
    "https://www.vatican.va/content/leo-xiv/en/apost_letters/documents/20251119-il-governatorato.html",
    "law",
    "web-page",
    2025,
  ),
  ...source(
    "vatican-law-one-year",
    "One year after the entry into force of the new Fundamental Law of the Vatican City State",
    ["Governorate of Vatican City State"],
    "Vatican City State",
    "https://www.vaticanstate.va/en/news/550-one-year-after-the-entry-into-force-of-the-new-fundamental-law-of-the-vatican-city-state.html",
    "other",
    "web-page",
    2024,
  ),
  ...source(
    "holy-see-vatican-distinction",
    "The Holy See and Vatican City State",
    ["Secretariat of State"],
    "The Holy See",
    "https://www.vatican.va/roman_curia/secretariat_state/documents/informazione_generale/sp_ss_scv_info-generale_en.html",
    "other",
    "web-page",
  ),
  ...source(
    "canon-law-331",
    "Code of Canon Law, canon 331",
    ["Catholic Church"],
    "The Holy See",
    "https://www.vatican.va/archive/cod-iuris-canonici/eng/documents/cic_lib2-cann330-367_en.html",
    "law",
    "web-page",
    1983,
  ),
  ...source(
    "lateran-treaty",
    "Lateran Treaty",
    ["Holy See", "Kingdom of Italy"],
    "The Holy See",
    "https://www.vatican.va/roman_curia/secretariat_state/archivio/documents/rc_seg-st_19290211_patti-lateranensi_it.html",
    "law",
    "web-page",
    1929,
  ),
  ...source(
    "vatican-judicial-law-2020",
    "Law No. CCCLI on the Judicial System of Vatican City State",
    ["Francis"],
    "The Holy See",
    "https://www.vatican.va/content/francesco/en/motu_proprio/documents/papa-francesco-motu-proprio-20200313_legge-cccli-ordinamentogiudiziario.html",
    "law",
    "web-page",
    2020,
  ),

  statement(
    "theocracy-contested-family",
    "Theocracy names a contested family of classifications",
    "Zakai traces theocracy from a claim of divine rule to several arrangements in which religious authority is connected to government; the term does not identify one timeless institutional form.",
    "definition",
  ),
  statement(
    "theocracy-hierocracy-boundary",
    "Theocracy and rule by priests are not identical",
    "A narrow hierocratic or ecclesiocratic use requires rule by a priestly body, while broader uses of theocracy also include divine-law authority or offices that combine religious and state jurisdiction.",
    "definition",
  ),
  statement(
    "theocracy-state-religion-boundary",
    "An official religion does not by itself establish theocracy",
    "Constitutional recognition or support of a religion does not establish which institutions can make, review, execute, or enforce public law.",
    "editorial-interpretation",
  ),
  statement(
    "theocracy-religious-law-boundary",
    "Religious-law clauses do not settle governing power",
    "A clause naming religious law as a source or limit of legislation is evidence of legal authority, but theocratic classification also depends on who interprets the clause and what consequences follow.",
    "editorial-interpretation",
  ),
  statement(
    "theocracy-influence-boundary",
    "Religious influence is not institutional rule",
    "Voting, lobbying, moral advocacy, or public religious language can influence government without assigning state authority to a religious office or religious-law reviewer.",
    "editorial-interpretation",
  ),
  statement(
    "theocracy-sacred-monarchy-boundary",
    "Sacred monarchy is a separate institutional question",
    "A monarch's sacred status or claim of divine legitimation does not show whether religious officeholders or religious-law institutions govern.",
    "editorial-interpretation",
  ),
  statement(
    "theocracy-authoritarianism-boundary",
    "Theocracy and authoritarianism classify different features",
    "Theocracy concerns the institutional location or asserted source of governing authority; authoritarianism concerns constrained pluralism and limited political accountability, so neither classification follows automatically from the other.",
    "editorial-interpretation",
  ),
  statement(
    "theocracy-polemical-label-boundary",
    "Polemical use is not evidence of institutional classification",
    "Calling opponents theocratic does not establish their formal offices, legal review powers, rules-in-use, or coercive capacities.",
    "editorial-interpretation",
  ),
  statement(
    "constitutional-theocracy-hybrid",
    "Constitutional theocracy is a hybrid category",
    "Hirschl uses constitutional theocracy for systems that retain constitutional institutions while granting a single religion or its law formal status and empowering religious bodies or courts in constitutional governance.",
    "classification",
  ),
  statement(
    "iran-divine-sovereignty-principles",
    "Iran's Constitution states divine-sovereignty principles",
    "Article 2 grounds the Islamic Republic in belief in one God, divine sovereignty and legislation, revelation, and leadership, while also naming human dignity, reason, science, and public participation.",
    "observation",
  ),
  statement(
    "iran-laws-islamic-criteria",
    "Iran subjects laws to Islamic criteria",
    "Article 4 requires civil, criminal, financial, economic, administrative, cultural, military, political, and other laws and regulations to conform to Islamic criteria, with Guardian Council jurists judging conformity.",
    "observation",
  ),
  statement(
    "iran-popular-elections",
    "Iran's Constitution provides elections and referenda",
    "Article 6 states that public affairs are administered through elections and referenda, including elections for the presidency, parliament, and councils.",
    "observation",
  ),
  statement(
    "iran-separation-under-leader",
    "Iran separates branches under the Leader",
    "Article 57 assigns legislative, executive, and judicial powers to separate branches while placing them under the supervision of the absolute religious Leader.",
    "observation",
  ),
  statement(
    "iran-guardian-council-composition",
    "Iran's Guardian Council combines jurists",
    "Articles 91 and 92 establish twelve Guardian Council members: six Islamic jurists selected by the Leader and six lawyers elected by parliament from nominees of the judiciary chief.",
    "observation",
  ),
  statement(
    "iran-guardian-council-review",
    "The Guardian Council reviews legislation",
    "Articles 93 through 96 make the Guardian Council necessary to ordinary parliamentary validity and assign it review of legislation for Islamic and constitutional conformity.",
    "observation",
  ),
  statement(
    "iran-guardian-council-elections",
    "The Guardian Council supervises elections",
    "Article 99 assigns the Guardian Council supervision of elections for the Assembly of Experts, presidency, parliament, and referenda.",
    "observation",
  ),
  statement(
    "iran-leader-selection",
    "Iran's Assembly of Experts selects the Leader",
    "Articles 107 and 111 assign the elected Assembly of Experts authority to designate and, under specified conditions, dismiss the Leader.",
    "observation",
  ),
  statement(
    "iran-leader-powers",
    "Iran's Leader holds enumerated state powers",
    "Article 110 assigns the Leader powers including setting general policies, commanding the armed forces, declaring war and peace, making senior appointments, and confirming or dismissing the president under specified rules.",
    "observation",
  ),
  statement(
    "iran-expediency-council",
    "Iran's Expediency Council mediates institutional conflict",
    "Article 112 provides for an Expediency Council appointed by the Leader to address specified disputes between parliament and the Guardian Council and advise the Leader.",
    "observation",
  ),
  statement(
    "iran-hybrid-rival-reading",
    "Arjomand identifies retained institutions under religious leadership",
    "Arjomand observes that the Constitution retains popular participation and separate legislative, executive, and judicial institutions while subordinating those institutions to religious leadership and review.",
    "classification",
  ),
  statement(
    "iran-classification-qualified",
    "Iran supports a qualified constitutional-theocracy placement",
    "The amended 1989 constitutional design combines elected offices and separate branches with binding Islamic-law review and extensive powers assigned to religiously qualified institutions; this placement describes those institutions, not Islam or Shi'a traditions.",
    "editorial-interpretation",
  ),
  statement(
    "vatican-pope-sovereign",
    "The Pope holds sovereign power in Vatican City",
    "Article 1 of the 2023 Fundamental Law states that the Supreme Pontiff, sovereign of Vatican City State, possesses the fullness of governmental power, including legislative, executive, and judicial power.",
    "observation",
  ),
  statement(
    "vatican-legislative-commission",
    "The 2023 law assigned legislative power to a cardinal commission",
    "As enacted in 2023, Articles 7 and 8 assigned legislative power to the Pontifical Commission except in matters reserved to the Pope and specified a Cardinal President and other Cardinals appointed for five-year terms; the membership rule was replaced in November 2025.",
    "observation",
  ),
  statement(
    "vatican-commission-amendment",
    "A 2025 amendment replaced the commission membership rule",
    "Leo XIV's 19 November 2025 apostolic letter abrogated and replaced Article 8(1), specifying that the Pontifical Commission comprises the Cardinal and other members, including the President, appointed by the Pope for five-year terms; it entered into force on publication.",
    "observation",
  ),
  statement(
    "vatican-executive-governorate",
    "The Governorate exercises Vatican executive administration",
    "Articles 10 through 13 assign executive functions to the President of the Governorate under the law's specified structure and reporting duties.",
    "observation",
  ),
  statement(
    "vatican-judicial-name",
    "Vatican judicial power is exercised in the Pope's name",
    "Article 21 provides that judicial power is exercised in the name of the Supreme Pontiff by organs constituted under Vatican judicial law.",
    "observation",
  ),
  statement(
    "holy-see-vatican-distinct",
    "The Holy See and Vatican City are distinct",
    "The Holy See's institutional account distinguishes the sovereign subject of international law centered on the Pope and Roman Curia from Vatican City State, the territorial state created to secure that independence.",
    "observation",
  ),
  statement(
    "pope-religious-state-office",
    "One officeholder joins religious and state capacities",
    "Canon 331 describes the Roman Pontiff's supreme ecclesial office, while Vatican Fundamental Law separately identifies the same officeholder as sovereign of the state; the two jurisdictions should not be collapsed.",
    "editorial-interpretation",
  ),
  statement(
    "vatican-delegation-boundary",
    "Delegation does not divide ultimate constitutional authority",
    "The 2023 Fundamental Law delegates ordinary legislative and executive functions to state organs while reserving the Pope's plenitude of governmental power and allowing him to reserve matters.",
    "editorial-interpretation",
  ),
  statement(
    "vatican-classification-qualified",
    "Vatican City supports a papal theocracy placement",
    "Vatican City's 2023 constitutional design places ultimate legislative, executive, and judicial authority in the Pope, whose eligibility derives from a religious office, while ordinary functions are delegated to distinct state organs; the placement does not classify Catholic people or Christianity.",
    "editorial-interpretation",
  ),

  {
    documentType: "entity",
    entity: {
      id: "iran",
      kind: "place",
      label: "Iran",
      description:
        "The geographic boundary for the post-1989 Iranian constitutional case.",
      placeType: "country",
      externalRefs: [
        {
          system: "wikipedia",
          url: "https://en.wikipedia.org/wiki/Iran",
          purpose: "orientation",
          language: "en",
          checkedAt: "2026-09-06",
        },
        {
          system: "wikidata",
          id: "Q794",
          url: "https://www.wikidata.org/wiki/Q794",
          purpose: "identity",
          match: "exact",
          checkedAt: "2026-09-06",
        },
      ],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "vatican-city",
      kind: "place",
      label: "Vatican City",
      description:
        "The territorial boundary for the post-2023 Vatican constitutional case.",
      placeType: "country",
      externalRefs: [
        {
          system: "wikipedia",
          url: "https://en.wikipedia.org/wiki/Vatican_City",
          purpose: "orientation",
          language: "en",
          checkedAt: "2026-09-06",
        },
        {
          system: "wikidata",
          id: "Q237",
          url: "https://www.wikidata.org/wiki/Q237",
          purpose: "identity",
          match: "exact",
          checkedAt: "2026-09-06",
        },
      ],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "iran-constitutional-authority-1989-present",
      kind: "case",
      label: "Iran under the amended 1989 Constitution",
      description:
        "Iran's formal allocation of elected, religious-review, leadership, and branch authority under the Constitution amended in 1989, current only through the stated review date.",
      locationIds: ["iran"],
      startDate: { year: 1989, month: 7, day: 28, certainty: "exact" },
      scope:
        "The formal amended constitutional design and a bounded scholarly account of its institutional tensions; not every rule in use, later election, Iranian society, Islam, or Shi'a traditions.",
      selectionRationale:
        "Tests a constitutional-theocracy classification where elections and secularly staffed institutions coexist with religious qualification, review, and leadership powers.",
      conditionStatementIds: [
        "iran-divine-sovereignty-principles",
        "iran-popular-elections",
      ],
      episodeIds: ["iran-post-1989-constitutional-episode"],
      asOf: "2026-09-07",
      lastReviewedAt: "2026-09-07",
      freshness: "current",
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "iran-post-1989-constitutional-episode",
      kind: "case-episode",
      label: "Iranian constitutional authority after the 1989 amendment",
      description:
        "The ongoing constitutional episode beginning with approval of the 1989 amendments.",
      caseId: "iran-constitutional-authority-1989-present",
      locationIds: ["iran"],
      startDate: { year: 1989, month: 7, day: 28, certainty: "exact" },
      scope:
        "Formal constitutional allocation and a bounded scholarly account of institutional conflict, reviewed through 7 September 2026.",
      conditionStatementIds: [
        "iran-divine-sovereignty-principles",
        "iran-popular-elections",
      ],
      formalRuleStatementIds: [
        "iran-laws-islamic-criteria",
        "iran-separation-under-leader",
        "iran-guardian-council-composition",
        "iran-guardian-council-review",
        "iran-guardian-council-elections",
        "iran-leader-selection",
        "iran-leader-powers",
        "iran-expediency-council",
      ],
      ruleInUseStatementIds: [],
      interactionStatementIds: [
        "iran-hybrid-rival-reading",
        "iran-classification-qualified",
      ],
      outcomeStatementIds: [],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "vatican-city-authority-2023-present",
      kind: "case",
      label: "Vatican City under the 2023 Fundamental Law",
      description:
        "Vatican City's allocation of sovereign and delegated authority under the Fundamental Law effective 7 June 2023, current only through the stated review date.",
      locationIds: ["vatican-city"],
      startDate: { year: 2023, month: 6, day: 7, certainty: "exact" },
      scope:
        "Vatican City's formal constitutional offices under the 2023 Fundamental Law as amended through 19 November 2025; not the Holy See's entire ecclesial government, Catholicism, Christianity, or informal practice beyond the reviewed record.",
      selectionRationale:
        "Tests a theocracy classification where a religious officeholder holds plenary state power but distinct organs ordinarily exercise legislative, executive, and judicial functions.",
      conditionStatementIds: [
        "holy-see-vatican-distinct",
        "pope-religious-state-office",
      ],
      episodeIds: ["vatican-post-2023-fundamental-law-episode"],
      materialChangeEventIds: ["vatican-commission-membership-amended-2025"],
      asOf: "2026-09-07",
      lastReviewedAt: "2026-09-07",
      freshness: "current",
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "vatican-post-2023-fundamental-law-episode",
      kind: "case-episode",
      label: "Vatican authority under the 2023 Fundamental Law",
      description:
        "The ongoing episode beginning when the 2023 Fundamental Law entered into force.",
      caseId: "vatican-city-authority-2023-present",
      locationIds: ["vatican-city"],
      startDate: { year: 2023, month: 6, day: 7, certainty: "exact" },
      scope:
        "Formal authority and delegated organs under the 2023 law, including the Article 8(1) text substituted in November 2025, reviewed through 7 September 2026.",
      conditionStatementIds: [
        "holy-see-vatican-distinct",
        "pope-religious-state-office",
      ],
      formalRuleStatementIds: [
        "vatican-pope-sovereign",
        "vatican-legislative-commission",
        "vatican-commission-amendment",
        "vatican-executive-governorate",
        "vatican-judicial-name",
      ],
      ruleInUseStatementIds: [],
      interactionStatementIds: [
        "vatican-delegation-boundary",
        "vatican-classification-qualified",
      ],
      outcomeStatementIds: [],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: "vatican-commission-membership-amended-2025",
      kind: "event",
      label: "Vatican commission membership rule amended",
      description:
        "Leo XIV replaced Article 8(1) of the 2023 Fundamental Law, a material textual change recorded for case freshness without assigning causal or turning-point significance.",
      eventKindIds: ["institutional-reorganization"],
      placeIds: ["vatican-city"],
      startDate: { year: 2025, month: 11, day: 19, certainty: "exact" },
      descriptionStatementIds: ["vatican-commission-amendment"],
      ...reviewed,
    },
  },
] satisfies AuthoringDocument[];
