import type { AuthoringDocument } from "../../../src/lib/domain";

const reviewed = { publicationStatus: "reviewed" as const };

type SourceType = "article" | "edition" | "report" | "dataset";
type WorkType = "article" | "book" | "report" | "other";

const source = (
  id: string,
  title: string,
  contributors: string[],
  year: number,
  publisher: string,
  url: string,
  workType: WorkType,
  sourceType: SourceType,
  identifiers?: { doi?: string; isbn13?: string },
  purpose: "publisher" | "authorized-reading" = "publisher",
  manifestationNote?: string,
): AuthoringDocument[] => [
  {
    documentType: "entity",
    entity: {
      id: `${id}-work`,
      kind: "work",
      label: title,
      description: `The non-fiction work used to define or examine welfare-state institutions: ${title}.`,
      title,
      workType,
      originalPublicationYear: year,
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: `${id}-source`,
      kind: "source",
      label: title,
      description:
        manifestationNote ??
        `The consulted ${publisher} manifestation of ${title}.`,
      title,
      sourceType,
      workId: `${id}-work`,
      contributorDisplay: contributors,
      publicationYear: year,
      publisher,
      ...(identifiers ? { identifiers } : {}),
      resourceLinks: [{ purpose, url, label: "Open the consulted source" }],
      ...reviewed,
    },
  },
];

const statement = (
  id: string,
  label: string,
  text: string,
  statementKind:
    | "definition"
    | "observation"
    | "attributed-value"
    | "attributed-proposal"
    | "causal-hypothesis"
    | "classification"
    | "editorial-interpretation" = "observation",
): AuthoringDocument => ({
  documentType: "entity",
  entity: {
    id,
    kind: "statement",
    label,
    description: label,
    statementKind,
    text,
    ...reviewed,
  },
});

const place = (id: string, label: string): AuthoringDocument => ({
  documentType: "entity",
  entity: {
    id,
    kind: "place",
    label,
    description: `${label}, the geographic boundary used for one welfare-state case.`,
    placeType: "country",
    ...reviewed,
  },
});

const boundedCase = (
  id: string,
  episodeId: string,
  label: string,
  placeId: string,
  start: number,
  end: number,
  scope: string,
  rationale: string,
  conditionStatementIds: string[],
  formalRuleStatementIds: string[],
  interactionStatementIds: string[],
  outcomeStatementIds: string[],
): AuthoringDocument[] => [
  {
    documentType: "entity",
    entity: {
      id,
      kind: "case",
      label,
      description: scope,
      locationIds: [placeId],
      startDate: { year: start, certainty: "exact" },
      endDate: { year: end, certainty: "exact" },
      scope,
      selectionRationale: rationale,
      conditionStatementIds,
      episodeIds: [episodeId],
      ...reviewed,
    },
  },
  {
    documentType: "entity",
    entity: {
      id: episodeId,
      kind: "case-episode",
      label,
      description: scope,
      caseId: id,
      locationIds: [placeId],
      startDate: { year: start, certainty: "exact" },
      endDate: { year: end, certainty: "exact" },
      scope,
      conditionStatementIds,
      formalRuleStatementIds,
      ruleInUseStatementIds: [],
      interactionStatementIds,
      outcomeStatementIds,
      ...reviewed,
    },
  },
];

export const welfareStateEvidenceDocuments = [
  ...source(
    "briggs-historical-perspective",
    "The Welfare State in Historical Perspective",
    ["Asa Briggs"],
    1961,
    "European Journal of Sociology",
    "https://www.cambridge.org/core/journals/european-journal-of-sociology-archives-europeennes-de-sociologie/article/abs/welfare-state-in-historical-perspective/6DD16AF993288356DC154B558FCEA3CF",
    "article",
    "article",
    { doi: "10.1017/S0003975600000412" },
  ),
  ...source(
    "esping-andersen-three-worlds",
    "The Three Worlds of Welfare Capitalism",
    ["Gøsta Esping-Andersen"],
    1989,
    "Polity Press",
    "https://www.wiley-vch.de/en/areas-interest/humanities-social-sciences/social-policy-welfare-12sp/social-work-12sp3/the-three-worlds-of-welfare-capitalism-978-0-7456-0796-2",
    "book",
    "edition",
    { isbn13: "9780745607962" },
  ),
  ...source(
    "orloff-gender-social-rights",
    "Gender and the Social Rights of Citizenship: The Comparative Analysis of Gender Relations and Welfare States",
    ["Ann Shola Orloff"],
    1993,
    "American Sociological Review",
    "https://sociology.northwestern.edu/documents/faculty-docs/faculty-research-article/orloff-gender-and-the-social-rights-of-citizenship.pdf",
    "article",
    "article",
    { doi: "10.2307/2095903" },
    "authorized-reading",
  ),
  ...source(
    "daly-lewis-social-care",
    "The Concept of Social Care and the Analysis of Contemporary Welfare States",
    ["Mary Daly", "Jane Lewis"],
    2000,
    "The British Journal of Sociology",
    "https://doi.org/10.1111/j.1468-4446.2000.00281.x",
    "article",
    "article",
    { doi: "10.1111/j.1468-4446.2000.00281.x" },
  ),
  ...source(
    "barr-welfare-state-piggy-bank",
    "The Welfare State as Piggy Bank: Information, Risk, Uncertainty, and the Role of the State",
    ["Nicholas Barr"],
    2001,
    "Oxford University Press",
    "https://academic.oup.com/book/25944",
    "book",
    "edition",
    {
      doi: "10.1093/0199246599.001.0001",
      isbn13: "9780199246595",
    },
  ),
  ...source(
    "ilo-world-social-protection-2024",
    "World Social Protection Report 2024–26: Universal Social Protection for Climate Action and a Just Transition",
    ["International Labour Organization"],
    2024,
    "International Labour Organization",
    "https://webapps.ilo.org/static/english/reports/flagship/world_social_protection_report_2024-26/Annex.html",
    "report",
    "report",
    { doi: "10.54394/ZMDK5543", isbn13: "9789220404508" },
    "authorized-reading",
  ),
  ...source(
    "oecd-socx",
    "Social Expenditure Database (SOCX)",
    ["Organisation for Economic Co-operation and Development"],
    2025,
    "OECD",
    "https://www.oecd.org/en/data/datasets/social-expenditure-database-socx.html",
    "other",
    "dataset",
  ),
  ...source(
    "beveridge-social-insurance",
    "Social Insurance and Allied Services",
    ["William Beveridge"],
    1942,
    "His Majesty's Stationery Office",
    "https://revenuebenefits.org.uk/pdf/Beveridge_report_1942.pdf",
    "report",
    "report",
    undefined,
    "authorized-reading",
    "A consulted scan of the report's Part I summary, originally published by His Majesty's Stationery Office.",
  ),
  ...source(
    "uk-national-insurance-act-1946",
    "National Insurance Act 1946",
    ["Parliament of the United Kingdom"],
    1946,
    "The National Archives",
    "https://www.legislation.gov.uk/ukpga/Geo6/9-10/67/pdfs/ukpga_19460067_en.pdf",
    "other",
    "edition",
    undefined,
    "authorized-reading",
  ),
  ...source(
    "uk-nhs-act-1946",
    "National Health Service Act 1946",
    ["Parliament of the United Kingdom"],
    1946,
    "The National Archives",
    "https://www.legislation.gov.uk/ukpga/Geo6/9-10/81/pdfs/ukpga_19460081_en.pdf",
    "other",
    "edition",
    undefined,
    "authorized-reading",
  ),
  ...source(
    "uk-nhs-scotland-act-1947",
    "National Health Service (Scotland) Act 1947",
    ["Parliament of the United Kingdom"],
    1947,
    "The National Archives",
    "https://www.legislation.gov.uk/ukpga/1947/27/pdfs/ukpga_19470027_en.pdf",
    "other",
    "edition",
    undefined,
    "authorized-reading",
  ),
  ...source(
    "vargas-muiser-costa-rica-universal-coverage",
    "Promoting universal financial protection: a policy analysis of universal health coverage in Costa Rica (1940–2000)",
    ["Juan Rafael Vargas", "Jorine Muiser"],
    2013,
    "Health Research Policy and Systems",
    "https://health-policy-systems.biomedcentral.com/articles/10.1186/1478-4505-11-28",
    "article",
    "article",
    { doi: "10.1186/1478-4505-11-28" },
  ),
  ...source(
    "uk-national-assistance-act-1948",
    "National Assistance Act 1948",
    ["Parliament of the United Kingdom"],
    1948,
    "The National Archives",
    "https://www.legislation.gov.uk/ukpga/Geo6/11-12/29/pdfs/ukpga_19480029_en.pdf",
    "other",
    "edition",
    undefined,
    "authorized-reading",
  ),
  ...source(
    "saenz-costa-rica-universal-coverage",
    "Universal Coverage in a Middle Income Country: Costa Rica",
    ["María del Rocío Sáenz", "Juan Luis Bermúdez", "Mónica Acosta"],
    2010,
    "World Health Organization",
    "https://cdn.who.int/media/docs/default-source/health-financing/technical-briefs-background-papers/costaricano11.pdf?download=true&sfvrsn=473cdf6a_3",
    "report",
    "report",
    undefined,
    "authorized-reading",
  ),
  ...source(
    "kwon-developmental-welfare",
    "Transforming the Developmental Welfare State in East Asia",
    ["Huck-ju Kwon"],
    2005,
    "Development and Change",
    "https://onlinelibrary.wiley.com/doi/10.1111/j.0012-155X.2005.00420.x",
    "article",
    "article",
    { doi: "10.1111/j.0012-155X.2005.00420.x" },
  ),
  ...source(
    "ku-korea-welfare-reform",
    "Social Welfare Reform Since the 1997 Economic Crisis in Korea: Achievement, Limits, and Future Prospects",
    ["Inhoe Ku"],
    2007,
    "Asian Social Work and Policy Review",
    "https://onlinelibrary.wiley.com/doi/full/10.1111/j.1753-1411.2007.00003.x",
    "article",
    "article",
    { doi: "10.1111/j.1753-1411.2007.00003.x" },
    "authorized-reading",
  ),
  ...source(
    "oecd-korea-economic-survey-2008",
    "OECD Economic Surveys: Korea 2008",
    ["Organisation for Economic Co-operation and Development"],
    2008,
    "OECD",
    "https://www.oecd.org/content/dam/oecd/en/publications/reports/2008/12/oecd-economic-surveys-korea-2008_g1gha18e/eco_surveys-kor-2008-en.pdf",
    "report",
    "report",
    { isbn13: "9789264054257" },
    "authorized-reading",
  ),
  ...source(
    "shim-legislature-welfare",
    "The Legislature and Agenda Politics of Social Welfare: A Comparative Analysis of Authoritarian and Democratic Regimes in South Korea",
    ["Jaemin Shim"],
    2019,
    "Democratization",
    "https://www.tandfonline.com/doi/abs/10.1080/13510347.2019.1621847",
    "article",
    "article",
    { doi: "10.1080/13510347.2019.1621847" },
  ),

  {
    documentType: "entity",
    entity: {
      id: "welfare-state",
      kind: "concept",
      label: "Welfare State",
      description:
        "A disputed institutional category for state-backed arrangements that pool social risks, transfer income, regulate eligibility, or provide services.",
      schemeIds: ["political-economic-ideas"],
      alternateLabels: ["welfare state"],
      scopeNote:
        "Do not infer a welfare state from one benefit, spending total, ideology, political regime, formal entitlement, or claimed outcome.",
      ...reviewed,
    },
  },

  statement(
    "welfare-state-institutional-category",
    "Welfare State is an institutional category",
    "Welfare State names a disputed institutional category in which public authority alters exposure to market and life-course risks through income guarantees, social insurance, assistance, services, regulation, or financing.",
    "definition",
  ),
  statement(
    "welfare-regime-analytical-category",
    "Welfare regime is an analytical category",
    "A welfare-regime typology classifies recurring relationships among states, markets, households, employers, and voluntary organizations; it is not a political regime type or a name for one program.",
    "definition",
  ),
  statement(
    "social-protection-category-boundary",
    "Social protection has variable scope",
    "The ILO uses social protection and social security for policies and programs addressing poverty, exclusion, health care, and specified life-course risks, while noting that other uses may include family or community provision or may narrow the term to poverty relief.",
    "definition",
  ),
  statement(
    "public-spending-insufficient",
    "Public spending is insufficient",
    "A spending total cannot by itself establish a welfare state's design, coverage, adequacy, delivery, or distribution because comparable accounts can include public, mandatory private, and voluntary private programs with different eligibility rules.",
    "editorial-interpretation",
  ),
  statement(
    "welfare-political-regime-boundary",
    "Welfare provision does not establish a political regime",
    "Social provision can operate under democratic or authoritarian rule, so welfare institutions do not by themselves establish Democracy or political accountability.",
    "editorial-interpretation",
  ),
  statement(
    "welfare-economic-order-boundary",
    "Welfare provision does not establish an economic order",
    "Welfare institutions do not by themselves establish social ownership, Capitalism, Socialism, or Social Democracy; welfare-state arrangements can retain substantial private ownership and market allocation.",
    "editorial-interpretation",
  ),
  statement(
    "welfare-outcome-boundary",
    "Institutions do not determine outcomes by label",
    "A formal benefit or service does not by itself establish effective access, adequate support, redistribution, equality, autonomy, or improved health.",
    "editorial-interpretation",
  ),
  statement(
    "welfare-design-facets",
    "Welfare design has separable facets",
    "Eligibility, financing, administration, delivery, coverage, benefit level, enforcement, appeals, and actual access are separate features that must be investigated rather than inferred from a program name.",
    "editorial-interpretation",
  ),
  statement(
    "welfare-benefit-forms",
    "Benefit forms distribute access differently",
    "Social protection programs may be universal or categorical, contributory, means-tested, tax-financed, employment-linked, or conditional, and several forms commonly coexist within one system.",
    "definition",
  ),
  statement(
    "social-insurance-assistance-boundary",
    "Social insurance and social assistance use different conditions",
    "Social insurance generally pools contributions against specified risks, while social assistance is usually non-contributory and conditions eligibility on a means test or another measure of need.",
    "definition",
  ),
  statement(
    "universal-categorical-boundary",
    "Universal and categorical coverage are distinct",
    "In the ILO glossary, universal benefits require only residence, while categorical benefits cover a broad population category without a means test; either may be financed without individual contributions.",
    "definition",
  ),
  statement(
    "welfare-mixed-provision",
    "Provision extends beyond direct state delivery",
    "The ILO distinguishes public responsibility for social security from delivery, which may involve public institutions, private entities, occupational plans, mutual organizations, community arrangements, or self-help institutions.",
    "definition",
  ),
  statement(
    "welfare-provider-boundaries",
    "Public, occupational, family, and mutual provision are distinct",
    "A publicly financed or delivered service, an employment-linked occupational benefit, family provision, mutual aid, employer provision, and community self-help use different authorities and eligibility relationships even when they address similar risks.",
    "definition",
  ),
  statement(
    "esping-welfare-regime-typology",
    "Esping-Andersen proposed three welfare regimes",
    "Esping-Andersen's influential typology compares liberal, conservative-corporatist, and social-democratic welfare-capitalist regimes through decommodification, stratification, and state-market relations.",
    "classification",
  ),
  statement(
    "esping-typology-boundary",
    "The three-regime typology has a bounded sample",
    "Esping-Andersen developed the three-regime comparison for advanced Western capitalist societies, so it cannot serve as a universal inventory of welfare institutions.",
    "editorial-interpretation",
  ),
  statement(
    "care-social-reproduction-boundary",
    "Care and social reproduction alter welfare comparisons",
    "Orloff argues that welfare analysis must examine paid and unpaid work, household dependence, access to employment, and the capacity to maintain an autonomous household rather than treating a male wage earner as the universal claimant.",
    "classification",
  ),
  statement(
    "esping-decommodification-purpose",
    "Decommodification reduces reliance on markets",
    "Esping-Andersen uses decommodification for social rights that allow people to maintain a livelihood without relying entirely on market participation.",
    "classification",
  ),
  statement(
    "orloff-decommodification-limit",
    "Care and household dependence limit decommodification measures",
    "Orloff argues that decommodification measures built around market dependence must be supplemented by access to paid work and the capacity to maintain an autonomous household because unpaid care and gendered dependence alter their effects.",
    "classification",
  ),
  statement(
    "social-care-welfare-mix",
    "Social care crosses institutional sectors",
    "Daly and Lewis place care at the intersection of state, market, family, and voluntary-sector relations, joining cash, services, labor, and relationships that program-by-program accounts can separate.",
    "classification",
  ),
  statement(
    "welfare-attributed-purposes",
    "Welfare institutions have multiple attributed purposes",
    "Researchers and public bodies attribute social provision to risk pooling, consumption smoothing, poverty relief, redistribution, labor-force participation, social investment, political incorporation, legitimation, or social control; the institutional label does not decide among these purposes.",
    "editorial-interpretation",
  ),

  statement(
    "beveridge-proposal-boundary",
    "Beveridge proposed a coordinated program",
    "Beveridge's 1942 report proposed a coordinated social-insurance plan with allied policies; it was a proposal and did not itself enact the postwar institutions later associated with it.",
    "attributed-proposal",
  ),
  statement(
    "beveridge-population-policy",
    "Beveridge linked family support to population policy",
    "Beveridge argued in 1942 that Britain's low reproduction rate made spending on childhood and maternity a priority within his proposed social-insurance plan.",
    "attributed-proposal",
  ),
  statement(
    "uk-national-insurance-formal-rule",
    "Britain enacted national insurance",
    "The National Insurance Act 1946 established contributory insurance covering specified interruptions of earnings and other contingencies under statutory eligibility and contribution rules.",
    "observation",
  ),
  statement(
    "uk-nhs-formal-rule",
    "England and Wales enacted a comprehensive health service",
    "The National Health Service Act 1946 placed a duty on the health minister to promote a comprehensive service in England and Wales and authorized hospital, medical, nursing, and related services.",
    "observation",
  ),
  statement(
    "uk-nhs-scotland-formal-rule",
    "Scotland enacted a comprehensive health service",
    "The National Health Service (Scotland) Act 1947 placed a corresponding duty on the Secretary of State to promote a comprehensive health service in Scotland.",
    "observation",
  ),
  statement(
    "uk-assistance-formal-rule",
    "Britain enacted national assistance",
    "The National Assistance Act 1948 created a means-tested assistance structure, abolished the former poor-law machinery, and provided administration and appeal rules distinct from contributory insurance.",
    "observation",
  ),
  statement(
    "britain-welfare-case-limit",
    "The British case is a formation period",
    "The 1942–1951 British sequence shows proposal, enactment, and institutional assembly; it does not establish uniform access, outcomes, one coherent ideology, or a model followed elsewhere.",
    "editorial-interpretation",
  ),

  statement(
    "costa-rica-ccss-formation",
    "Costa Rica created the CCSS",
    "Costa Rica's 1941 legislation created the Caja Costarricense de Seguro Social and began a social-insurance institution whose early coverage was narrower than its later mandate.",
    "observation",
  ),
  statement(
    "costa-rica-universalization-mandate",
    "Costa Rica adopted a universalization mandate",
    "The 1961 Social Security Universalization Act instructed the CCSS to extend social insurance to the whole population within ten years, establishing a formal direction rather than immediate complete access.",
    "observation",
  ),
  statement(
    "costa-rica-1973-hospital-transfer",
    "Costa Rica transferred public hospitals to the CCSS",
    "The 1973 Hospital Transfer Act directed the transfer of the non-CCSS hospital network, including hospitals owned and managed by the Social Protection Board, to the CCSS, a process implemented gradually over the following decade.",
    "observation",
  ),
  statement(
    "costa-rica-1973-health-right",
    "Costa Rica recognized a right to health promotion",
    "Costa Rica's 1973 General Health Law stated that population health is a matter of public interest and recognized residents' right to state action promoting health.",
    "observation",
  ),
  statement(
    "costa-rica-financing-access",
    "Costa Rican health coverage mixed financing and access",
    "The Costa Rican system combined worker, employer, and state contributions with integrated services, while measured insurance coverage and practical access remained distinct from the universal legal commitment.",
    "observation",
  ),
  statement(
    "costa-rica-welfare-case-limit",
    "The Costa Rican case concerns incremental health institutions",
    "The 1941–1973 sequence concerns the formation and staged expansion of social insurance and health administration; it does not represent every Costa Rican welfare institution or prove a general regional model.",
    "editorial-interpretation",
  ),

  statement(
    "korea-democratization-expansion",
    "Korean social programs expanded after democratization",
    "South Korea implemented major programs including the national pension and employment insurance after democratization, but coverage initially remained concentrated among regular workers and larger firms.",
    "observation",
  ),
  statement(
    "korea-labor-discipline-purpose",
    "Korean protection was linked to labor discipline",
    "Ku describes authoritarian governments seeking labor peace through union suppression while employment and social-security protections remained concentrated among regular workers in large firms.",
    "observation",
  ),
  statement(
    "korea-crisis-coverage-gap",
    "The 1997 crisis exposed coverage gaps",
    "Mass unemployment during the 1997 financial crisis exposed the inability of employment-linked protection to reach many unemployed people and their families.",
    "observation",
  ),
  statement(
    "korea-employment-insurance-expansion",
    "Korea widened employment insurance",
    "In 1998 South Korea accelerated employment-insurance expansion from firms with at least thirty workers to firms with at least one worker and eased benefit eligibility, while coverage remained incomplete.",
    "observation",
  ),
  statement(
    "korea-public-works-response",
    "Korea used public works after the crisis",
    "South Korea's post-crisis response included temporary public-works jobs for unemployed people who were not protected by employment insurance.",
    "observation",
  ),
  statement(
    "korea-assistance-response",
    "Korea temporarily expanded public assistance",
    "South Korea temporarily widened livelihood protection and cash assistance after the 1997 crisis to reach some people outside employment insurance.",
    "observation",
  ),
  statement(
    "korea-2008-coverage-gap",
    "The OECD reported Korean social-insurance coverage gaps in 2008",
    "The OECD's 2008 survey reported that non-regular workers and workers in small firms remained less likely to be insured and that only about one-third of unemployed people received employment benefits.",
    "observation",
  ),
  statement(
    "korea-reform-outcome-limit",
    "Expansion did not reverse every distributional trend",
    "Ku reports that post-crisis welfare expansion coexisted with higher measured income inequality and relative poverty than before the crisis, so institutional expansion cannot be treated as proof of equal outcomes.",
    "observation",
  ),
  statement(
    "korea-authoritarian-democratic-boundary",
    "Korean welfare politics crossed regime periods",
    "Shim analyzes social-welfare bills across authoritarian and democratic periods and finds that welfare priority rises continuously with higher levels of democracy, cautioning against a simple regime binary.",
    "observation",
  ),
  statement(
    "korea-selective-political-provision",
    "Korean welfare bills targeted protected groups",
    "Shim identifies authoritarian-period welfare initiatives directed to groups including the military, teachers, politicians, and civil servants, showing that provision can be selective within a political settlement.",
    "observation",
  ),
  statement(
    "south-korea-welfare-case-limit",
    "The Korean case is a bounded expansion sequence",
    "The 1988–2008 Korean sequence shows democratization, crisis, and institutional expansion under changing conditions; it does not establish that democracy alone caused reform or that formal expansion produced universal access.",
    "editorial-interpretation",
  ),

  place("britain-welfare-state-case-place", "Great Britain"),
  place("costa-rica-welfare-state-case-place", "Costa Rica"),
  place("south-korea-welfare-state-case-place", "South Korea"),
  ...boundedCase(
    "britain-welfare-state-formation-1942-1951",
    "britain-welfare-state-formation-episode",
    "British social-policy formation, 1942–1951",
    "britain-welfare-state-case-place",
    1942,
    1951,
    "Beveridge's proposal and the enactment of national insurance, national assistance, and National Health Service statutes for England and Wales and for Scotland from 1942 through 1951.",
    "Separates a prominent proposal from several enacted institutions during a bounded formation period.",
    ["beveridge-proposal-boundary"],
    [
      "uk-national-insurance-formal-rule",
      "uk-nhs-formal-rule",
      "uk-nhs-scotland-formal-rule",
      "uk-assistance-formal-rule",
    ],
    [],
    [],
  ),
  ...boundedCase(
    "costa-rica-social-insurance-health-1941-1973",
    "costa-rica-social-insurance-health-episode",
    "Costa Rican social-insurance and health expansion, 1941–1973",
    "costa-rica-welfare-state-case-place",
    1941,
    1973,
    "CCSS formation, the universalization mandate, and the 1973 Hospital Transfer and General Health laws in Costa Rica.",
    "Tests staged universalization outside the European cases that shaped prominent welfare-regime typologies.",
    ["costa-rica-ccss-formation"],
    [
      "costa-rica-universalization-mandate",
      "costa-rica-1973-hospital-transfer",
      "costa-rica-1973-health-right",
    ],
    ["costa-rica-financing-access"],
    [],
  ),
  ...boundedCase(
    "south-korea-welfare-expansion-1988-2008",
    "south-korea-welfare-expansion-episode",
    "South Korean welfare expansion, 1988–2008",
    "south-korea-welfare-state-case-place",
    1988,
    2008,
    "Social-policy expansion after democratization and the 1997 financial crisis, with employment and distributional limits, in South Korea from 1988 through 2008.",
    "Tests changing welfare institutions across democratic transition and crisis without making regime type a sufficient cause.",
    ["korea-democratization-expansion", "korea-crisis-coverage-gap"],
    ["korea-employment-insurance-expansion"],
    [
      "korea-public-works-response",
      "korea-assistance-response",
      "korea-2008-coverage-gap",
    ],
    ["korea-reform-outcome-limit"],
  ),
] satisfies AuthoringDocument[];
