import type { AuthoringDocument, Dossier } from "../../../src/lib/domain";
import { attachNarrative } from "./load-narrative";

const dossier = attachNarrative("matriliny-property-authority.md", {
  id: "matriliny-property-authority-dossier",
  kind: "dossier" as const,
  label: "Matriliny, property, and authority",
  description:
    "Maternal descent does not by itself determine property control, management, office, or equality.",
  subject: { kind: "concept" as const, id: "matriliny" },
  standfirst: "",
  standfirstStatementIds: [
    "matriliny-maternal-descent-definition",
    "matriliny-does-not-fix-residence",
    "matriliny-does-not-fix-property-control",
    "matriliny-does-not-fix-office",
    "matriliny-does-not-fix-equality",
  ],
  sections: [
    {
      id: "how-do-the-terms-differ",
      heading: "How do matriliny, matrilocality, and matriarchy differ?",
      body: "",
      traceStatus: "qualified",
      statementIds: [
        "matriliny-maternal-descent-definition",
        "matrilocality-residence-distinction",
        "matriliny-does-not-fix-residence",
        "matriliny-does-not-fix-property-control",
        "matriliny-does-not-fix-office",
        "matriliny-does-not-fix-equality",
        "matriarchy-rule-by-women-dispute",
        "matriarchy-sanday-maternal-centered-interpretation",
      ],
      relatedEntityRefs: [
        { kind: "concept", id: "matrilocality" },
        { kind: "concept", id: "matriarchy" },
      ],
    },
    {
      id: "what-counts-as-power",
      heading: "Can formal office tell us who has power?",
      body: "",
      traceStatus: "qualified",
      statementIds: [
        "minangkabau-power-varies-by-relation",
        "bonjol-ulayat-formal-distinction",
        "bonjol-harta-pusaka-transition",
      ],
    },
    {
      id: "how-are-local-terms-used",
      heading: "What do the retained local terms mean here?",
      body: "",
      traceStatus: "qualified",
      statementIds: [
        "adat-translation-boundary",
        "nagari-translation-boundary",
        "minangkabau-legal-orders-interact",
        "minangkabau-ancestral-acquired-property-distinction",
        "bonjol-ulayat-formal-distinction",
        "bonjol-harta-pusaka-transition",
        "bonjol-bundo-kanduang-role",
      ],
    },
    {
      id: "what-can-koto-tinggi-show",
      heading: "What can Koto Tinggi show about public authority?",
      body: "",
      traceStatus: "qualified",
      statementIds: [
        "koto-tinggi-fieldwork-scope",
        "koto-tinggi-participant-count-unreported",
        "koto-tinggi-womens-voice-unidentified",
        "koto-tinggi-descent-unobserved",
        "koto-tinggi-residence-unobserved",
        "koto-tinggi-minangkabau-adat-context",
        "koto-tinggi-three-institutions",
        "koto-tinggi-representative-council",
        "koto-tinggi-customary-council",
        "koto-tinggi-formal-participation-rules",
        "koto-tinggi-formal-decision-rule",
        "koto-tinggi-formal-speaking-rule",
        "koto-tinggi-formal-consensus-rule",
        "koto-tinggi-formal-vote-fallback",
        "koto-tinggi-customary-council-contestation",
        "koto-tinggi-budget-rules-in-use",
        "koto-tinggi-budget-postponement",
        "koto-tinggi-budget-consensus",
        "koto-tinggi-administrative-capacity-limit",
        "koto-tinggi-regulatory-preparation-limit",
      ],
      relatedEntityRefs: [
        { kind: "case", id: "koto-tinggi-post-decentralization-governance" },
        {
          kind: "case-episode",
          id: "koto-tinggi-governance-october-2016",
        },
      ],
    },
    {
      id: "what-can-bonjol-show",
      heading: "What can Bonjol show about inheritance and control?",
      body: "",
      traceStatus: "qualified",
      statementIds: [
        "bonjol-study-method-and-voice",
        "bonjol-ulayat-formal-distinction",
        "bonjol-ulayat-delegated-management",
        "bonjol-harta-pusaka-transition",
        "bonjol-harta-pusaka-female-line",
        "bonjol-inheritance-did-not-confer-office-authority",
        "bonjol-bundo-kanduang-role",
        "bonjol-bundo-kanduang-not-universal-authority",
        "bonjol-ulayat-sales-rules-in-use",
        "bonjol-neshp-formal-promise",
        "bonjol-neshp-distribution-practice",
        "bonjol-neshp-exclusion-outcome",
        "bonjol-women-testimony-limit",
        "bonjol-five-women-testimony",
        "bonjol-five-women-weak-influence",
        "bonjol-authors-causal-interpretation",
        "bonjol-authors-early-marriage-hypothesis",
        "bonjol-authors-gender-norms-hypothesis",
        "bonjol-authors-forum-hypothesis",
        "bonjol-authors-representation-dependence-hypothesis",
        "bonjol-causal-identification-limit",
      ],
      relatedEntityRefs: [
        { kind: "case", id: "bonjol-melayu-ulayat-governance" },
        { kind: "case-episode", id: "bonjol-ulayat-governance-2000-2016" },
      ],
    },
    {
      id: "why-cant-the-cases-be-generalized",
      heading: "Why can’t these cases stand for all Minangkabau communities?",
      body: "",
      traceStatus: "qualified",
      statementIds: [
        "koto-tinggi-fieldwork-scope",
        "bonjol-study-method-and-voice",
        "bonjol-new-nagari-forest-transition",
        "bonjol-no-minangkabau-generalization",
        "minangkabau-practices-historically-changing",
        "nagari-law-changed-after-cases",
      ],
    },
  ],
  publicationStatus: "reviewed",
  reviewedAt: "2026-09-06",
} satisfies Dossier);

export const minangkabauDossierDocuments = [
  { documentType: "entity", entity: dossier },
] satisfies AuthoringDocument[];
