import type { AuthoringDocument } from "../../../src/lib/domain";
import { attachNarrative } from "./load-narrative";

export const southCarolinaReconstructionDossierDocuments = [
  {
    documentType: "entity",
    entity: attachNarrative("south-carolina-reconstruction.md", {
      id: "south-carolina-reconstruction-dossier",
      kind: "dossier" as const,
      label: "South Carolina political membership under Reconstruction",
      description: "South Carolina's 1868 constitutional membership rules widened Black men's formal access to voting and office while retaining explicit exclusions; later records show officeholding, coercion, federal enforcement, and a disputed transfer of executive authority.",
      subject: { kind: "case" as const, id: "south-carolina-reconstruction-political-membership" },
      standfirst: "",
      standfirstStatementIds: [
        "sc-constitution-elector-membership-1868",
        "sc-constitution-elector-residence-1868",
        "sc-constitution-institutional-confinement-exclusion",
        "sc-constitution-religious-office-test",
        "sc-whipper-motion-rejected",
        "sc-house-black-majority-1868-1876",
        "sc-hill-political-renunciation-demands",
        "sc-federal-mass-arrests-1871",
        "sc-disputed-election-rival-governors",
        "sc-office-transfer-case-boundary",
      ],
      sections: [
        {
          id: "changed-membership",
          heading: "What changed in political membership in 1868?",
          body: "",
          traceStatus: "qualified" as const,
          statementIds: [
            "sc-constitution-elector-membership-1868",
            "sc-constitution-free-open-election-rule",
            "sc-constitution-equal-elect-and-be-elected-rule",
            "sc-office-transfer-case-boundary",
          ],
          relatedEntityRefs: [
            { kind: "case" as const, id: "south-carolina-reconstruction-political-membership" },
            { kind: "case-episode" as const, id: "sc-constitution-formation-1868" },
          ],
          researchObligationIds: ["sc-reconstruction-post-1877-formal-practice-divergence"],
        },
        {
          id: "antecedent-demands",
          heading: "Who demanded political membership before the convention?",
          body: "",
          traceStatus: "qualified" as const,
          statementIds: [
            "sc-colored-convention-equal-suffrage-demand",
            "sc-colored-convention-representation-argument",
            "sc-organizer-meeting-reach-report",
            "sc-organizer-league-reach-report",
            "sc-organizer-report-scope-boundary",
          ],
        },
        {
          id: "eligibility-and-exclusion",
          heading: "Who could vote or hold office?",
          body: "",
          traceStatus: "qualified" as const,
          statementIds: [
            "sc-constitution-elector-residence-1868",
            "sc-constitution-federal-disability-exclusion",
            "sc-constitution-institutional-confinement-exclusion",
            "sc-constitution-prison-confinement-exclusion",
            "sc-constitution-enslavement-conviction-boundary",
            "sc-constitution-county-office-elector-rule",
            "sc-constitution-general-office-elector-rule",
            "sc-constitution-first-election-residence-exception",
            "sc-constitution-religious-office-test",
            "sc-constitution-no-property-office-qualification",
            "sc-constitution-election-protection-directive",
            "sc-house-population-apportionment-rule",
            "sc-house-county-minimum-representation-rule",
            "sc-constitution-later-amendment-boundary",
          ],
        },
        {
          id: "convention-arguments",
          heading: "What did Black delegates argue, and what did the convention decide?",
          body: "",
          traceStatus: "qualified" as const,
          statementIds: [
            "sc-ransier-opposed-education-voting-test",
            "sc-ransier-opposed-property-voting-test",
            "sc-ransier-suffrage-self-defense-argument",
            "sc-whipper-male-word-removal-motion",
            "sc-whipper-woman-suffrage-argument",
            "sc-whipper-motion-rejected",
            "sc-convention-adopted-constitution",
            "sc-electors-ratified-constitution",
            "sc-congress-admitted-representation",
          ],
          researchObligationIds: ["sc-reconstruction-women-political-practice"],
        },
        {
          id: "officeholding-practice",
          heading: "What did officeholding look like in practice?",
          body: "",
          traceStatus: "qualified" as const,
          statementIds: ["sc-house-black-majority-1868-1876", "sc-senate-black-majority-1872-1876"],
          relatedEntityRefs: [{ kind: "case-episode" as const, id: "sc-black-legislative-participation-1868-1876" }],
        },
        {
          id: "political-coercion",
          heading: "How did political coercion operate?",
          body: "",
          traceStatus: "qualified" as const,
          statementIds: [
            "sc-hill-league-role-context",
            "sc-hill-may-1871-assault-testimony",
            "sc-hill-political-renunciation-demands",
            "sc-bonner-league-meeting-cessation",
            "sc-congressional-testimony-mediation-boundary",
          ],
          relatedEntityRefs: [{ kind: "case-episode" as const, id: "sc-political-coercion-federal-enforcement-1871-1872" }],
        },
        {
          id: "federal-enforcement",
          heading: "What did federal enforcement accomplish and fail to secure?",
          body: "",
          traceStatus: "qualified" as const,
          statementIds: [
            "sc-enforcement-act-vote-intimidation-rule",
            "sc-klan-act-voter-intimidation-rule",
            "sc-grant-habeas-suspension-october-1871",
            "sc-federal-mass-arrests-1871",
            "sc-klan-prosecution-results",
            "sc-klan-enforcement-short-term-assessment",
            "sc-klan-enforcement-durability-limit",
          ],
          researchObligationIds: [
            "sc-reconstruction-enforcement-deterrence-duration",
            "sc-reconstruction-federal-protection-durability",
          ],
        },
        {
          id: "contest-and-transfer",
          heading: "What changed in 1876 and April 1877?",
          body: "",
          traceStatus: "qualified" as const,
          statementIds: [
            "sc-hamburg-red-shirt-militia-confrontation",
            "sc-hamburg-bradley-six-executions-account",
            "sc-hamburg-stone-five-prisoners-account",
            "sc-hamburg-victim-membership-boundary",
            "sc-hamburg-casualty-count-conflict",
            "sc-hamburg-indictments-no-trials",
            "sc-rifle-club-organization-october-1876",
            "sc-rifle-club-intimidation-purpose",
            "sc-rifle-club-hampton-support-purpose",
            "sc-grant-rifle-club-disband-order",
            "sc-federal-reinforcement-1876",
            "sc-disputed-election-rival-governors",
            "sc-statehouse-troops-withdrawn-april-10",
            "sc-chamberlain-transfer-correspondence-april-10",
            "sc-executive-office-transferred-april-11",
            "sc-reversal-causal-weight-boundary",
          ],
          relatedEntityRefs: [{ kind: "case-episode" as const, id: "sc-election-contest-office-transfer-1876-1877" }],
          researchObligationIds: [
            "sc-reconstruction-paramilitary-electoral-effect",
            "sc-reconstruction-federal-withdrawal-control-effect",
            "sc-hamburg-casualty-identity-sequence-reconciliation",
          ],
        },
        {
          id: "comparisons-and-open-questions",
          heading: "What remains unsettled, and what should be compared?",
          body: "",
          traceStatus: "qualified" as const,
          statementIds: [
            "kahnawake-cdmrp-type-one-design",
            "jbg-formal-delegation",
            "jbg-civil-military-authority-limit",
            "koto-tinggi-three-institutions",
            "koto-tinggi-representative-council",
            "koto-tinggi-customary-council",
            "koto-tinggi-formal-participation-rules",
          ],
          relatedEntityRefs: [
            { kind: "case" as const, id: "kahnawake-community-lawmaking" },
            { kind: "case" as const, id: "zapatista-autonomy-chiapas-1994-present" },
            { kind: "case" as const, id: "koto-tinggi-post-decentralization-governance" },
          ],
          researchObligationIds: ["sc-reconstruction-republican-coalition-division-1876"],
        },
      ],
      publicationStatus: "reviewed" as const,
      reviewedAt: "2026-09-08",
    }),
  },
] satisfies AuthoringDocument[];
