import type { AuthoringDocument } from "../../../src/lib/domain";

const citations = [
  [
    "capitalism-definition-contested",
    "sep-capitalism-source",
    "section 1, introductory paragraph and sections 1.1–1.7",
    "supports",
    "rival-definitions",
  ],
  [
    "capitalism-market-boundary",
    "sep-markets-2026-source",
    "section 1, paragraphs 4–5",
    "supports",
    "market-boundary",
  ],
  [
    "capitalism-market-boundary",
    "hodgson-conceptualizing-capitalism-source",
    "chapter 5, pp. 129–146; chapter 10, pp. 251–262",
    "supports",
    "historical-market-boundary",
  ],
  [
    "capitalism-institutional-definition",
    "hodgson-conceptualizing-capitalism-source",
    "chapter 10, pp. 251–262",
    "supports",
    "institutional-definition",
  ],
  [
    "capitalism-marx-definition",
    "marx-capital-volume-one-source",
    "chapter 6, paragraphs beginning “The change of value” and “In order to be able to extract value”; chapter 26, first four paragraphs",
    "supports",
    "marx-definition",
  ],
  [
    "capitalism-marx-definition",
    "sep-capitalism-source",
    "section 1.1, paragraphs 1–8",
    "context",
    "marx-context",
  ],
  [
    "capitalism-polanyi-definition",
    "polanyi-great-transformation-source",
    "chapter 6, pp. 71–80",
    "supports",
    "polanyi-definition",
  ],
  [
    "capitalism-polanyi-definition",
    "sep-capitalism-source",
    "section 1.6, paragraphs 1–5",
    "context",
    "polanyi-context",
  ],
  [
    "property-possession-boundary",
    "hodgson-conceptualizing-capitalism-source",
    "chapter 4, pp. 101–128",
    "supports",
    "property-possession",
  ],
  [
    "property-rights-plural",
    "hohfeld-fundamental-legal-conceptions-source",
    "pp. 30–44, tables of jural correlatives and opposites",
    "supports",
    "property-incidents",
  ],
  [
    "wage-labor-boundary",
    "hodgson-conceptualizing-capitalism-source",
    "chapter 9, pp. 235–250",
    "supports",
    "employment-boundary",
  ],
  [
    "wage-labor-history-limit",
    "hodgson-conceptualizing-capitalism-source",
    "chapter 9, pp. 235–250",
    "supports",
    "employment-history",
  ],
  [
    "commodity-production-boundary",
    "hodgson-conceptualizing-capitalism-source",
    "chapter 5, pp. 129–146",
    "supports",
    "commodity-boundary",
  ],
  [
    "commodity-production-boundary",
    "marx-capital-volume-one-source",
    "chapter 6, final twelve paragraphs",
    "context",
    "commodity-labor-context",
  ],
  [
    "firm-market-boundary",
    "sep-markets-2026-source",
    "section 1, paragraph 3",
    "supports",
    "firm-boundary",
  ],
  [
    "firm-market-boundary",
    "hodgson-conceptualizing-capitalism-source",
    "chapter 8, pp. 208–234",
    "supports",
    "firm-institution",
  ],
  [
    "capital-finance-boundary",
    "hodgson-conceptualizing-capitalism-source",
    "chapters 6–7, pp. 147–207",
    "supports",
    "capital-finance",
  ],
  [
    "market-definition-exchange",
    "sep-markets-2026-source",
    "opening summary and section 1, paragraphs 1–2",
    "supports",
    "market-definition",
  ],
  [
    "market-economy-plural-allocation",
    "sep-markets-2026-source",
    "section 1, paragraph 3",
    "supports",
    "plural-allocation",
  ],
  [
    "market-economy-plural-allocation",
    "polanyi-great-transformation-source",
    "chapter 4, pp. 45–58",
    "context",
    "allocation-context",
  ],
  [
    "market-state-boundary",
    "sep-markets-2026-source",
    "section 4.3, paragraphs 1–5",
    "supports",
    "market-state",
  ],
  [
    "market-state-boundary",
    "hodgson-conceptualizing-capitalism-source",
    "chapters 3–4, pp. 76–128",
    "supports",
    "legal-foundations",
  ],
  [
    "market-ownership-boundary",
    "sep-markets-2026-source",
    "section 1, paragraphs 4–5",
    "supports",
    "ownership-boundary",
  ],
  [
    "market-laissez-faire-boundary",
    "sep-markets-2026-source",
    "sections 1 and 4.3",
    "supports",
    "laissez-faire-boundary",
  ],
  [
    "smith-exchange-division-labor",
    "smith-wealth-nations-cannan-source",
    "Book I, chapters 2–3",
    "supports",
    "smith-exchange",
  ],
  [
    "england-brenner-class-thesis",
    "brenner-agrarian-class-structure-source",
    "pp. 31–40 and 61–75",
    "supports",
    "brenner-thesis",
  ],
  [
    "england-brenner-rival-explanations",
    "aston-philpin-brenner-debate-source",
    "introduction, pp. 1–10; contributions by Bois, Postan and Hatcher, and Brenner",
    "supports",
    "brenner-debate",
  ],
  [
    "ghana-cocoa-smallholder-expansion",
    "austin-ghana-cocoa-source",
    "pp. 1035–1041 and 1057–1061",
    "supports",
    "cocoa-producers",
  ],
  [
    "ghana-cocoa-resource-reallocation",
    "austin-ghana-cocoa-source",
    "pp. 1048–1062",
    "supports",
    "cocoa-reallocation",
  ],
  [
    "ghana-cocoa-classification-limit",
    "austin-ghana-cocoa-source",
    "pp. 1035–1048 and 1057–1062",
    "supports",
    "cocoa-boundary",
  ],
  [
    "china-dual-track-coordination",
    "naughton-growing-out-plan-source",
    "chapters 3 and 6, pp. 97–136 and 200–243",
    "supports",
    "dual-track",
  ],
  [
    "china-tve-ownership-boundary",
    "naughton-growing-out-plan-source",
    "chapter 4, pp. 137–170",
    "supports",
    "tve-ownership",
  ],
  [
    "china-marketization-classification-limit",
    "naughton-growing-out-plan-source",
    "chapters 4, 6, and 9, pp. 137–170, 200–243, and 309–340",
    "supports",
    "incremental-reform",
  ],
] as const;

const capitalism = { kind: "concept" as const, id: "capitalism" };
const marketEconomy = { kind: "concept" as const, id: "market-economy" };
const capitalismRelatedConceptStatements = [
  ["private-property", "property-possession-boundary"],
  ["wage-labor", "wage-labor-history-limit"],
  ["commodity-production", "commodity-production-boundary"],
  ["market-coordination", "capitalism-market-boundary"],
  ["business-firm", "firm-market-boundary"],
  ["finance", "capital-finance-boundary"],
  ["legal-order", "market-state-boundary"],
  ["state-capacity", "market-state-boundary"],
  ["economic-planning", "china-dual-track-coordination"],
  ["social-ownership", "market-ownership-boundary"],
] as const;

export const capitalismMarketRelationshipDocuments = [
  {
    documentType: "relationships",
    subject: capitalism,
    relationships: [
      {
        id: "capitalism-related-to-market-economy",
        predicate: "related-to",
        subject: capitalism,
        object: marketEconomy,
        status: "qualified",
        statementIds: [
          "capitalism-market-boundary",
          "market-ownership-boundary",
        ],
      },
      ...capitalismRelatedConceptStatements.map(([id, statementId]) => ({
        id: `capitalism-related-to-${id}`,
        predicate: "related-to" as const,
        subject: capitalism,
        object: { kind: "concept" as const, id },
        status: "qualified" as const,
        statementIds: [statementId],
      })),
    ],
  },
  {
    documentType: "relationships",
    subject: marketEconomy,
    relationships: [
      {
        id: "market-economy-related-to-market-coordination",
        predicate: "related-to",
        subject: marketEconomy,
        object: { kind: "concept", id: "market-coordination" },
        status: "qualified",
        statementIds: [
          "market-definition-exchange",
          "market-economy-plural-allocation",
        ],
      },
      {
        id: "market-economy-related-to-mixed-economy",
        predicate: "related-to",
        subject: marketEconomy,
        object: { kind: "concept", id: "mixed-economy" },
        status: "qualified",
        statementIds: [
          "market-economy-plural-allocation",
          "market-laissez-faire-boundary",
        ],
      },
      ...[
        ["business-firm", "firm-market-boundary"],
        ["finance", "capital-finance-boundary"],
        ["legal-order", "market-state-boundary"],
        ["state-capacity", "market-state-boundary"],
        ["economic-planning", "china-dual-track-coordination"],
        ["social-ownership", "market-ownership-boundary"],
      ].map(([id, statementId]) => ({
        id: `market-economy-related-to-${id}`,
        predicate: "related-to" as const,
        subject: marketEconomy,
        object: { kind: "concept" as const, id: id ?? "" },
        status: "qualified" as const,
        statementIds: [statementId ?? ""],
      })),
    ],
  },
  ...[
    [
      "english-agrarian-market-dependence",
      "england-brenner-rival-explanations",
    ],
    ["gold-coast-cocoa-expansion", "ghana-cocoa-classification-limit"],
    [
      "china-dual-track-market-reforms",
      "china-marketization-classification-limit",
    ],
  ].flatMap(([caseId, statementId]) =>
    [capitalism, marketEconomy].map((concept) => ({
      documentType: "relationships" as const,
      subject: { kind: "case" as const, id: caseId ?? "" },
      relationships: [
        {
          id: `${caseId}-${concept.id === "capitalism" ? "contests-capitalism" : "applies-market-economy"}`,
          predicate:
            concept.id === "capitalism"
              ? ("contested-in-case" as const)
              : ("applies-to-case" as const),
          subject: { kind: "case" as const, id: caseId ?? "" },
          object: concept,
          status: "qualified" as const,
          statementIds: [statementId ?? ""],
        },
      ],
    })),
  ),
  ...citations.map(([statementId, sourceId, locator, role, suffix]) => ({
    documentType: "relationships" as const,
    subject: { kind: "statement" as const, id: statementId },
    relationships: [
      {
        id: `${statementId}-cites-${suffix}`,
        predicate: "cites" as const,
        subject: { kind: "statement" as const, id: statementId },
        object: { kind: "source" as const, id: sourceId },
        role,
        locator,
        status: "reviewed" as const,
      },
    ],
  })),
] satisfies AuthoringDocument[];
