import type { AuthoringDocument } from "../../../src/lib/domain";

const citations = [
  [
    "liberalism-plural-traditions",
    "sep-liberalism-source",
    "introduction, paragraphs 1–2",
    "supports",
  ],
  [
    "liberalism-authority-justification",
    "sep-liberalism-source",
    "section 1.1, paragraphs 1–4",
    "supports",
  ],
  [
    "liberalism-liberty-disputes",
    "sep-liberalism-source",
    "sections 1.1–1.4",
    "supports",
  ],
  [
    "liberalism-old-new-boundary",
    "sep-liberalism-source",
    "sections 2.1–2.3",
    "supports",
  ],
  [
    "liberalism-label-insufficient",
    "sep-liberalism-source",
    "introduction, paragraphs 1–2",
    "supports",
  ],
  [
    "mill-liberty-limiting-principle",
    "mill-on-liberty-source",
    "chapter I, paragraph beginning ‘The object of this Essay’",
    "supports",
  ],
  [
    "mill-colonial-exclusion",
    "mill-on-liberty-source",
    "chapter I, paragraph beginning ‘It is, perhaps, hardly necessary’",
    "supports",
  ],
  [
    "mehta-liberal-empire-tension",
    "mehta-liberalism-empire-source",
    "publisher synopsis, paragraphs 1–2",
    "supports",
  ],
  [
    "pateman-contract-gender-boundary",
    "pateman-sexual-contract-source",
    "publisher synopsis, paragraph 1",
    "supports",
  ],
  [
    "india-equality-before-law",
    "india-constitution-source",
    "article 14",
    "supports",
  ],
  [
    "india-discrimination-grounds",
    "india-constitution-source",
    "article 15(1)",
    "supports",
  ],
  [
    "india-special-provisions",
    "india-constitution-source",
    "article 15(3)–(5)",
    "supports",
  ],
  [
    "japan-legal-equality",
    "japan-constitution-source",
    "article 14",
    "supports",
  ],
  [
    "japan-marriage-consent",
    "japan-constitution-source",
    "article 24(1), first sentence",
    "supports",
  ],
  [
    "japan-spousal-equality",
    "japan-constitution-source",
    "article 24(1), second sentence",
    "supports",
  ],
  [
    "japan-rights-drafting-boundary",
    "nakanishi-japan-rights-source",
    "pp. 1185–1186 and 1191–1195",
    "supports",
  ],
  [
    "conservatism-broad-narrow",
    "sep-conservatism-source",
    "section 1.1, paragraphs 1–3",
    "supports",
  ],
  [
    "conservatism-tradition-reform",
    "sep-conservatism-source",
    "section 1.3, paragraphs 1–3",
    "supports",
  ],
  [
    "conservatism-reaction-boundary",
    "sep-conservatism-source",
    "section 1.3, paragraphs 1–3",
    "supports",
  ],
  [
    "conservatism-authoritarian-boundary",
    "sep-conservatism-source",
    "section 1.3, paragraphs 2–4",
    "supports",
  ],
  [
    "conservatism-procedural-substantive",
    "sep-conservatism-source",
    "section 1.4, paragraphs 1–5",
    "supports",
  ],
  [
    "burke-change-conservation",
    "burke-reflections-source",
    "paragraph beginning ‘A state without the means of some change’",
    "supports",
  ],
  [
    "burke-inheritance-prudence",
    "burke-reflections-source",
    "paragraph beginning ‘You will observe, that from Magna Charta’",
    "supports",
  ],
  [
    "ahlen-programme-economic-order",
    "cdu-ahlen-programme-source",
    "preamble, paragraphs 1–2",
    "supports",
  ],
  [
    "ahlen-programme-compromise",
    "bach-ahlen-history-source",
    "paragraphs 1–5",
    "supports",
  ],
  [
    "duesseldorf-social-market-shift",
    "cdu-duesseldorf-guidelines-source",
    "pp. 1–4, ‘Soziale Marktwirtschaft’ and principles 1–8",
    "supports",
  ],
  [
    "cdu-programme-change-boundary",
    "bach-ahlen-history-source",
    "paragraphs 1–5",
    "supports",
  ],
  [
    "cdu-programme-change-boundary",
    "cdu-duesseldorf-guidelines-source",
    "pp. 1–4, principles 1–8",
    "context",
  ],
  [
    "bell-rival-liberalism-methods",
    "bell-what-is-liberalism-source",
    "pp. 682–689",
    "supports",
  ],
  [
    "huntington-rival-conservatism-types",
    "huntington-conservatism-ideology-source",
    "pp. 454–461",
    "supports",
  ],
  [
    "right-to-buy-conservative-programme",
    "commons-right-to-buy-source",
    "printed p. 7, paragraphs 2–3",
    "supports",
  ],
  [
    "right-to-buy-statutory-rules",
    "housing-act-1980-source",
    "sections 1–2, 7, 16–17, 35",
    "supports",
  ],
  [
    "right-to-buy-statutory-rules",
    "commons-right-to-buy-source",
    "printed pp. 7–8, ‘The Housing Act 1980’",
    "context",
  ],
  [
    "right-to-buy-distribution",
    "commons-right-to-buy-source",
    "summary, printed p. 5; printed pp. 12–15",
    "supports",
  ],
  [
    "swatantra-economic-conservatism",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 5–6",
    "supports",
  ],
  [
    "swatantra-ordered-progress",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 3–4 and 17–18",
    "supports",
  ],
  [
    "swatantra-gender-limit",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 15–16",
    "supports",
  ],
  [
    "swatantra-opposition-practices",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 17–18",
    "supports",
  ],
  [
    "india-liberal-rights-test",
    "india-constitution-source",
    "articles 14–15",
    "context",
  ],
  [
    "japan-liberal-rights-test",
    "nakanishi-japan-rights-source",
    "pp. 1185–1186 and 1191–1195",
    "context",
  ],
  [
    "right-to-buy-conservatism-boundary",
    "commons-right-to-buy-source",
    "printed pp. 7–8",
    "context",
  ],
  [
    "swatantra-conservatism-boundary",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 3–6 and 15–18",
    "supports",
  ],
  [
    "liberalism-exclusion-evidence-limit",
    "mehta-liberalism-empire-source",
    "publisher synopsis, paragraphs 1–2",
    "context",
  ],
  [
    "liberalism-exclusion-evidence-limit",
    "pateman-sexual-contract-source",
    "publisher synopsis, paragraph 1",
    "context",
  ],
  [
    "liberalism-atlantic-taxonomy-limit",
    "bell-what-is-liberalism-source",
    "pp. 682–689",
    "context",
  ],
  [
    "conservatism-genealogy-limit",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 3–6",
    "context",
  ],
] as const;

export const liberalismConservatismRelationshipDocuments = [
  ...[
    [
      "india-constitutional-rights-settlement-1946-1950",
      "liberalism",
      "india-liberal-rights-test",
    ],
    [
      "japan-constitutional-rights-settlement-1946-1947",
      "liberalism",
      "japan-liberal-rights-test",
    ],
    [
      "right-to-buy-england-wales-1980-1988",
      "conservatism",
      "right-to-buy-conservatism-boundary",
    ],
    [
      "swatantra-opposition-organization-1959-1967",
      "conservatism",
      "swatantra-conservatism-boundary",
    ],
  ].map(([caseId, conceptId, statementId]) => ({
    documentType: "relationships" as const,
    subject: { kind: "case" as const, id: caseId },
    relationships: [
      {
        id: `${caseId}-contests-${conceptId}`,
        predicate: "contested-in-case" as const,
        subject: { kind: "case" as const, id: caseId },
        object: { kind: "concept" as const, id: conceptId },
        status: "qualified" as const,
        statementIds: [statementId],
      },
    ],
  })),
  ...citations.map(([statementId, sourceId, locator, role], index) => ({
    documentType: "relationships" as const,
    subject: { kind: "statement" as const, id: statementId },
    relationships: [
      {
        id: `${statementId}-cites-${index + 1}`,
        predicate: "cites" as const,
        subject: { kind: "statement" as const, id: statementId },
        object: { kind: "source" as const, id: sourceId },
        role,
        locator,
      },
    ],
  })),
] satisfies AuthoringDocument[];
