import type { AuthoringDocument } from "../../../src/lib/domain";

const citations = [
  [
    "liberalism-plural-traditions",
    "sep-liberalism-source",
    "introduction, paragraphs 1–2",
    "supports",
  ],
  [
    "liberalism-authority-justification",
    "sep-liberalism-source",
    "section 1.1, paragraphs 1–4",
    "supports",
  ],
  [
    "liberalism-liberty-disputes",
    "sep-liberalism-source",
    "sections 1.1–1.4",
    "supports",
  ],
  [
    "liberalism-old-new-boundary",
    "sep-liberalism-source",
    "sections 2.1–2.3",
    "supports",
  ],
  [
    "liberalism-label-insufficient",
    "sep-liberalism-source",
    "introduction, paragraphs 1–2",
    "supports",
  ],
  [
    "mill-liberty-limiting-principle",
    "mill-on-liberty-source",
    "chapter I, paragraph beginning ‘The object of this Essay’",
    "supports",
  ],
  [
    "mill-colonial-exclusion",
    "mill-on-liberty-source",
    "chapter I, paragraph beginning ‘It is, perhaps, hardly necessary’",
    "supports",
  ],
  [
    "mehta-liberal-empire-tension",
    "mehta-liberalism-empire-source",
    "publisher synopsis, paragraphs 1–2",
    "supports",
  ],
  [
    "pateman-contract-gender-boundary",
    "pateman-sexual-contract-source",
    "publisher synopsis, paragraph 1",
    "supports",
  ],
  [
    "india-equality-before-law",
    "india-constitution-source",
    "article 14",
    "supports",
  ],
  [
    "india-discrimination-grounds",
    "india-constitution-source",
    "article 15(1)",
    "supports",
  ],
  [
    "india-special-provisions",
    "india-constitution-source",
    "article 15(3)–(5)",
    "supports",
  ],
  [
    "japan-legal-equality",
    "japan-constitution-source",
    "article 14",
    "supports",
  ],
  [
    "japan-marriage-consent",
    "japan-constitution-source",
    "article 24(1), first sentence",
    "supports",
  ],
  [
    "japan-spousal-equality",
    "japan-constitution-source",
    "article 24(1), second sentence",
    "supports",
  ],
  [
    "japan-rights-drafting-boundary",
    "nakanishi-japan-rights-source",
    "pp. 1185–1186 and 1191–1195",
    "supports",
  ],
  [
    "conservatism-broad-narrow",
    "sep-conservatism-source",
    "section 1.1, paragraphs 1–3",
    "supports",
  ],
  [
    "conservatism-tradition-reform",
    "sep-conservatism-source",
    "section 1.3, paragraphs 1–3",
    "supports",
  ],
  [
    "conservatism-reaction-boundary",
    "sep-conservatism-source",
    "section 1.3, paragraphs 1–3",
    "supports",
  ],
  [
    "conservatism-authoritarian-boundary",
    "sep-conservatism-source",
    "section 1.3, paragraphs 2–4",
    "supports",
  ],
  [
    "conservatism-procedural-substantive",
    "sep-conservatism-source",
    "section 1.4, paragraphs 1–5",
    "supports",
  ],
  [
    "burke-change-conservation",
    "burke-reflections-source",
    "paragraph beginning ‘A state without the means of some change’",
    "supports",
  ],
  [
    "burke-inheritance-prudence",
    "burke-reflections-source",
    "paragraph beginning ‘You will observe, that from Magna Charta’",
    "supports",
  ],
  [
    "ahlen-programme-economic-order",
    "cdu-ahlen-programme-source",
    "preamble, paragraphs 1–2; Ends and Means English summary translated from the cited German",
    "supports",
  ],
  [
    "ahlen-programme-compromise",
    "bach-ahlen-history-source",
    "paragraphs 1–5",
    "supports",
  ],
  [
    "duesseldorf-social-market-shift",
    "cdu-duesseldorf-guidelines-source",
    "pp. 1–4, ‘Soziale Marktwirtschaft’ and principles 1–8; Ends and Means English summary translated from the cited German",
    "supports",
  ],
  [
    "cdu-programme-change-boundary",
    "bach-ahlen-history-source",
    "paragraphs 1–5",
    "supports",
  ],
  [
    "cdu-programme-change-boundary",
    "cdu-duesseldorf-guidelines-source",
    "pp. 1–4, principles 1–8",
    "context",
  ],
  [
    "bell-rival-liberalism-methods",
    "bell-what-is-liberalism-source",
    "abstract, sentences 2–3",
    "supports",
  ],
  [
    "huntington-rival-conservatism-types",
    "huntington-conservatism-ideology-source",
    "publisher extract, first paragraph",
    "supports",
  ],
  [
    "right-to-buy-conservative-programme",
    "commons-right-to-buy-source",
    "printed p. 7, paragraphs 2–3",
    "supports",
  ],
  [
    "right-to-buy-purchase-right",
    "housing-act-1980-source",
    "section 1",
    "supports",
  ],
  [
    "right-to-buy-discounts",
    "housing-act-1980-source",
    "section 7",
    "supports",
  ],
  [
    "right-to-buy-mortgage-duty",
    "housing-act-1980-source",
    "section 16",
    "supports",
  ],
  [
    "right-to-buy-ministerial-intervention",
    "housing-act-1980-source",
    "section 23",
    "supports",
  ],
  [
    "right-to-buy-buyer-distribution",
    "commons-right-to-buy-source",
    "printed pp. 12–13",
    "supports",
  ],
  [
    "right-to-buy-residual-sector",
    "commons-right-to-buy-source",
    "printed pp. 14–15",
    "supports",
  ],
  [
    "right-to-buy-rules-changed",
    "commons-right-to-buy-source",
    "printed pp. 8–9, ‘Further legislation on the Right to Buy’",
    "supports",
  ],
  [
    "swatantra-economic-conservatism",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 5–6",
    "supports",
  ],
  [
    "swatantra-ordered-progress",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 3–4 and 17–18",
    "supports",
  ],
  [
    "swatantra-gender-limit",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 15–16",
    "supports",
  ],
  [
    "swatantra-coalition-practice",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 17–18",
    "supports",
  ],
  [
    "swatantra-parliamentary-practice",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 17–18",
    "supports",
  ],
  [
    "swatantra-court-practice",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 17–18",
    "supports",
  ],
  [
    "swatantra-formal-principles",
    "swatantra-statement-principles-source",
    "title page and principles 1–21",
    "supports",
  ],
  [
    "india-liberal-rights-test",
    "india-constitution-source",
    "articles 14–15",
    "context",
  ],
  [
    "japan-liberal-rights-test",
    "nakanishi-japan-rights-source",
    "pp. 1185–1186 and 1191–1195",
    "context",
  ],
  [
    "right-to-buy-conservatism-boundary",
    "commons-right-to-buy-source",
    "printed pp. 7–8",
    "context",
  ],
  [
    "swatantra-conservatism-boundary",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 3–6 and 15–18",
    "supports",
  ],
  [
    "liberalism-exclusion-evidence-limit",
    "mehta-liberalism-empire-source",
    "publisher synopsis, paragraphs 1–2",
    "context",
  ],
  [
    "liberalism-exclusion-evidence-limit",
    "pateman-sexual-contract-source",
    "publisher synopsis, paragraph 1",
    "context",
  ],
  [
    "liberalism-atlantic-taxonomy-limit",
    "bell-what-is-liberalism-source",
    "pp. 682–689",
    "context",
  ],
  [
    "conservatism-genealogy-limit",
    "balasubramanian-free-economy-source",
    "introduction, printed pp. 3–6",
    "context",
  ],
] as const;

export const liberalismConservatismRelationshipDocuments = [
  ...citations.map(([statementId, sourceId, locator, role], index) => ({
    documentType: "relationships" as const,
    subject: { kind: "statement" as const, id: statementId },
    relationships: [
      {
        id: `${statementId}-cites-${index + 1}`,
        predicate: "cites" as const,
        subject: { kind: "statement" as const, id: statementId },
        object: { kind: "source" as const, id: sourceId },
        role,
        locator,
      },
    ],
  })),
] satisfies AuthoringDocument[];
