import type { AuthoringDocument } from "../../../src/lib/domain";

type CitationRole = "supports" | "challenges" | "qualifies" | "context";

const citationRows: [string, string, string, CitationRole, string][] = [
  [
    "matriliny-maternal-descent-definition",
    "mardoni-matrilineal-data-center-source",
    "opening section, paragraph beginning ‘Sistem matrilineal diartikan’",
    "supports",
    "local-definition",
  ],
  [
    "matriliny-does-not-fix-property-control",
    "mutolib-bonjol-ulayat-source",
    "p. 32, paragraph beginning ‘Control over ulayat land’",
    "supports",
    "descent-property-control-boundary",
  ],
  [
    "matriliny-does-not-fix-office",
    "mutolib-bonjol-ulayat-source",
    "p. 33, first paragraph",
    "supports",
    "descent-office-boundary",
  ],
  [
    "matriliny-does-not-fix-equality",
    "mutolib-bonjol-ulayat-source",
    "p. 41, ‘Discussion’, first paragraph",
    "supports",
    "descent-equality-boundary",
  ],
  [
    "matrilocality-residence-distinction",
    "sanday-women-center-excerpt-source",
    "‘From the Preface’, paragraph beginning ‘A number of feminist writers’",
    "supports",
    "matrilocal-residence",
  ],
  [
    "matriliny-does-not-fix-residence",
    "sanday-women-center-excerpt-source",
    "‘From the Preface’, paragraph beginning ‘A number of feminist writers’",
    "supports",
    "descent-residence-boundary",
  ],
  [
    "matriarchy-rule-by-women-dispute",
    "sanday-women-center-excerpt-source",
    "‘From the Preface’, paragraph beginning ‘A number of feminist writers’",
    "supports",
    "sanday-redefinition",
  ],
  [
    "matriarchy-sanday-maternal-centered-interpretation",
    "sanday-women-center-excerpt-source",
    "‘From the Preface’, paragraph beginning ‘A number of feminist writers’",
    "supports",
    "sanday-maternal-interpretation",
  ],
  [
    "minangkabau-power-varies-by-relation",
    "blackwood-webs-power-source",
    "chapter 1, pp. 7–8, paragraphs describing relation-specific forms of power",
    "supports",
    "blackwood-gender-power",
  ],
  [
    "minangkabau-power-varies-by-relation",
    "mutolib-bonjol-ulayat-source",
    "p. 41, ‘Discussion’, first paragraph",
    "qualifies",
    "bonjol-rival-case",
  ],
  [
    "minangkabau-practices-historically-changing",
    "sebastian-matrilineal-muslims-source",
    "abstract",
    "supports",
    "historical-change",
  ],
  [
    "adat-translation-boundary",
    "blackwood-webs-power-source",
    "chapter 1, p. 1, opening paragraph",
    "supports",
    "adat-translation-blackwood",
  ],
  [
    "adat-translation-boundary",
    "nurdin-nagari-governance-source",
    "p. 106, footnote 1",
    "context",
    "adat-translation-nurdin",
  ],
  [
    "nagari-translation-boundary",
    "nurdin-nagari-governance-source",
    "p. 109, paragraph beginning ‘Structure of Nagari Government’",
    "supports",
    "nagari-institutional-form",
  ],
  [
    "nagari-translation-boundary",
    "west-sumatra-nagari-law-2018-source",
    "articles 1–3",
    "context",
    "nagari-later-law",
  ],
  [
    "minangkabau-legal-orders-interact",
    "nurdin-nagari-governance-source",
    "p. 109, paragraph beginning ‘Structure of Nagari Government’; p. 110, paragraph beginning ‘Institutionally’",
    "supports",
    "legal-orders-nurdin",
  ],
  [
    "minangkabau-legal-orders-interact",
    "sebastian-matrilineal-muslims-source",
    "abstract",
    "supports",
    "legal-orders-sebastian",
  ],
  [
    "minangkabau-ancestral-acquired-property-distinction",
    "colombijn-padang-landownership-source",
    "p. 432, paragraph beginning ‘In Minangkabau society’",
    "supports",
    "padang-property-categories",
  ],
  [
    "koto-tinggi-minangkabau-adat-context",
    "nurdin-nagari-governance-source",
    "p. 106, opening paragraph; p. 109, paragraph beginning ‘Structure of Nagari Government’",
    "supports",
    "koto-adat-context",
  ],
  [
    "koto-tinggi-descent-unobserved",
    "nurdin-nagari-governance-source",
    "p. 108, ‘Method’, complete method description",
    "supports",
    "koto-descent-unobserved",
  ],
  [
    "koto-tinggi-residence-unobserved",
    "nurdin-nagari-governance-source",
    "p. 108, ‘Method’, complete method description",
    "supports",
    "koto-residence-unobserved",
  ],
  [
    "koto-tinggi-fieldwork-scope",
    "nurdin-nagari-governance-source",
    "p. 108, final paragraph before ‘Method’",
    "supports",
    "koto-method",
  ],
  [
    "koto-tinggi-participant-count-unreported",
    "nurdin-nagari-governance-source",
    "p. 108, ‘Method’, complete method description",
    "supports",
    "koto-count-unreported",
  ],
  [
    "koto-tinggi-womens-voice-unidentified",
    "nurdin-nagari-governance-source",
    "p. 108, ‘Method’, complete method description",
    "supports",
    "koto-womens-voice-unidentified",
  ],
  [
    "koto-tinggi-three-institutions",
    "nurdin-nagari-governance-source",
    "p. 109, first four paragraphs",
    "supports",
    "koto-formal-institutions",
  ],
  [
    "koto-tinggi-formal-participation-rules",
    "nurdin-nagari-governance-source",
    "p. 109, ‘The Mechanism of Rural Development’, paragraph beginning ‘The meeting was attended’",
    "supports",
    "koto-meeting-rules",
  ],
  [
    "koto-tinggi-formal-decision-rule",
    "nurdin-nagari-governance-source",
    "p. 110, first paragraph",
    "supports",
    "koto-decision-rule",
  ],
  [
    "koto-tinggi-formal-speaking-rule",
    "nurdin-nagari-governance-source",
    "p. 110, first paragraph, sentence beginning ‘All participants’",
    "supports",
    "koto-speaking-rule",
  ],
  [
    "koto-tinggi-formal-consensus-rule",
    "nurdin-nagari-governance-source",
    "p. 110, first paragraph, sentence beginning ‘Decision making’",
    "supports",
    "koto-consensus-rule",
  ],
  [
    "koto-tinggi-formal-vote-fallback",
    "nurdin-nagari-governance-source",
    "p. 110, first paragraph, final sentence",
    "supports",
    "koto-vote-fallback",
  ],
  [
    "koto-tinggi-customary-council-contestation",
    "nurdin-nagari-governance-source",
    "p. 110, final two paragraphs before ‘Dynamic of Interaction in Rural Development’",
    "supports",
    "koto-dual-council-dispute",
  ],
  [
    "koto-tinggi-budget-rules-in-use",
    "nurdin-nagari-governance-source",
    "p. 111, first paragraph",
    "supports",
    "koto-budget-practice",
  ],
  [
    "koto-tinggi-budget-consensus",
    "nurdin-nagari-governance-source",
    "p. 111, second paragraph",
    "supports",
    "koto-budget-consensus",
  ],
  [
    "koto-tinggi-administrative-capacity-limit",
    "nurdin-nagari-governance-source",
    "p. 110, paragraph beginning ‘Looking at the stipulated mechanism’",
    "supports",
    "koto-capacity-limit",
  ],
  [
    "koto-tinggi-regulatory-preparation-limit",
    "nurdin-nagari-governance-source",
    "p. 111, final paragraph",
    "supports",
    "koto-regulatory-preparation",
  ],
  [
    "bonjol-study-method-and-voice",
    "mutolib-bonjol-ulayat-source",
    "pp. 26–27, ‘Methodology’, ‘Data Collection Technique’, and ‘Data Analysis’",
    "supports",
    "bonjol-method",
  ],
  [
    "bonjol-new-nagari-forest-transition",
    "mutolib-bonjol-ulayat-source",
    "p. 29, paragraph beginning ‘After the regional autonomy’",
    "supports",
    "bonjol-transition",
  ],
  [
    "bonjol-concession-end-transition",
    "mutolib-bonjol-ulayat-source",
    "p. 29, paragraph beginning ‘The area was formerly’",
    "supports",
    "bonjol-concession-transition",
  ],
  [
    "bonjol-ulayat-formal-distinction",
    "mutolib-bonjol-ulayat-source",
    "p. 31, ‘Land Control in the Melayu Clan of Nagari Bonjol’, first paragraph",
    "supports",
    "bonjol-ulayat-authority",
  ],
  [
    "bonjol-ulayat-delegated-management",
    "mutolib-bonjol-ulayat-source",
    "p. 32, paragraph beginning ‘Control over ulayat land’",
    "supports",
    "bonjol-delegated-management",
  ],
  [
    "bonjol-harta-pusaka-transition",
    "mutolib-bonjol-ulayat-source",
    "p. 32, final paragraph continuing onto p. 33",
    "supports",
    "bonjol-property-transition",
  ],
  [
    "bonjol-harta-pusaka-female-line",
    "mutolib-bonjol-ulayat-source",
    "p. 33, first paragraph",
    "supports",
    "bonjol-female-line-transmission",
  ],
  [
    "bonjol-inheritance-did-not-confer-office-authority",
    "mutolib-bonjol-ulayat-source",
    "p. 33, first paragraph",
    "supports",
    "bonjol-inheritance-office-boundary",
  ],
  [
    "bonjol-bundo-kanduang-role",
    "mutolib-bonjol-ulayat-source",
    "p. 30, paragraph beginning ‘The most important role’",
    "supports",
    "bonjol-bundo-kanduang",
  ],
  [
    "bonjol-bundo-kanduang-not-universal-authority",
    "mutolib-bonjol-ulayat-source",
    "p. 30, paragraph beginning ‘The most important role’; p. 33, first paragraph",
    "qualifies",
    "bonjol-bundo-boundary",
  ],
  [
    "bonjol-ulayat-sales-rules-in-use",
    "mutolib-bonjol-ulayat-source",
    "pp. 33–35, ‘Selling Ulayat Forest Land’, tables 1–2",
    "supports",
    "bonjol-sales",
  ],
  [
    "bonjol-neshp-formal-promise",
    "mutolib-bonjol-ulayat-source",
    "p. 35, ‘Manipulation of NESHP Plot Distribution’, first paragraph",
    "supports",
    "bonjol-neshp-promise",
  ],
  [
    "bonjol-neshp-distribution-practice",
    "mutolib-bonjol-ulayat-source",
    "p. 35, ‘Manipulation of NESHP Plot Distribution’, final paragraph",
    "supports",
    "bonjol-neshp-practice",
  ],
  [
    "bonjol-neshp-exclusion-outcome",
    "mutolib-bonjol-ulayat-source",
    "p. 36, first two paragraphs",
    "supports",
    "bonjol-neshp-exclusion",
  ],
  [
    "bonjol-women-testimony-limit",
    "mutolib-bonjol-ulayat-source",
    "p. 36, ‘Melayu Women: When Matters Are More Precious Than Kinship’, second paragraph",
    "supports",
    "bonjol-women-testimony",
  ],
  [
    "bonjol-five-women-testimony",
    "mutolib-bonjol-ulayat-source",
    "pp. 36–37, block quotation attributed to five Melayu women",
    "supports",
    "bonjol-five-women",
  ],
  [
    "bonjol-authors-causal-interpretation",
    "mutolib-bonjol-ulayat-source",
    "pp. 38–40, ‘Why are Melayu Women Oppressed?’, enumerated explanations",
    "supports",
    "bonjol-authors-explanation",
  ],
  [
    "bonjol-authors-early-marriage-hypothesis",
    "mutolib-bonjol-ulayat-source",
    "p. 39, subsection ‘Early Marriage’",
    "supports",
    "bonjol-early-marriage-hypothesis",
  ],
  [
    "bonjol-authors-gender-norms-hypothesis",
    "mutolib-bonjol-ulayat-source",
    "p. 40, subsection discussing patriarchal culture",
    "supports",
    "bonjol-gender-norms-hypothesis",
  ],
  [
    "bonjol-authors-forum-hypothesis",
    "mutolib-bonjol-ulayat-source",
    "p. 40, subsection ‘No Forum for Women’",
    "supports",
    "bonjol-forum-hypothesis",
  ],
  [
    "bonjol-authors-representation-dependence-hypothesis",
    "mutolib-bonjol-ulayat-source",
    "p. 40, subsection discussing dependence on male clan representatives",
    "supports",
    "bonjol-representation-hypothesis",
  ],
  [
    "bonjol-causal-identification-limit",
    "mutolib-bonjol-ulayat-source",
    "pp. 26–27, reported cross-sectional methods and sample",
    "qualifies",
    "bonjol-identification-limit",
  ],
  [
    "bonjol-authors-causal-interpretation",
    "mutolib-bonjol-ulayat-source",
    "pp. 26–27, reported cross-sectional methods and sample",
    "qualifies",
    "bonjol-causal-limit",
  ],
  [
    "bonjol-no-minangkabau-generalization",
    "mutolib-bonjol-ulayat-source",
    "p. 41, ‘Discussion’, first paragraph",
    "supports",
    "bonjol-transfer-limit",
  ],
  [
    "nagari-law-changed-after-cases",
    "west-sumatra-nagari-law-2018-source",
    "preamble paragraph c; articles 1–3 and 23",
    "supports",
    "post-case-law",
  ],
  [
    "koto-tinggi-representative-council",
    "nurdin-nagari-governance-source",
    "p. 109, second paragraph",
    "supports",
    "koto-representative-council",
  ],
  [
    "koto-tinggi-customary-council",
    "nurdin-nagari-governance-source",
    "p. 109, third paragraph",
    "supports",
    "koto-customary-council",
  ],
  [
    "koto-tinggi-budget-postponement",
    "nurdin-nagari-governance-source",
    "p. 111, first paragraph",
    "supports",
    "koto-budget-postponement",
  ],
  [
    "koto-tinggi-unspent-funds",
    "nurdin-nagari-governance-source",
    "p. 110, paragraph beginning ‘Looking at the stipulated mechanism’",
    "supports",
    "koto-unspent-funds",
  ],
  [
    "koto-tinggi-accounting-difficulty",
    "nurdin-nagari-governance-source",
    "p. 110, paragraph beginning ‘Looking at the stipulated mechanism’",
    "supports",
    "koto-accounting-difficulty",
  ],
  [
    "bonjol-thirteen-key-informants",
    "mutolib-bonjol-ulayat-source",
    "p. 26, ‘Data Collection Technique’, first paragraph",
    "supports",
    "bonjol-key-informants",
  ],
  [
    "bonjol-agency-records",
    "mutolib-bonjol-ulayat-source",
    "p. 27, first paragraph",
    "supports",
    "bonjol-agency-records",
  ],
  [
    "bonjol-twenty-seven-women-sample",
    "mutolib-bonjol-ulayat-source",
    "p. 27, first paragraph",
    "supports",
    "bonjol-women-sample",
  ],
  [
    "bonjol-ulayat-sales-contrary-to-custom",
    "mutolib-bonjol-ulayat-source",
    "p. 33, ‘Selling Ulayat Forest Land’, first paragraph",
    "supports",
    "bonjol-sales-custom-boundary",
  ],
  [
    "bonjol-neshp-member-exclusion",
    "mutolib-bonjol-ulayat-source",
    "p. 36, first two paragraphs",
    "supports",
    "bonjol-member-exclusion",
  ],
  [
    "bonjol-five-women-income-loss",
    "mutolib-bonjol-ulayat-source",
    "pp. 36–37, block quotation attributed to five Melayu women",
    "supports",
    "bonjol-five-women-income",
  ],
  [
    "bonjol-five-women-weak-influence",
    "mutolib-bonjol-ulayat-source",
    "pp. 36–37, block quotation attributed to five Melayu women",
    "supports",
    "bonjol-five-women-influence",
  ],
];

const citations = citationRows.map(
  ([statementId, sourceId, locator, role, suffix]) => ({
    documentType: "relationships" as const,
    subject: { kind: "statement" as const, id: statementId },
    relationships: [
      {
        id: `citation-${suffix}`,
        predicate: "cites" as const,
        subject: { kind: "statement" as const, id: statementId },
        object: { kind: "source" as const, id: sourceId },
        role,
        locator,
      },
    ],
  }),
);

export const minangkabauRelationshipDocuments = [
  ...citations,
  {
    documentType: "relationships",
    subject: {
      kind: "case-episode",
      id: "bonjol-ulayat-governance-2000-2016",
    },
    relationships: [
      {
        id: "bonjol-applies-matriliny",
        predicate: "applies-to-case",
        subject: {
          kind: "case-episode",
          id: "bonjol-ulayat-governance-2000-2016",
        },
        object: { kind: "concept", id: "matriliny" },
        status: "qualified",
        statementIds: [
          "bonjol-harta-pusaka-transition",
          "bonjol-harta-pusaka-female-line",
          "bonjol-no-minangkabau-generalization",
        ],
        scope: {
          startDate: "2000",
          endDate: "2016-04",
          placeIds: ["nagari-bonjol-dharmasraya"],
          note: "Applies only to the Melayu-clan property and descent arrangements documented in this episode.",
        },
      },
    ],
  },
  {
    documentType: "relationships",
    subject: { kind: "concept", id: "matriliny" },
    relationships: [
      {
        id: "matriliny-related-to-matrilocality",
        predicate: "related-to",
        subject: { kind: "concept", id: "matriliny" },
        object: { kind: "concept", id: "matrilocality" },
        status: "qualified",
        statementIds: [
          "matriliny-does-not-fix-residence",
          "matrilocality-residence-distinction",
        ],
      },
      {
        id: "matriliny-commonly-confused-with-matriarchy",
        predicate: "commonly-confused-with",
        subject: { kind: "concept", id: "matriliny" },
        object: { kind: "concept", id: "matriarchy" },
        status: "asserted",
        statementIds: [
          "matriarchy-rule-by-women-dispute",
          "matriarchy-sanday-maternal-centered-interpretation",
        ],
      },
    ],
  },
] satisfies AuthoringDocument[];
