import type { AuthoringDocument } from "../../../src/lib/domain";

type CitationRole = "supports" | "qualifies" | "context" | "challenges";
const rows: [string, string, string, CitationRole, string][] = [
  [
    "monarchy-office-form-definition",
    "idea-constitutional-monarchs-source",
    "pp. 3–6, ‘Introduction’ and ‘The role of a constitutional monarch’",
    "qualifies",
    "office",
  ],
  [
    "monarchy-heredity-boundary",
    "idea-constitutional-monarchs-source",
    "p. 12, ‘Alternative forms of succession’",
    "supports",
    "heredity",
  ],
  [
    "monarchy-succession-varies",
    "idea-constitutional-monarchs-source",
    "p. 12, ‘Alternative forms of succession’",
    "supports",
    "succession",
  ],
  [
    "monarchy-head-roles-boundary",
    "idea-constitutional-monarchs-source",
    "pp. 3–8, head of state and parliamentary government",
    "supports",
    "head-roles",
  ],
  [
    "monarchy-formal-practice-boundary",
    "idea-constitutional-monarchs-source",
    "pp. 7–13, discretion, advice, and constitutional conventions",
    "supports",
    "formal-practice",
  ],
  [
    "monarchy-reserve-delegated-boundary",
    "idea-constitutional-monarchs-source",
    "pp. 7–13, advice and discretionary powers",
    "supports",
    "reserve",
  ],
  [
    "monarchy-democracy-boundary",
    "idea-constitutional-monarchs-source",
    "pp. 3–6, monarchy within parliamentary democracies",
    "supports",
    "democracy",
  ],
  [
    "monarchy-authoritarian-boundary",
    "idea-constitutional-monarchs-source",
    "pp. 3–6, limited scope to parliamentary constitutional monarchy",
    "qualifies",
    "authoritarian",
  ],
  [
    "monarchy-theocracy-boundary",
    "saudi-basic-law-source",
    "articles 1 and 7",
    "context",
    "sacred",
  ],
  [
    "monarchy-republic-boundary",
    "idea-constitutional-monarchs-source",
    "p. 10, ‘Republic or monarchy?’",
    "supports",
    "empire",
  ],
  [
    "monarchy-empire-boundary",
    "sep-colonialism-monarchy-boundaries-source",
    "section 1, paragraphs 4–7, imperialism and control over dependent territory",
    "supports",
    "empire-boundary",
  ],
  [
    "monarchy-empire-boundary",
    "idea-constitutional-monarchs-source",
    "pp. 3–6, monarch as head of state in the primer's bounded parliamentary context",
    "qualifies",
    "empire-boundary-monarchy-office",
  ],
  [
    "monarchy-colonial-rule-boundary",
    "sep-colonialism-monarchy-boundaries-source",
    "opening definition and section 1, paragraphs 1–3",
    "supports",
    "colonial-boundary",
  ],
  [
    "monarchy-colonial-rule-boundary",
    "idea-constitutional-monarchs-source",
    "pp. 3–6, monarch as head of state in the primer's bounded parliamentary context",
    "qualifies",
    "colonial-boundary-monarchy-office",
  ],
  [
    "monarchy-nobility-boundary",
    "oxford-nobility-definition-source",
    "sense 1, ‘the nobility’",
    "supports",
    "nobility-boundary",
  ],
  [
    "monarchy-nobility-boundary",
    "idea-constitutional-monarchs-source",
    "pp. 3–6, monarch as head of state in the primer's bounded parliamentary context",
    "qualifies",
    "nobility-boundary-monarchy-office",
  ],
  [
    "japan-emperor-symbol-rule",
    "japan-constitution-moj-source",
    "article 1; Japanese text and government reference translation; site disclaimer",
    "supports",
    "japan-symbol",
  ],
  [
    "japan-constitution-commencement",
    "japan-constitution-moj-source",
    "law date 3 November 1946 and article 100, six-month commencement rule",
    "supports",
    "japan-commencement",
  ],
  [
    "japan-emperor-no-government-powers",
    "japan-constitution-moj-source",
    "article 4",
    "supports",
    "japan-no-power",
  ],
  [
    "japan-emperor-cabinet-advice",
    "japan-constitution-moj-source",
    "article 3",
    "supports",
    "japan-cabinet",
  ],
  [
    "japan-emperor-enumerated-acts",
    "japan-constitution-moj-source",
    "articles 6–7",
    "supports",
    "japan-acts",
  ],
  [
    "japan-succession-male-line",
    "japan-imperial-house-law-source",
    "article 1, Japanese source text on e-Gov",
    "supports",
    "japan-succession",
  ],
  [
    "japan-practice-influence-question",
    "shugiin-emperor-study-source",
    "‘Main points of Prof. YOKOTA’s statement,’ sections 1–5, especially sections 3–5",
    "supports",
    "japan-study",
  ],
  [
    "tonga-2013-assembly-composition",
    "tonga-constitution-constitute-source",
    "clauses 59–60, composition and representative members",
    "supports",
    "tonga-seats",
  ],
  [
    "tonga-king-appoints-pm",
    "tonga-constitution-constitute-source",
    "clause 50A, election and appointment of Prime Minister",
    "supports",
    "tonga-pm",
  ],
  [
    "tonga-retained-royal-formal-powers",
    "tonga-constitution-constitute-source",
    "clause 50, Privy Council",
    "supports",
    "tonga-council",
  ],
  [
    "tonga-cabinet-executive-design",
    "tonga-constitution-constitute-source",
    "clauses 50A–51, Prime Minister and Cabinet",
    "supports",
    "tonga-cabinet",
  ],
  [
    "tonga-2010-government-formation",
    "tonga-crown-law-prime-minister-2010-source",
    "media release dated 24 December 2010, first page, paragraphs 2–3",
    "supports",
    "tonga-accountability",
  ],
  [
    "tonga-record-mediation-boundary",
    "tonga-constitution-constitute-source",
    "title page and document metadata; no translator or source-text provenance stated",
    "qualifies",
    "tonga-history",
  ],
  [
    "saudi-monarchy-basic-law",
    "saudi-basic-law-source",
    "article 5(a), consulted English consolidation",
    "supports",
    "saudi-form",
  ],
  [
    "saudi-succession-designation",
    "saudi-basic-law-source",
    "article 5(b)",
    "supports",
    "saudi-succession",
  ],
  [
    "saudi-crown-prince-designation",
    "saudi-basic-law-source",
    "article 5(c)",
    "supports",
    "saudi-crown-prince",
  ],
  [
    "saudi-basic-law-king-prime-minister-clause",
    "saudi-basic-law-source",
    "articles 55–56",
    "supports",
    "saudi-formal-executive",
  ],
  [
    "saudi-2022-crown-prince-prime-minister",
    "spa-2022-prime-minister-order-source",
    "first royal order, paragraphs 1–2, 27 September 2022",
    "supports",
    "saudi-current-pm",
  ],
  [
    "saudi-religious-law-rule",
    "saudi-basic-law-source",
    "articles 1 and 7",
    "supports",
    "saudi-law",
  ],
  [
    "saudi-theocracy-classification-boundary",
    "loc-saudi-country-study-source",
    "printed pp. 208–209, ‘Islam’ and religious-legal institutions",
    "qualifies",
    "saudi-theocracy",
  ],
  [
    "saudi-theocracy-classification-boundary",
    "saudi-basic-law-source",
    "articles 1 and 7, stated religious sources of authority",
    "context",
    "saudi-theocracy-basic-law",
  ],
  [
    "saudi-dynastic-rules-in-use",
    "herb-all-in-family-source",
    "chapter 1, printed p. 8 (PDF p. 10), definition of dynastic monarchy",
    "supports",
    "saudi-dynasty",
  ],
  [
    "saudi-ruling-family-institution-herb",
    "herb-all-in-family-source",
    "chapter 1, printed p. 8 (PDF p. 10), Saudi Arabia placement and family participation contrast",
    "supports",
    "saudi-family-institution",
  ],
  [
    "three-cases-nonrepresentative",
    "idea-constitutional-monarchs-source",
    "pp. 3–13, bounded constitutional-monarchy typology",
    "qualifies",
    "cases-boundary",
  ],
];

const related = (id: string, objectId: string, statementIds: string[]) => ({
  documentType: "relationships" as const,
  subject: { kind: "concept" as const, id: "monarchy" },
  relationships: [
    {
      id,
      predicate: "related-to" as const,
      subject: { kind: "concept" as const, id: "monarchy" },
      object: { kind: "concept" as const, id: objectId },
      status: "qualified" as const,
      scope: {
        note: "A comparison link only; neither concept inherits the other's claims, classifications, institutions, or evaluations.",
      },
      statementIds,
    },
  ],
});

export const monarchyRelationshipDocuments = [
  {
    documentType: "relationships",
    subject: { kind: "approach", id: "constitutional-parliamentary-monarchy" },
    relationships: [
      {
        id: "constitutional-parliamentary-monarchy-interprets-monarchy",
        predicate: "interprets-concept",
        subject: {
          kind: "approach",
          id: "constitutional-parliamentary-monarchy",
        },
        object: { kind: "concept", id: "monarchy" },
        role: "core",
        interpretation:
          "A deliberately bounded constitutional-parliamentary configuration within the wider and more varied concept of monarchy.",
        status: "qualified",
        statementIds: [
          "monarchy-head-roles-boundary",
          "monarchy-reserve-delegated-boundary",
        ],
      },
    ],
  },
  {
    documentType: "relationships",
    subject: { kind: "case-episode", id: "saudi-basic-law-monarchy-episode" },
    relationships: [
      {
        id: "saudi-episode-partially-instantiated-executive-dynastic-monarchy",
        predicate: "partially-instantiated",
        subject: {
          kind: "case-episode",
          id: "saudi-basic-law-monarchy-episode",
        },
        object: { kind: "approach", id: "executive-dynastic-monarchy" },
        status: "qualified",
        statementIds: ["saudi-ruling-family-institution-herb"],
      },
    ],
  },
  {
    documentType: "relationships",
    subject: { kind: "approach", id: "executive-dynastic-monarchy" },
    relationships: [
      {
        id: "executive-dynastic-monarchy-interprets-monarchy",
        predicate: "interprets-concept",
        subject: { kind: "approach", id: "executive-dynastic-monarchy" },
        object: { kind: "concept", id: "monarchy" },
        role: "core",
        interpretation:
          "Herb's attributed analytical configuration within monarchy, not a synonym for absolute monarchy or every dynasty.",
        status: "qualified",
        statementIds: ["saudi-dynastic-rules-in-use"],
      },
    ],
  },
  related("monarchy-related-to-republic", "republic", [
    "monarchy-republic-boundary",
  ]),
  related("monarchy-related-to-democracy", "democracy", [
    "monarchy-democracy-boundary",
  ]),
  related("monarchy-related-to-authoritarianism", "authoritarianism", [
    "monarchy-authoritarian-boundary",
  ]),
  related("monarchy-related-to-theocracy", "theocracy", [
    "monarchy-theocracy-boundary",
    "saudi-theocracy-classification-boundary",
  ]),
  related("monarchy-related-to-succession", "monarchic-succession", [
    "monarchy-succession-varies",
  ]),
  related("monarchy-related-to-executive-authority", "executive-authority", [
    "monarchy-formal-practice-boundary",
    "saudi-basic-law-king-prime-minister-clause",
    "saudi-2022-crown-prince-prime-minister",
  ]),
  related(
    "monarchy-related-to-legislative-accountability",
    "legislative-accountability",
    ["monarchy-head-roles-boundary", "tonga-2010-government-formation"],
  ),
  ...rows.map(([statementId, sourceId, locator, role, suffix]) => ({
    documentType: "relationships" as const,
    subject: { kind: "statement" as const, id: statementId },
    relationships: [
      {
        id: `${statementId}-cites-${suffix}`,
        predicate: "cites" as const,
        subject: { kind: "statement" as const, id: statementId },
        object: { kind: "source" as const, id: sourceId },
        role,
        locator,
      },
    ],
  })),
] satisfies AuthoringDocument[];
