import type { AuthoringDocument } from "../../../src/lib/domain";

const socialism = { kind: "concept" as const, id: "socialism" };
const communism = { kind: "concept" as const, id: "communism" };

const citations = [
  [
    "socialism-contested-family",
    "gilabert-oneill-socialism-source",
    "sections 1–5",
    "supports",
    "socialism-family-sep",
  ],
  [
    "socialism-contested-family",
    "newman-socialism-vsi-source",
    "introduction and book abstract",
    "supports",
    "socialism-family-newman",
  ],
  [
    "socialism-democratic-control-minimum",
    "gilabert-oneill-socialism-source",
    "section 1, paragraphs 1–19",
    "supports",
    "socialism-control",
  ],
  [
    "socialism-not-statism",
    "gilabert-oneill-socialism-source",
    "section 1, paragraphs 18–19",
    "supports",
    "socialism-statism",
  ],
  [
    "socialism-market-boundary",
    "gilabert-oneill-socialism-source",
    "section 1, paragraphs 14–17; sections 4.1–4.2",
    "supports",
    "socialism-markets",
  ],
  [
    "socialism-three-distinct-questions",
    "gilabert-oneill-socialism-source",
    "section 2, paragraphs 1–5",
    "supports",
    "socialism-dimensions",
  ],
  [
    "socialism-values-newman",
    "newman-socialism-vsi-source",
    "introduction, pp. 1–5",
    "supports",
    "socialism-values",
  ],
  [
    "socialism-global-historical-variation",
    "newman-socialism-vsi-source",
    "chapters 2–5 and book abstract",
    "supports",
    "socialism-global",
  ],
  [
    "socialism-organizational-disagreement",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73, especially ‘Organizing Socialism’ and ‘Revolution and Reform Under the Second International’",
    "supports",
    "socialism-organization",
  ],
  [
    "socialism-communism-overlap-boundary",
    "newman-socialism-vsi-source",
    "chapters 1–3",
    "supports",
    "overlap-newman",
  ],
  [
    "socialism-communism-overlap-boundary",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73",
    "supports",
    "overlap-eley",
  ],
  [
    "socialism-communism-overlap-boundary",
    "lenin-state-revolution-progress-source",
    "chapters I and V",
    "context",
    "overlap-lenin",
  ],
  [
    "socialism-communism-overlap-boundary",
    "kropotkin-conquest-bread-source",
    "chapters 2–3",
    "context",
    "overlap-kropotkin",
  ],
  [
    "communism-multiple-referents",
    "newman-socialism-vsi-source",
    "chapters 2–3",
    "supports",
    "communism-referents-newman",
  ],
  [
    "communism-multiple-referents",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73",
    "supports",
    "communism-referents-eley",
  ],
  [
    "manifesto-communist-immediate-aim",
    "communist-manifesto-avalon-source",
    "part II, paragraphs 1–10",
    "supports",
    "manifesto-aim",
  ],
  [
    "manifesto-bourgeois-property-boundary",
    "communist-manifesto-avalon-source",
    "part II, paragraphs 11–31",
    "supports",
    "manifesto-property",
  ],
  [
    "manifesto-common-property-class-character",
    "communist-manifesto-avalon-source",
    "part II, paragraphs 22–31",
    "supports",
    "manifesto-common-property",
  ],
  [
    "marx-lower-communist-phase",
    "marx-gotha-critique-progress-source",
    "part I, pp. 16–19 of the 1970 edition",
    "supports",
    "gotha-lower",
  ],
  [
    "marx-higher-communist-phase",
    "marx-gotha-critique-progress-source",
    "part I, p. 19 of the 1970 edition",
    "supports",
    "gotha-higher",
  ],
  [
    "lenin-transitional-state-claim",
    "lenin-state-revolution-progress-source",
    "chapter I §4; Collected Works vol. 25, pp. 400–413",
    "supports",
    "lenin-transition",
  ],
  [
    "lenin-state-withering-claim",
    "lenin-state-revolution-progress-source",
    "chapter I §4 and chapter V §§1–4; Collected Works vol. 25, pp. 400–413, 464–482",
    "supports",
    "lenin-withering",
  ],
  [
    "kropotkin-anarchist-communist-route",
    "kropotkin-conquest-bread-source",
    "chapter 3 §I",
    "supports",
    "kropotkin-distribution",
  ],
  [
    "kropotkin-nonparliamentary-route",
    "kropotkin-conquest-bread-source",
    "chapter 2 §III",
    "supports",
    "kropotkin-route",
  ],
  [
    "communism-early-global-variation",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73, especially the M. N. Roy and José Carlos Mariátegui vignettes",
    "supports",
    "communism-global",
  ],
  [
    "communist-label-non-embodiment",
    "marx-gotha-critique-progress-source",
    "part I, pp. 16–19 of the 1970 edition",
    "context",
    "label-boundary-gotha",
  ],
  [
    "communist-label-non-embodiment",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73",
    "supports",
    "label-boundary-eley",
  ],
] as const;

export const socialismCommunismRelationshipDocuments = [
  {
    documentType: "relationships",
    subject: socialism,
    relationships: [
      {
        id: "socialism-related-to-communism",
        predicate: "related-to",
        subject: socialism,
        object: communism,
        status: "qualified",
        statementIds: ["socialism-communism-overlap-boundary"],
      },
      {
        id: "socialism-related-to-social-ownership",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "social-ownership" },
        status: "qualified",
        statementIds: [
          "socialism-democratic-control-minimum",
          "socialism-not-statism",
        ],
      },
      {
        id: "socialism-related-to-economic-democracy",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "economic-democracy" },
        status: "qualified",
        statementIds: ["socialism-democratic-control-minimum"],
      },
      {
        id: "socialism-related-to-social-democracy",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "social-democracy" },
        status: "contested",
        statementIds: [
          "socialism-contested-family",
          "social-democracy-contested-capitalism-boundary",
        ],
      },
      {
        id: "socialism-related-to-market-socialism",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "market-socialism" },
        status: "qualified",
        statementIds: ["socialism-market-boundary"],
      },
    ],
  },
  {
    documentType: "relationships",
    subject: communism,
    relationships: [
      {
        id: "communism-related-to-socialism",
        predicate: "related-to",
        subject: communism,
        object: socialism,
        status: "qualified",
        statementIds: ["socialism-communism-overlap-boundary"],
      },
      {
        id: "communism-related-to-social-ownership",
        predicate: "related-to",
        subject: communism,
        object: { kind: "concept", id: "social-ownership" },
        status: "qualified",
        statementIds: [
          "manifesto-bourgeois-property-boundary",
          "manifesto-common-property-class-character",
        ],
      },
    ],
  },
  ...citations.map(([statementId, sourceId, locator, role, id]) => ({
    documentType: "relationships" as const,
    subject: { kind: "statement" as const, id: statementId },
    relationships: [
      {
        id: `socialism-communism-${id}-citation`,
        predicate: "cites" as const,
        subject: { kind: "statement" as const, id: statementId },
        object: { kind: "source" as const, id: sourceId },
        role,
        locator,
      },
    ],
  })),
] satisfies AuthoringDocument[];
