import type { AuthoringDocument } from "../../../src/lib/domain";

const socialism = { kind: "concept" as const, id: "socialism" };
const communism = { kind: "concept" as const, id: "communism" };

const citations = [
  [
    "socialism-contested-family",
    "gilabert-oneill-socialism-source",
    "sections 1–5",
    "supports",
    "socialism-family-sep",
  ],
  [
    "socialism-contested-family",
    "newman-socialism-vsi-source",
    "introduction and book abstract",
    "supports",
    "socialism-family-newman",
  ],
  [
    "socialism-democratic-control-minimum",
    "gilabert-oneill-socialism-source",
    "section 1, paragraphs 1–19",
    "supports",
    "socialism-control",
  ],
  [
    "socialism-not-statism",
    "gilabert-oneill-socialism-source",
    "section 1, paragraphs 18–19",
    "supports",
    "socialism-statism",
  ],
  [
    "socialism-market-boundary",
    "gilabert-oneill-socialism-source",
    "section 1, paragraphs 14–17; sections 4.1–4.2",
    "supports",
    "socialism-markets",
  ],
  [
    "socialism-planning-designs",
    "gilabert-oneill-socialism-source",
    "section 4.1, paragraphs 1–2 and 9–12",
    "supports",
    "socialism-planning-designs-sep",
  ],
  [
    "socialism-three-distinct-questions",
    "gilabert-oneill-socialism-source",
    "section 2, paragraphs 1–5",
    "supports",
    "socialism-dimensions",
  ],
  [
    "socialism-values-newman",
    "newman-socialism-vsi-source",
    "introduction, pp. 1–5",
    "supports",
    "socialism-values",
  ],
  [
    "socialism-global-historical-variation",
    "newman-socialism-vsi-source",
    "chapters 2–5 and book abstract",
    "supports",
    "socialism-global",
  ],
  [
    "socialism-organizational-disagreement",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73, especially ‘Organizing Socialism’ and ‘Revolution and Reform Under the Second International’",
    "supports",
    "socialism-organization",
  ],
  [
    "modern-communist-traditions-within-socialist-debates",
    "newman-socialism-vsi-source",
    "chapters 1–3",
    "supports",
    "overlap-newman",
  ],
  [
    "modern-communist-traditions-within-socialist-debates",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73",
    "supports",
    "overlap-eley",
  ],
  [
    "communist-organizational-rivalry",
    "lenin-state-revolution-service-source",
    "chapters I and V",
    "context",
    "overlap-lenin",
  ],
  [
    "communist-organizational-rivalry",
    "kropotkin-conquest-bread-chapman-hall-source",
    "chapters 2–3",
    "context",
    "overlap-kropotkin",
  ],
  [
    "communism-multiple-referents",
    "newman-socialism-vsi-source",
    "chapters 2–3",
    "supports",
    "communism-referents-newman",
  ],
  [
    "communism-multiple-referents",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73",
    "supports",
    "communism-referents-eley",
  ],
  [
    "manifesto-communist-immediate-aim",
    "communist-manifesto-progress-source",
    "part II; 1969 edition pp. 108–109",
    "supports",
    "manifesto-aim",
  ],
  [
    "manifesto-bourgeois-property-boundary",
    "communist-manifesto-progress-source",
    "part II; 1969 edition pp. 109–111",
    "supports",
    "manifesto-property",
  ],
  [
    "manifesto-common-property-class-character",
    "communist-manifesto-progress-source",
    "part II; 1969 edition pp. 110–111",
    "supports",
    "manifesto-common-property",
  ],
  [
    "marx-lower-phase-inherited-limits",
    "marx-gotha-critique-carver-source",
    "pp. 213–215 of the 1996 Carver translation",
    "supports",
    "gotha-lower-limits",
  ],
  [
    "marx-lower-phase-labor-distribution",
    "marx-gotha-critique-carver-source",
    "pp. 213–215 of the 1996 Carver translation",
    "supports",
    "gotha-lower-distribution",
  ],
  [
    "marx-higher-phase-conditions",
    "marx-gotha-critique-carver-source",
    "pp. 215–216 of the 1996 Carver translation",
    "supports",
    "gotha-higher-conditions",
  ],
  [
    "marx-higher-phase-needs-distribution",
    "marx-gotha-critique-carver-source",
    "p. 215 of the 1996 Carver translation",
    "supports",
    "gotha-higher-distribution",
  ],
  [
    "lenin-transitional-state-claim",
    "lenin-state-revolution-service-source",
    "chapter I §4 in the 2009 Service translation",
    "supports",
    "lenin-transition",
  ],
  [
    "lenin-state-withering-claim",
    "lenin-state-revolution-service-source",
    "chapter I §4 and chapter V §§1–4 in the 2009 Service translation",
    "supports",
    "lenin-withering",
  ],
  [
    "kropotkin-anarchist-communist-route",
    "kropotkin-conquest-bread-chapman-hall-source",
    "chapter 3 §I",
    "supports",
    "kropotkin-distribution",
  ],
  [
    "kropotkin-nonparliamentary-route",
    "kropotkin-conquest-bread-chapman-hall-source",
    "chapter 2 §III",
    "supports",
    "kropotkin-route",
  ],
  [
    "eley-early-communist-network-geography",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73, especially the M. N. Roy and José Carlos Mariátegui vignettes",
    "supports",
    "communism-global-geography",
  ],
  [
    "eley-comintern-local-revision-interpretation",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73, especially the M. N. Roy and José Carlos Mariátegui vignettes",
    "supports",
    "communism-global-interpretation",
  ],
  [
    "communist-label-non-embodiment",
    "marx-gotha-critique-carver-source",
    "pp. 213–216 of the 1996 Carver translation",
    "context",
    "label-boundary-gotha",
  ],
  [
    "communist-label-non-embodiment",
    "eley-marxism-socialist-revolution-source",
    "pp. 49–73",
    "supports",
    "label-boundary-eley",
  ],
] as const;

export const socialismCommunismRelationshipDocuments = [
  {
    documentType: "relationships",
    subject: socialism,
    relationships: [
      {
        id: "socialism-related-to-communism",
        predicate: "related-to",
        subject: socialism,
        object: communism,
        status: "qualified",
        statementIds: [
          "modern-communist-traditions-within-socialist-debates",
          "communist-organizational-rivalry",
        ],
      },
      {
        id: "socialism-related-to-social-ownership",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "social-ownership" },
        status: "qualified",
        statementIds: [
          "socialism-democratic-control-minimum",
          "socialism-not-statism",
        ],
      },
      {
        id: "socialism-related-to-economic-democracy",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "economic-democracy" },
        status: "qualified",
        statementIds: ["socialism-democratic-control-minimum"],
      },
      {
        id: "socialism-related-to-social-democracy",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "social-democracy" },
        status: "contested",
        statementIds: [
          "socialism-contested-family",
          "social-democracy-contested-capitalism-boundary",
        ],
      },
      {
        id: "socialism-related-to-market-socialism",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "market-socialism" },
        status: "qualified",
        statementIds: ["socialism-market-boundary"],
      },
      {
        id: "socialism-related-to-economic-planning",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "economic-planning" },
        status: "qualified",
        statementIds: ["socialism-planning-designs"],
      },
      {
        id: "socialism-related-to-market-coordination",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "market-coordination" },
        status: "qualified",
        statementIds: ["socialism-market-boundary"],
      },
      {
        id: "socialism-related-to-social-class",
        predicate: "related-to",
        subject: socialism,
        object: { kind: "concept", id: "social-class" },
        status: "qualified",
        statementIds: [
          "socialism-democratic-control-minimum",
          "modern-communist-traditions-within-socialist-debates",
        ],
      },
    ],
  },
  {
    documentType: "relationships",
    subject: communism,
    relationships: [
      {
        id: "communism-related-to-socialism",
        predicate: "related-to",
        subject: communism,
        object: socialism,
        status: "qualified",
        statementIds: [
          "modern-communist-traditions-within-socialist-debates",
          "communist-organizational-rivalry",
        ],
      },
      {
        id: "communism-related-to-social-ownership",
        predicate: "related-to",
        subject: communism,
        object: { kind: "concept", id: "social-ownership" },
        status: "qualified",
        statementIds: [
          "manifesto-bourgeois-property-boundary",
          "manifesto-common-property-class-character",
        ],
      },
      {
        id: "communism-related-to-social-class",
        predicate: "related-to",
        subject: communism,
        object: { kind: "concept", id: "social-class" },
        status: "qualified",
        statementIds: [
          "manifesto-communist-immediate-aim",
          "manifesto-common-property-class-character",
        ],
      },
      {
        id: "communism-related-to-statelessness",
        predicate: "related-to",
        subject: communism,
        object: { kind: "concept", id: "statelessness" },
        status: "contested",
        statementIds: [
          "communist-organizational-rivalry",
          "lenin-state-withering-claim",
          "kropotkin-anarchist-communist-route",
        ],
      },
    ],
  },
  ...citations.map(([statementId, sourceId, locator, role, id]) => ({
    documentType: "relationships" as const,
    subject: { kind: "statement" as const, id: statementId },
    relationships: [
      {
        id: `socialism-communism-${id}-citation`,
        predicate: "cites" as const,
        subject: { kind: "statement" as const, id: statementId },
        object: { kind: "source" as const, id: sourceId },
        role,
        locator,
      },
    ],
  })),
] satisfies AuthoringDocument[];
