import type { AuthoringDocument } from "../../../src/lib/domain";

const citations = [
  ["sc-colored-convention-equal-suffrage-demand", "sc-1865-colored-convention-house-divided-source", "address in original proceedings, pp. 23–26", "supports"],
  ["sc-colored-convention-representation-argument", "sc-1865-colored-convention-house-divided-source", "address in original proceedings, pp. 23–26", "supports"],
  ["sc-organizer-meeting-reach-report", "sc-1867-black-organizer-ldhi-source", "letter dated August 2, 1867, paragraph beginning ‘I have travelled’", "supports"],
  ["sc-organizer-league-reach-report", "sc-1867-black-organizer-ldhi-source", "letter dated August 2, 1867, paragraph beginning ‘I have travelled’", "supports"],
  ["sc-organizer-report-scope-boundary", "sc-1867-black-organizer-ldhi-source", "single letter and LDHI provenance note", "qualifies"],

  ["sc-constitution-elector-membership-1868", "sc-1868-constitution-later-compilation-source", "Article VIII §2, printed p. 36", "supports"],
  ["sc-constitution-elector-residence-1868", "sc-1868-constitution-later-compilation-source", "Article VIII §2, printed p. 36", "supports"],
  ["sc-constitution-federal-disability-exclusion", "sc-1868-constitution-later-compilation-source", "Article VIII §2, printed p. 36", "supports"],
  ["sc-constitution-institutional-confinement-exclusion", "sc-1868-constitution-later-compilation-source", "Article VIII §2, printed p. 36", "supports"],
  ["sc-constitution-prison-confinement-exclusion", "sc-1868-constitution-later-compilation-source", "Article VIII §2, printed p. 36", "supports"],
  ["sc-constitution-enslavement-conviction-boundary", "sc-1868-constitution-later-compilation-source", "Article VIII §12, printed p. 37", "supports"],
  ["sc-constitution-county-office-elector-rule", "sc-1868-constitution-later-compilation-source", "Article VIII §7, printed p. 37", "supports"],
  ["sc-constitution-general-office-elector-rule", "sc-1868-constitution-later-compilation-source", "Article XIV §1, printed p. 47", "supports"],
  ["sc-constitution-first-election-residence-exception", "sc-1868-constitution-later-compilation-source", "Article VIII §11, printed p. 37", "supports"],
  ["sc-constitution-religious-office-test", "sc-1868-constitution-later-compilation-source", "Article XIV §6, printed p. 48", "supports"],
  ["sc-constitution-free-open-election-rule", "sc-1868-constitution-later-compilation-source", "Article I §31, printed p. 9", "supports"],
  ["sc-constitution-equal-elect-and-be-elected-rule", "sc-1868-constitution-later-compilation-source", "Article I §31, printed p. 9", "supports"],
  ["sc-constitution-no-property-office-qualification", "sc-1868-constitution-later-compilation-source", "Article I §32, printed p. 9", "supports"],
  ["sc-constitution-election-protection-directive", "sc-1868-constitution-later-compilation-source", "Article I §33, printed p. 9", "supports"],
  ["sc-house-population-apportionment-rule", "sc-1868-constitution-later-compilation-source", "Article II §4, printed pp. 11–12", "supports"],
  ["sc-house-county-minimum-representation-rule", "sc-1868-constitution-later-compilation-source", "Article II §6, printed p. 12", "supports"],
  ["sc-constitution-later-amendment-boundary", "sc-1868-constitution-later-compilation-source", "amendment notes at printed pp. 55–57 and 109–110", "qualifies"],

  ["sc-ransier-opposed-education-voting-test", "sc-1868-convention-proceedings-scan-source", "printed pp. 829–830", "supports"],
  ["sc-ransier-opposed-property-voting-test", "sc-1868-convention-proceedings-scan-source", "printed pp. 829–830", "supports"],
  ["sc-ransier-suffrage-self-defense-argument", "sc-1868-convention-proceedings-scan-source", "printed pp. 829–830", "supports"],
  ["sc-whipper-male-word-removal-motion", "sc-1868-convention-proceedings-scan-source", "printed pp. 836–839", "supports"],
  ["sc-whipper-woman-suffrage-argument", "sc-1868-convention-proceedings-scan-source", "printed pp. 838–839", "supports"],
  ["sc-whipper-motion-rejected", "sc-1868-convention-proceedings-scan-source", "printed p. 839", "supports"],
  ["sc-convention-adopted-constitution", "sc-1868-ratification-govinfo-source", "A. G. Mackey certification dated May 5, 1868", "supports"],
  ["sc-electors-ratified-constitution", "sc-1868-ratification-govinfo-source", "A. G. Mackey certification of the April 14–16 vote", "supports"],
  ["sc-congress-admitted-representation", "sc-1868-admission-house-history-source", "paragraph dated June 25, 1868", "supports"],
  ["sc-house-black-majority-1868-1876", "sc-black-political-activism-house-history-source", "paragraph beginning ‘But only in South Carolina’", "supports"],
  ["sc-senate-black-majority-1872-1876", "sc-black-political-activism-house-history-source", "paragraph beginning ‘But only in South Carolina’", "supports"],

  ["sc-enforcement-act-vote-intimidation-rule", "sc-klan-trials-fjc-source", "section ‘The statutes’ and discussion of §5", "supports"],
  ["sc-klan-act-voter-intimidation-rule", "sc-klan-trials-fjc-source", "section ‘The statutes’ and discussion of §2", "supports"],
  ["sc-hill-may-1871-assault-testimony", "sc-elias-hill-testimony-reproduction-source", "witness header and original printed pp. 1407–1408", "supports"],
  ["sc-hill-political-renunciation-demands", "sc-elias-hill-testimony-reproduction-source", "original printed p. 1408", "supports"],
  ["sc-hill-league-role-context", "sc-elias-hill-testimony-reproduction-source", "original printed p. 1408", "supports"],
  ["sc-bonner-league-meeting-cessation", "sc-freedpeople-testimony-ldhi-selection-source", "Alberry Bonner testimony, original printed pp. 444–445", "supports"],
  ["sc-grant-habeas-suspension-october-1871", "sc-klan-trials-fjc-source", "paragraph beginning ‘Alarmed by reports’", "supports"],
  ["sc-federal-mass-arrests-1871", "sc-klan-trials-fjc-source", "paragraph following the October suspension account", "supports"],
  ["sc-klan-prosecution-results", "sc-klan-trials-fjc-source", "proceedings and concluding assessment", "supports"],
  ["sc-klan-enforcement-short-term-assessment", "sc-klan-trials-fjc-source", "opening and concluding assessment", "supports"],
  ["sc-klan-enforcement-durability-limit", "sc-klan-trials-fjc-source", "concluding discussion extending through 1873–1885", "supports"],
  ["sc-congressional-testimony-mediation-boundary", "klan-evidence-history-source", "printed pp. 239–242", "supports"],
  ["sc-congressional-testimony-mediation-boundary", "sc-elias-hill-testimony-reproduction-source", "witness header and congressional volume provenance", "context"],

  ["sc-hamburg-red-shirt-militia-confrontation", "army-reconstruction-govinfo-source", "printed pp. 70–71, paragraph beginning ‘In South Carolina’", "supports"],
  ["sc-hamburg-bradley-six-executions-account", "army-reconstruction-govinfo-source", "printed p. 70", "supports"],
  ["sc-hamburg-stone-five-prisoners-account", "stone-hamburg-report-congressional-record-source", "Congressional Record—Senate, August 8, 1876, printed p. 5316", "supports"],
  ["sc-hamburg-victim-membership-boundary", "stone-hamburg-report-congressional-record-source", "printed p. 5316, Cook and captive-membership passages", "supports"],
  ["sc-hamburg-casualty-count-conflict", "army-reconstruction-govinfo-source", "printed p. 70", "qualifies"],
  ["sc-hamburg-casualty-count-conflict", "stone-hamburg-report-congressional-record-source", "printed p. 5316", "qualifies"],
  ["sc-hamburg-indictments-no-trials", "army-reconstruction-govinfo-source", "printed p. 70", "supports"],
  ["sc-rifle-club-organization-october-1876", "army-reconstruction-govinfo-source", "printed p. 70", "supports"],
  ["sc-rifle-club-intimidation-purpose", "army-reconstruction-govinfo-source", "printed p. 70", "supports"],
  ["sc-rifle-club-hampton-support-purpose", "army-reconstruction-govinfo-source", "printed p. 70", "supports"],
  ["sc-grant-rifle-club-disband-order", "army-reconstruction-govinfo-source", "printed p. 70", "supports"],
  ["sc-federal-reinforcement-1876", "army-reconstruction-govinfo-source", "printed pp. 70–71", "supports"],
  ["sc-disputed-election-rival-governors", "army-reconstruction-govinfo-source", "printed pp. 70–71", "supports"],
  ["sc-statehouse-troops-withdrawn-april-10", "anderson-intelligencer-usc-ocr-source", "April 12, 1877, p. 2, ‘The Troops Removed’", "supports"],
  ["sc-statehouse-troops-withdrawn-april-10", "usc-hampton-transfer-history-source", "account of troop withdrawal and Hampton's assumption of office", "context"],
  ["sc-chamberlain-transfer-correspondence-april-10", "anderson-intelligencer-usc-ocr-source", "April 12, 1877, p. 2, reproduced April 10 correspondence", "supports"],
  ["sc-executive-office-transferred-april-11", "anderson-intelligencer-usc-ocr-source", "April 12, 1877, p. 2, report following the correspondence", "supports"],
  ["sc-executive-office-transferred-april-11", "usc-hampton-transfer-history-source", "account of Hampton taking office on April 11", "context"],
  ["sc-office-transfer-case-boundary", "anderson-intelligencer-usc-ocr-source", "April 10 correspondence and April 11 office-transfer report", "supports"],
  ["sc-office-transfer-case-boundary", "sc-1868-constitution-later-compilation-source", "post-1877 amendment material in the compilation", "qualifies"],
  ["sc-reversal-causal-weight-boundary", "army-reconstruction-govinfo-source", "printed pp. 70–71", "qualifies"],
  ["sc-reversal-causal-weight-boundary", "anderson-intelligencer-usc-ocr-source", "April 10 correspondence and April 11 report", "qualifies"],
] as const;

export const southCarolinaReconstructionRelationshipDocuments = [
  {
    documentType: "relationships",
    subject: { kind: "case" as const, id: "south-carolina-reconstruction-political-membership" },
    relationships: [
      {
        id: "south-carolina-reconstruction-applies-to-democracy",
        predicate: "applies-to-case" as const,
        subject: { kind: "case" as const, id: "south-carolina-reconstruction-political-membership" },
        object: { kind: "concept" as const, id: "democracy" },
        status: "qualified" as const,
        scope: {
          startDate: "1868-01-14",
          endDate: "1877-04-11",
          placeIds: ["south-carolina"],
          note: "Tests electoral and officeholding membership, reported governing composition, and coercive limits under named South Carolina institutions; it does not classify the state or period as a pure embodiment of democracy.",
        },
        statementIds: [
          "sc-constitution-elector-membership-1868",
          "sc-constitution-institutional-confinement-exclusion",
          "sc-constitution-religious-office-test",
          "sc-house-black-majority-1868-1876",
          "sc-hill-political-renunciation-demands",
        ],
      },
    ],
  },
  ...citations.map(
    ([statementId, sourceId, locator, role]): AuthoringDocument => ({
      documentType: "relationships",
      subject: { kind: "statement", id: statementId },
      relationships: [
        {
          id: `${statementId}-cites-${sourceId}`,
          predicate: "cites",
          subject: { kind: "statement", id: statementId },
          object: { kind: "source", id: sourceId },
          role,
          locator,
        },
      ],
    }),
  ),
] satisfies AuthoringDocument[];
