import type { AuthoringDocument } from "../../../src/lib/domain";

const citations = [
  [
    "tawantinsuyu-name-boundary",
    "guaman-poma-coronica-source",
    "‘The chapter of the Inkas’, manuscript pp. 79–119",
    "supports",
    "naming",
  ],
  [
    "tawantinsuyu-chronology-boundary",
    "julien-reading-inca-history-source",
    "Introduction, pp. 3–21",
    "supports",
    "chronology",
  ],
  [
    "tawantinsuyu-ruler-kin-authority",
    "rostworowski-inca-realm-source",
    "chapters 3–4, pp. 25–62",
    "supports",
    "royal-kin",
  ],
  [
    "tawantinsuyu-provincial-indirect-rule",
    "oxford-handbook-incas-source",
    "chapter ‘Inca Political Organization, Economic Institutions, and Infrastructure’",
    "supports",
    "provincial-rule",
  ],
  [
    "tawantinsuyu-mita-labor",
    "daltroy-incas-source",
    "chapter 8, ‘The Political Economy’, pp. 267–305",
    "supports",
    "mita",
  ],
  [
    "tawantinsuyu-mita-labor",
    "guaman-poma-coronica-source",
    "‘The chapter of the general inspection, or census’, manuscript pp. 195–199",
    "context",
    "age-service",
  ],
  [
    "tawantinsuyu-storage-evidence",
    "daltroy-hastorf-storehouses-source",
    "abstract; pp. 334–349, especially Table 1 and conclusion",
    "supports",
    "xauxa-storage",
  ],
  [
    "tawantinsuyu-road-labor",
    "nmai-great-inka-road-source",
    "‘Building the Road’ and ‘Mit’a and Ayni—Labor and Reciprocity’",
    "supports",
    "road-labor",
  ],
  [
    "tawantinsuyu-road-power-limit",
    "oxford-handbook-incas-source",
    "chapter ‘Conclusions: Inca Imperial Identities: Colonization, Resistance, and Hybridity’",
    "supports",
    "regional-road-limit",
  ],
  [
    "tawantinsuyu-land-resource-plurality",
    "daltroy-incas-source",
    "chapter 8, ‘The Political Economy’, pp. 267–305",
    "supports",
    "resource-domains",
  ],
  [
    "tawantinsuyu-mitmaq-resettlement",
    "daltroy-incas-source",
    "chapter 9, ‘The Imperial Order’, pp. 306–342",
    "supports",
    "mitmaq",
  ],
  [
    "tawantinsuyu-warfare-incorporation",
    "rostworowski-inca-realm-source",
    "chapters 5–6, pp. 63–92",
    "supports",
    "incorporation",
  ],
  [
    "tawantinsuyu-gender-status-variation",
    "oxford-handbook-incas-source",
    "chapter ‘Gender and Status in Inca Textile and Ceramic Craft Production’, pp. 283–302",
    "supports",
    "gender-status",
  ],
  [
    "tawantinsuyu-huanuco-material",
    "huanuco-pampa-project-source",
    "Introduction, pp. 1–23; chapters 4–6, pp. 75–132",
    "supports",
    "huanuco",
  ],
  [
    "tawantinsuyu-reciprocity-interpretation",
    "murra-economic-organization-source",
    "chapters 3–5, pp. 49–135",
    "supports",
    "murra",
  ],
  [
    "tawantinsuyu-extraction-rival",
    "daltroy-earle-staple-finance-source",
    "pp. 187–206, especially pp. 190–197",
    "supports",
    "staple-finance",
  ],
  [
    "tawantinsuyu-chronicle-mediation",
    "oxford-handbook-incas-source",
    "Introduction, pp. 3–21",
    "supports",
    "chronicle-criticism",
  ],
  [
    "tawantinsuyu-chronicle-mediation",
    "adorno-guaman-poma-source",
    "Introduction to the second edition, pp. xii–xx; ‘Writing and Religion: The Visita Report’, pp. li–lv",
    "supports",
    "guaman-poma-genre",
  ],
  [
    "tawantinsuyu-chronicle-mediation",
    "cieza-chronicle-peru-source",
    "1880 Jiménez de la Espada edition, Proemio and chapters I–VI",
    "context",
    "cieza-genre",
  ],
  [
    "tawantinsuyu-guaman-poma-service",
    "guaman-poma-coronica-source",
    "‘First age: auca camayoc’, manuscript pp. 195–197; ‘Second age: puriq machu’, pp. 198–199",
    "supports",
    "guaman-poma-service",
  ],
  [
    "tawantinsuyu-non-embodiment",
    "daltroy-incas-source",
    "chapters 7–9, pp. 233–342",
    "supports",
    "institutional-mixture",
  ],
  [
    "tawantinsuyu-non-embodiment",
    "daltroy-earle-staple-finance-source",
    "pp. 187–206",
    "context",
    "coercive-finance",
  ],
] as const;

export const tawantinsuyuRelationshipDocuments = citations.map(
  ([statementId, sourceId, locator, role, suffix]): AuthoringDocument => ({
    documentType: "relationships",
    subject: { kind: "statement", id: statementId },
    relationships: [
      {
        id: `${statementId}-cites-${suffix}`,
        predicate: "cites",
        subject: { kind: "statement", id: statementId },
        object: { kind: "source", id: sourceId },
        role,
        locator,
      },
    ],
  }),
) satisfies AuthoringDocument[];
