export const reviewedOrientationOnlyMappings = {
  "constitutional-parliamentary-monarchy": "Constitutional monarchy",
  "executive-authority": "Executive (government)",
  "active-labor-market-adjustment": "Active labour market policies",
  "affected-community-accountability": "Accountability",
  "anarchist-traditions": "Anarchism",
  "anarcho-syndicalist-organizing": "Anarcho-syndicalism",
  "athens-411-constitutional-change": "Athenian coup of 411 BC",
  "athens-four-hundred-five-thousand-411-bce": "Athenian coup of 411 BC",
  "andes-tawantinsuyu": "Inca Empire",
  "bonjol-melayu-ulayat-governance": "Minangkabau people",
  "bonjol-ulayat-governance-2000-2016": "Minangkabau people",
  "central-planning-arrangements": "Economic planning",
  "centralized-solidaristic-bargaining-1956-1983": "Rehn–Meidner model",
  "china-dual-track-market-reforms": "Reform and opening up",
  "china-plan-market-coexistence-1978-1993": "Reform and opening up",
  "collective-capital-formation": "Capital formation",
  "combahee-organizing-episode": "Combahee River Collective",
  "combahee-river-collective-1974-1980": "Combahee River Collective",
  "democratic-traditions": "Democracy",
  "democratic-selection-means": "Democracy",
  "electoral-representation": "Democracy",
  "english-agrarian-market-dependence": "British Agricultural Revolution",
  "english-agrarian-transformation-1450-1750":
    "British Agricultural Revolution",
  "equal-political-standing": "Social equality",
  "fascist-movements": "Fascism",
  "feminist-traditions": "Feminism",
  "freedom-as-nondomination": "Republicanism",
  "freedom-from-domination": "Republicanism",
  "gold-coast-cocoa-expansion": "Cocoa production in Ghana",
  "gold-coast-cocoa-takeoff-1890-1936": "Cocoa production in Ghana",
  "historical-italian-fascism": "Fascism",
  "iceland-parental-leave-2000-2018": "Parental leave",
  "iceland-parental-leave-outcomes-episode": "Parental leave",
  "india-constitutional-rights-episode": "Constitution of India",
  "india-constitutional-rights-settlement-1946-1950": "Constitution of India",
  "indigenous-autonomy": "Self-determination",
  "institutional-formation": "Institutional theory",
  "italian-fascist-consolidated-rule": "Fascism",
  "italian-fascist-dictatorship-1925-1943": "Fascism",
  "jinst-sum": "Jinst",
  "japan-constitutional-rights-episode": "Constitution of Japan",
  "japan-constitutional-rights-settlement-1946-1947": "Constitution of Japan",
  "japan-symbolic-emperorship-1947-2004": "Emperor of Japan",
  "japan-symbolic-emperorship-episode": "Emperor of Japan",
  "kahnawake-cdmrp-2005-present": "Kahnawake",
  "kahnawake-community-lawmaking": "Kahnawake",
  "koto-tinggi-governance-2016": "Minangkabau people",
  "koto-tinggi-post-decentralization-governance": "Minangkabau people",
  "linz-regime-analysis": "Juan Linz",
  "market-coordination": "Market economy",
  "legislative-accountability": "Accountability",
  "monarchic-succession": "Order of succession",
  "member-owned-cooperative-finance": "Cooperative banking",
  "nazi-consolidation-1933": "Adolf Hitler's rise to power",
  "nazi-party-state-consolidation-1933": "Adolf Hitler's rise to power",
  "neo-republican-nondomination": "Republicanism",
  "nontransferable-parental-leave": "Parental leave",
  "planning-correctability": "Economic planning",
  "planning-information-and-coordination": "Economic planning",
  "cmp-operation-1943-1945": "Economic planning",
  "controlled-materials-allocation": "Economic planning",
  "regional-wage-earner-fund-boards": "Rehn–Meidner model",
  "enacted-wage-earner-funds-1984-1991": "Rehn–Meidner model",
  "liquidation-board-period-1992": "Rehn–Meidner model",
  "republican-traditions": "Republicanism",
  "representative-democratic-government": "Democracy",
  "restrictive-macroeconomic-demand-management": "Demand management",
  "right-to-buy-england-wales-1980-1998": "Right to Buy",
  "right-to-buy-initial-operation": "Right to Buy",
  "rotating-municipal-delegation": "Delegate model of representation",
  "ruwalla-borderland-1918-1936": "Ruwallah",
  "ruwalla-borderland-organization": "Ruwallah",
  "self-employed-worker-unionism": "Trade union",
  "sewa-ahmedabad-1972-1977": "Trade union",
  "sewa-ahmedabad-institutions-episode": "Trade union",
  "solidaristic-wage-bargaining": "Rehn–Meidner model",
  "saudi-basic-law-monarchy-1992-2022": "Politics of Saudi Arabia",
  "saudi-basic-law-monarchy-episode": "Politics of Saudi Arabia",
  "southwestern-syrian-desert-wadi-sirhan": "Syrian Desert",
  "spanish-anarchist-initiatives-1936-1939": "Anarchism",
  "spanish-anarchist-initiatives-war-episode": "Anarchism",
  statelessness: "Stateless society",
  "swatantra-early-opposition-episode": "Swatantra Party",
  "swatantra-opposition-organization-1959-1967": "Swatantra Party",
  "swedish-rehn-meidner-model": "Rehn–Meidner model",
  "swedish-solidaristic-bargaining": "Rehn–Meidner model",
  "tawantinsuyu-expansion-consolidation": "Inca Empire",
  "tawantinsuyu-succession-invasion": "Inca Empire",
  "totalitarianism-analyses": "Totalitarianism",
  "tonga-constitutional-settlement-2010-2013": "Politics of Tonga",
  "tonga-post-reform-monarchy-episode": "Politics of Tonga",
  "us-controlled-materials-plan": "Economic planning",
  "us-wartime-production-mobilization": "Economic planning",
  "wage-earner-fund-board-abolition": "Rehn–Meidner model",
  "wage-earner-funds-to-liquidation": "Rehn–Meidner model",
  "wage-earner-influence": "Rehn–Meidner model",
  "worker-union-federation": "Trade union federation",
  "wpb-requirements-committee": "War Production Board",
  "zapatista-autonomy-chiapas-1994-present": "Zapatista territories",
  "chiapas-zapatista-regions": "Zapatista territories",
  "zapatista-autonomy-reorganization-2023": "Zapatista territories",
  "zapatista-caracol-jbg-episode-2003-2023": "Zapatista territories",
  "zapatista-caracoles": "Zapatista territories",
  "zapatista-caracoles-jbg-formation-announced-2003": "Zapatista territories",
  "zapatista-gal-successor-episode-2023-present": "Zapatista territories",
  "zapatista-good-government-councils": "Zapatista territories",
  "zapatista-jbg-to-gal-transition-2023": "Zapatista territories",
  "zapatista-local-autonomous-governments": "Zapatista territories",
  "zapatista-support-base-communities": "Zapatista territories",
} as const;

export const orientationOnlyReason = (label: string, article: string) =>
  `${article} directly defines or situates ${label}; no Wikidata identity is asserted because the project target retains its authored kind, scope, or historical boundary.`;

export const reviewedOrientationOnlyGuideSubjects = {
  "guide-central-planning": "central-planning-arrangements",
  "guide-kahnawake-community-lawmaking": "kahnawake-community-lawmaking",
  "guide-ruwalla-borderland-organization": "ruwalla-borderland-organization",
} as const;
